### ISSUE TITLE
Native Auth on xportal hub extension doesnt function for view data

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1020]
Native Auth on xportal hub extension doesnt function for view data

![image](https://github.com/Itheum/data-dex/assets/121969933/562a18d0-6790-46a8-ae57-ef42d7455e49)

**Comment by damienen** [comment]
This is because of a multitude of factors:
1. Hub won't allow to download files
2. Some Marshal settings have to be changed in roder for the hub login to work
3. Some possible tweaks also needed to the code

Will defer to 1.7.0

**Comment by damienen** [comment]
Hub does not allow to download files, but explroer redirect now works
