### ISSUE TITLE
Session timeout behaviour to be ammended for NativeAuth.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1022]
Session timeout set to 1 hour 

Pass-Logout seen post 1 hour for xportal and defi wallet.

Fail-Logout not seen for web wallet post 1 hour

Fail- 1. Message seen for session timeout only once on xportal and defi wallet, not noticed on web wallet.
        2. Message was seen that session timeout in 43 minutes however even after 15 minutes it was still saying 43 minutes left.

**Comment by damienen** [comment]
Will investigate, but as it is not a blocker moving to 1.7.0

**Comment by damienen** [comment]
Will reopen if seen again.
