### ISSUE TITLE
Logging out from Datadex, does not log you out of the connected session on explorer.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1037]
Logging out from Datadex, does not log you out of the connected session on explorer.

Steps.
1. Make sure you are logged out of both datadex and explorer
2. log into datadex
3. Identify a TB and click on explore.
4. You will be automatically logged into the explorer with an access token
5. Now log out of the datadex.
6. You should be logged out of the explorer.

Actual behaviour, the user remains logged into the explorer.

**Comment by damienen** [comment]
This can't happen. The user should log out manually.
