### ISSUE TITLE
Connecting with xportal on datadex indicates invalid QR code.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1038]
Upon attempting to connect with xportal and scanning the QR code often there is a message of "invalid QR code" encountered.

https://test.datadex.itheum.io/

**Comment by fuzzyduke** [comment]
Also periodically takes alot of time for QR code to load.

![image](https://github.com/Itheum/data-dex/assets/121969933/980478a5-cccd-464a-89a6-d216238fd9ff)

**Comment by damienen** [comment]
Solved. Closing
