### ISSUE TITLE
Unable to buy any data NFT using devnet2

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/data-dex#1053]
Unable to buy any data NFT using devnet2

Steps to repro:

Login to  https://test.datadex.itheum.io/
Try to obtain any data nft from the marketplace
Notice that you receive an error that token cannot be loaded

![image](https://github.com/Itheum/data-dex/assets/141028717/b4530252-ecfa-416f-9dc9-1ec2b1af0b1f)

https://files.slack.com/files-pri/TD671GEP7-F060ARY9PPU/image.png

![image](https://github.com/Itheum/data-dex/assets/141028717/b482dcd0-ec90-4c3e-a240-2c48ba6f99bf)

Expected result: You are able to purchase the data nft whitout any issues.

**Comment by damienen** [comment]
Ohh, using devnet2? Damn, we did not implement that yet, of course it does not work.

Closing.
