### ISSUE TITLE
Make interactions table work for all contracts on Data Dex

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1056]
See XOXNO integration. We will see other possible contracts if needed afterwards

**Comment by bucurdavid** [comment]
I would move the logic to the backend service with a more general approach to support different marketplaces

**Comment by bucurdavid** [comment]
I use the following endpoint to observe interactions outside of our marketplace: https://explorer.multiversx.com/nfts/DATANFTFT-e936d4-04 (this will include other marketplace trades as well)

**Comment by damienen** [comment]
It's good for now. Closing.

**Comment by damienen** [comment]
Can you change the logic on data dex so it uses your endpoint rather than doing the tx parsing on the spot? With a PR to 1.8.0

**Comment by bucurdavid** [comment]
Data NFT Activity should have improved loading time and third party interactions as peer-to-peer transfers
