### ISSUE TITLE
Launching data NFT while being redirected from datadex doesnt reflect correctly on the explorer. [Native auth]

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1067]
Launching data NFT while being redirected from datadex doesnt reflect correctly on the explorer. [Native auth]

Steps

1. Go to the datadex-> wallet
2. Go the the music data NFT and click explore.
3.  Make sure you going to the stg link with the access token.
4. Launch the music data NFT.

Expected behaviour
1. Upon launching the tracks should play.

Actual Behaviour
1. App launches but the music does not play. Instead we see a native auth error.

![image](https://github.com/Itheum/data-dex/assets/121969933/fb29250b-ce58-44c3-8ea6-5ea34b623c52)

**Comment by damienen** [comment]
Solved. Closing.
