### ISSUE TITLE
Display issue of accepted tokens on guardrails page

### ISSUE THREAD

**Issue by 911-Benedek-RobertGeorge** [Itheum/data-dex#1068]
![Image](https://github.com/Itheum/data-dex/assets/72063093/7780d504-652f-4889-9482-39163ff43999)

**Comment by 911-Benedek-RobertGeorge** [comment]
If there would be more tokens, it will be scrollable 
![Image](https://github.com/Itheum/data-dex/assets/72063093/d1b95035-4418-4dd1-b426-a4ca79445fb2)

**Comment by damienen** [comment]
Done. Closing.
