### ISSUE TITLE
Update Live Uptime Check to handle private network cert issues

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1070]
We are not sure why the data marshal API is being blocked in some networks due to cert errors. this may be due to the fact the cert is not allowed in certain networks... this is a bug blocker to someone trying to procure a data nft

- We need a UX that can "catch" this specific error:
<img width="1307" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/31fdbcdb-41a2-4967-b018-c1c654e134fe">

<img width="856" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/3b530c31-4e3f-47e5-a9b8-0e8dcb936ce8">

<img width="521" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/ba4e9c1d-9dab-4b26-9e93-2ddfb26f1b29">

- The UI then tells the user that "The network's settings may be causing some issues... we recommend they switch your network and try again. OR proceed by accepting the risk that the data stream may be down"

@fuzzyduke pls help with some product scope for this issue.

**Comment by damienen** [comment]
Even if it fails and the error is a non http error show the error message

**Comment by damienen** [comment]
Solved. Closing.
