### ISSUE TITLE
When clicking on the details page from the Marketplace, it is reported that the page flickers.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1071]
When clicking on the details page from the Marketplace, it is reported that the page flickers.

MP

![image](https://github.com/Itheum/data-dex/assets/121969933/c498a5a0-0a67-4b28-b094-cf0ad0bea52f)

**Comment by damienen** [comment]
Could we have a video? Description is not very clear, @fuzzyduke

**Comment by damienen** [comment]
@newbreedofgeek any clue how to recreate?

**Comment by fuzzyduke** [comment]
Hi @damienen this was reported by a user while accessing a mobile device. I have not been able to reproduce this yet.

**Comment by fuzzyduke** [comment]
Additional information

1. Experienced on iOS mobile.
2. When clicking on the image, it takes multiple tries to register the click and open details page.

**Comment by 911-Benedek-RobertGeorge** [comment]
I have recreated the bug on iphone 11

**Comment by fuzzyduke** [comment]
Hi @damienen kindly assign to an iOS user.

**Comment by 911-Benedek-RobertGeorge** [comment]
how does it work on android? I have IOS, works fine, it should be the same as on android now

**Comment by fuzzyduke** [comment]
Works fine on android. Can close if the check is made on iOS.

Verified. Closing.
