### ISSUE TITLE
While accessing homepage of datadex a repeated page refresh is seen. 

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1072]
While accessing homepage of datadex a repeated page refresh is seen. 
The use is not loged in at this point. 

In some cases it was seen that after X number of autorefreshes the page stopped refreshing and would prompt the wallet selection..

datadex.itheum.io
test.datadex.itheum.io

**Comment by damienen** [comment]
Will be tested through continous usage. Closing.
