### ISSUE TITLE
Add "You already own this" badge to market place data nfts

### ISSUE THREAD

**Issue by 911-Benedek-RobertGeorge** [Itheum/data-dex#1077]
If the user already own that nft, show  a badge there 

![Image](https://github.com/Itheum/data-dex/assets/72063093/92615380-e7ad-42b3-982e-67a4adcb0e69)

like this : 

![Image](https://github.com/Itheum/data-dex/assets/72063093/673e08f8-321c-4337-8ec7-f2de72828597)

**Comment by damienen** [comment]
This adds to much computational stress. Let's defer this
