### ISSUE TITLE
Refactoring of the data-dex

### ISSUE THREAD

**Issue by Enciusan** [Itheum/data-dex#1079]
First thing it'll be Trading Data page.

**Comment by damienen** [comment]
Check that minting an NFT works as expected

**Comment by fuzzyduke** [comment]
Upon Minting the below error was encountered in one instance on pr #1125 

https://devnet-explorer.multiversx.com/transactions/a6df96fa67818e5d8d3b4ebc109f06ae22cefa3ee0e861db9dbc223e3c04fa58

**Comment by damienen** [comment]
Merged. Closing.
