### ISSUE TITLE
Enterprise Mint: Minting token fails when collection is created with Tax set.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1106]
Description:

1. Deploy Minter.
2. Create collection and set tax as well.
3. Mint a single token. 

Below error is seen, however it works for collections when tax is not set.

https://devnet-explorer.multiversx.com/transactions/1f2d9aa784fbbe595e3ece1eaa621aa5e39a4492d5cf0f770df9d825d97e297d

**Comment by damienen** [comment]
We need to deploy a new sdk version to npm

**Comment by damienen** [comment]
Solved. Closing
