### ISSUE TITLE
View data does not work in apps when using xportal hub login.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1107]
The below error message is seen when using xportal hub extension to view a file using Multiversx Infographics App.

![image](https://github.com/Itheum/data-dex/assets/121969933/c774702b-60e4-4939-b240-2f4f73ed43cc)

**Comment by fuzzyduke** [comment]
When viewing TB there seems to be another error.

![image](https://github.com/Itheum/data-dex/assets/121969933/16865585-99a3-4520-a869-3a8fa4594e6c)

**Comment by damienen** [comment]
I cannot reproduce this

**Comment by damienen** [comment]
Seems like this is happening even if I pass the currently used origin to the marshal. Any idea why it could happen, @newbreedofgeek ?

![Image](https://github.com/Itheum/data-dex/assets/44813558/e810de21-313a-430c-b120-26233ba5bc78)

**Comment by damienen** [comment]
Solved. Closing.
