### ISSUE TITLE
While purchasing an enterprise NFT(on datatdex) the below is encountered.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1109]
Pre condition: Collection is not transferrable on datadex.

While purchasing an enterprise NFT(on datatdex) the below is encountered.

Should a token be enabled for listing if it is non transferrable on an address?

![image](https://github.com/Itheum/data-dex/assets/121969933/9d58b721-937e-4961-8db3-7097a000a5eb)

**Comment by fuzzyduke** [comment]
It is also noticed that sometimes for a brief period the NFT is not seen in the wallet or the marketplace, it appears in the back marketplace after a few minutes.

**Comment by damienen** [comment]
Can't do anything about it. This is because the address is not whitelisted (the SC address) inside the collection controls
