### ISSUE TITLE
File access in wallet of explorer initially shows files in viewer however after a period of time start showing popup blocker message.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1114]
Wallet used: web wallet.

Noticed the below on test.explorer.

Observation:
Upon accessing the wallet, initially the files are viewable within the viewer, however it seems that after a period of time there seems to be a popup blocker, further upon accessing the file manually the next screenshot is encountered.

![image](https://github.com/Itheum/data-dex/assets/121969933/7b31a10b-1aa8-4865-bb38-77e3854441bc)

![image](https://github.com/Itheum/data-dex/assets/121969933/5bda527b-3aa2-4ff2-aa37-327264e5345f)

https://test.explorer.itheum.io/%7B%20%20%20%20%22data_stream%22:%20%7B%20%20%20%20%20%20%20%20%22name%22:%20%22trailblazer%22,%20%20%20%20%20%20%20%20%22creator%22:%20%22Itheum%22,%20%20%20%20%20%20%20%20%22created_on%22:%20%222023-05-22T05:37:17Z%22,%20%20%20%20%20%20%20%20%22last_modified_on%22:%20%222023-08-29T04:45:44Z%22%20%20%20%20%7D,%20%20%20%20%22data%22:%20[%20%20%20%20%20%20%20%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Feature%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222022-10-06T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Morningstar%20Ventures%20Project%20Review%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://twitter.com/Morningstar_vc/status/1577801459013386240%22%20%20%20%20%20%20%20%20%7D,%20%20%20%20%20%20%20%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Tech%20Team%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-03-19T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Bucharest%20Hackathon%20Winners%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://twitter.com/ThisIsMarkPaul/status/1637407056524353536%22%20%20%20%20%20%20%20%20%7D,%20%20%20%20%20%20%20%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Event%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-04-26T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22ICI/CIP%20Forum%20Conference%20Bucharest%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://twitter.com/itheum/status/1650786375707361281%22%20%20%20%20%20%20%20%20%7D,%20%20%20%20%20%20%20%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Community%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-05-05T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Community%20Call%20#5%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://twitter.com/itheum/status/1653694614715392000%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Ecosystem%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-05-16T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Canary%20Net%20Explained%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://twitter.com/itheum/status/1658430080492634115%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Ecosystem%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-05-25T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Understanding%20CanaryNet:%20Itheum's%20Guarded%20Data%20NFT%20Launch%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://open.spotify.com/episode/3NYzCxA4t9C2PjclA2g6EY%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Ecosystem%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-06-30T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Data%20NFTs:%20The%20Future%20of%20Data%20Ownership%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://medium.com/itheum-newsletter/data-nfts-welcome-to-the-future-of-data-ownership-e282d9b1d537%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Ecosystem%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-04T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Introducing%20the%20Trailblazer%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://medium.com/itheum-newsletter/embrace-the-future-of-data-introducing-the-trailblazer-a-community-engagement-tool-built-on-789f504637d5?source=user_profile---------2----------------------------%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quiz%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-07T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22[Trailblazer%20Quiz#1%20:%20PeerMe%20-%20End%20Date%2009/08/2023%20at%2012%20GMT]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/C46iCu4EzdQvGiDM8%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quiz%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-07T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22[Trailblazer%20Quiz#1%20:%20Knights%20of%20Cathena%20-%20End%20Date%2009/08/2023%20at%2012%20GMT]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/TRDt5dViPfsZtBk49%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quiz%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-07T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22[Trailblazer%20Quiz#1%20:%20Bware%20Labs%20-%20End%20Date%2008/08/2023%20at%2012%20GMT]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/28424BaJ89nt5n5t8%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quiz%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-07T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22[Trailblazer%20Quiz#1%20:%20AshSwap%20-%20End%20Date%2008/08/2023%20at%2012%20GMT]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/bdQvLKw2M2ACGPHq5%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quiz%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-07T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22[Trailblazer%20Quiz#1%20:%20Giants%20Village%20-%20End%20Date%2008/08/2023%20at%2012%20GMT]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/NQVpXZSgiJAnb6GC9%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quiz%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-07T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22[Trailblazer%20Quiz#1%20:%20BH%20Network%20-%20End%20Date%2008/08/2023%20at%2012%20GMT]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/1mK86jYLzGBXUFoaA%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Ecosystem%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-23T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Whitelisting%20Process%20to%20mint%20you%20Data%20NFT%20is%20now%20live.%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://medium.com/itheum-newsletter/the-whitelisting-process-is-now-live-apply-to-mint-your-data-as-nfts-on-itheums-data-marketplace-799361c15099%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quest%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-07-24T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Trailblazer%20Quest#1%20Bonus%20Task-Let's%20meet%20each%20other%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://forms.gle/oD6mXxBdWW7vJXi16%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Leaderboard%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-08-08T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Points%20Trailblazer%20Quest#1%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%220x88..91_310:0x78..94_200:0x981.92_150:0x18..91_120:0x28..94_233:0x54..34_110%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Quest%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-08-29T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Trailblazer%20Quest#3.1%20Let's%20meet%20[End%20time%20-%2009:00%20GMT%2029/08/2023]%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://zealy.io/c/ests/questboard/a1293602-69b6-43e9-a6ca-01872e7085f2%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%22category%22:%20%22Offer%22,%20%20%20%20%20%20%20%20%20%20%20%20%22date%22:%20%222023-09-01T00:00:00Z%22,%20%20%20%20%20%20%20%20%20%20%20%20%22title%22:%20%22Codes%20for%20music%20festivals%22,%20%20%20%20%20%20%20%20%20%20%20%20%22link%22:%20%22https://leviathan616.myshopify.com/products/concert-ticket%22%20%20%20%20%20%20%20%20}%20%20%20%20]}

**Comment by damienen** [comment]
Can't reproduce anymore on @Enciusan 's branch after his fix. Solved. Closing.
