### ISSUE TITLE
Enterprise new wireframe functionality

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1117]
This is the collection view + freezing/wiping feature

**Comment by fuzzyduke** [comment]
It is noticed that freezing done should have an address input field. As only the creator address is frozen for that data NFT

Please clarify behavior @damienen for freezing
1. User should enter address or addresses upon which a single data NFT can be frozen. 
Currently it is seen that when freeze is invoked that only the creator address cannot list data NFTs.

**Comment by damienen** [comment]
In this case, the OWNER of the NFT is always frozen by design. There is no need to freeze any other address from this panel, as there is always only one owner and freezing their address for a specific nonce makes it unable for them to move it from their wallet

**Comment by damienen** [comment]
Works as expected. Closing.
