### ISSUE TITLE
Itheum Enterperise, No Action seen when trying to launch collection with tax

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1119]
Itheum Enterperise, No Action seen when trying to launch collection with tax

However, if the Tax box is unchecked and we attempt to launch then we see the transaction request in the wallet.

![image](https://github.com/Itheum/data-dex/assets/121969933/195bcad7-df5c-4635-b1d8-12a7b7ee25d1)

**Comment by Enciusan** [comment]
Closing, this is happen when you enter the wrong token identifier.
