### ISSUE TITLE
Itheum enterprise: Currently v 1.0.0 collections cannot be upgraded or accessed.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1120]
Itheum enterprise: Currently v 1.0.0 collections cannot be upgraded or accessed.

![image](https://github.com/Itheum/data-dex/assets/121969933/8996b686-f01c-4f9c-9a4d-3154e7bf4094)

**Comment by damienen** [comment]
Won't happen when in production. No need to fix it
