### ISSUE TITLE
Itheum Enterprise: If a second address has been permitted for mint, clarification is needed on the workflow.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1121]
Itheum Enterprise: If a second address has been permitted for mint, clarification is needed on the workflow.
Should the user B see the minter contract in the enterprise interface? (fig 2)
OR
Should the user be given the URL to mint a data NFT for the collection?

Fig 1
![image](https://github.com/Itheum/data-dex/assets/121969933/a9a0339e-8cf9-4286-aa50-b9966f4cd5d7)

Fig 2
![image](https://github.com/Itheum/data-dex/assets/121969933/a6682133-8c48-4319-91fe-c0897637560a)

**Comment by damienen** [comment]
We should restrict the contract view from people that are not creators of the contract

**Comment by fuzzyduke** [comment]
Verified. Fixed. 
Redirect is seen to homepage.
