### ISSUE TITLE
zstorage additional items set thread

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1126]
https://storage-mu.vercel.app/

1. When a file is updated the previous version also shows. Need to either group or show only the latest version of the file.
![image](https://github.com/Itheum/data-dex/assets/121969933/d0a1d62c-3588-4f67-bad0-bf60f03e882b)

2. If you try to update a playlist which already has 2 songs, and change a title there is no change seen in the manifest file or the playlist does not get edited. If however you add a third song while editing the manifest file then it generates a new file hash which is fine.

Therefore, we need to allow that if the header or existing items are edited with no addition of new song, then the playlist should be updated.
![image](https://github.com/Itheum/data-dex/assets/121969933/77d2d0c6-e8d4-485f-8a12-39474dcbd3d0)

3. You should be able to see your files and their file hash if relogging. Currently there is no way to see the file hash of items already created to zstorage. Further please mentioned the file hash in addition to the ipfs gateway that already exists. Therefore add a parmater for instance.
[ipfs/bafybeiegkvv53gqkllxmy3zhfsex2dsdbyxv3kodovz2pxpyu5ghwjfvme](https://ipfs.io/ipfs/bafybeiegkvv53gqkllxmy3zhfsex2dsdbyxv3kodovz2pxpyu5ghwjfvme)

**Comment by fuzzyduke** [comment]
4. When not logged in, user should not be able to select any options.

**Comment by damienen** [comment]
Duplicate
