### ISSUE TITLE
While updating on zstorage, it is seen that previous files are not being loaded from ipfs.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1132]
While updating on zstorage, it is seen that previous files are not being loaded from ipfs.

Steps:
1. Update a previous data asset on zstorage.
2. Add another file.
3. Upload after saving.

It is seen that the previous files are not loading from ipfs.

![image](https://github.com/Itheum/data-dex/assets/121969933/71e8bfdc-90d9-42dd-9b6b-5c8c4b04d23f)

**Comment by damienen** [comment]
I will try to reproduce as well

**Comment by 911-Benedek-RobertGeorge** [comment]
this happens when the files dont get pinned, error 504 - gateway timeout
wait a little for the files to get pinned
