### ISSUE TITLE
Issue seen while updating an existing file on zstorage.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1133]
Issue seen while updating an existing file on zstorage.

Steps
1. Attempt to update an already created music playlist on zstorage.
2. Update only the cover image.
3. Post clicking on upload the below is seen.
4. However it still generates an IPFS link. https://ipfs.io/ipfs/bafybeidj36gyqi5bmtczqdkjhtdkzrjhv76d4fxxgxfahoyil3xe24wk5u
Uprocessable content
Image used to replace was https://dataassets.valhallala.com/file_storage/tripy.gif
![image](https://github.com/Itheum/data-dex/assets/121969933/742675e3-ef54-4c45-aecf-739f8d688ab1)
![image](https://github.com/Itheum/data-dex/assets/121969933/670bf7cf-411d-47fa-8aa2-a23479d3b73e)
![image](https://github.com/Itheum/data-dex/assets/121969933/6898f7f0-e027-4548-b716-71acaf5c2abe)
5. Upon completion of the above refreshed the page and went to homepage to try and reupdate. However on launching homescreen the below was seen 
![image](https://github.com/Itheum/data-dex/assets/121969933/6943e1ee-b12a-47d2-ab87-3da04bdabcb1)

It is assumed that the playlist file is not retrievable or corrupted and causes the page to behave as such.

**Comment by damienen** [comment]
Duplicate
