### ISSUE TITLE
Add style to table (more like repair it) component

### ISSUE THREAD

**Issue by Enciusan** [Itheum/data-dex#1157]
Details nft's table don't have enough pading and it's not responsive

![Image](https://github.com/Itheum/data-dex/assets/92076681/b10b0042-7149-4269-b8f7-db405b2b7a47)

**Comment by fuzzyduke** [comment]
Styling to table looks fine.
Age column does not seem to be functioning right. The to column does not take effect.

**Comment by fuzzyduke** [comment]
Ignore Age, looks fine.
