### ISSUE TITLE
Add Status page link in Data DEX, Explorer footer

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1168]
In the footer of the Data DEX and Explorer, add a "service status" link that goes here in a "new tab" : https://stats.uptimerobot.com/D8JBwIo983

Should be in this style / row of links:

![Image](https://github.com/Itheum/data-dex/assets/743169/b05674ca-11bf-4ca6-96e4-05adc49fbd12)

i.e. Terms of use, privacy policy, service status

**Comment by Enciusan** [comment]
Here i've added status page redirect buttons for both explorer and data dex.

**Comment by damienen** [comment]
Tested. Solved. Good job
