### ISSUE TITLE
ITHEUM tokens balance goes into too many decimals

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#118]
In some instances, the ITHEUM tokens and claims token balances has a decimals issue in the UI. This PR has the fix: https://github.com/Itheum/data-dex/pull/114

**Comment by damienen** [comment]
@newbreedofgeek can thiis issue be closed? Seems done to me.

**Comment by newbreedofgeek** [comment]
Yes, it looks good. Closing
