### ISSUE TITLE
listing nfts skews grouping. it shows each nft as a separate group

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1182]
listing enterprise tokens from one collections skews grouping. it shows each nft as a separate group

![Image](https://github.com/Itheum/data-dex/assets/121969933/e32f6ae6-3f43-4921-a528-848b8b92a081)

**Comment by bucurdavid** [comment]
Needs release with: https://github.com/Itheum/sdk-mx-data-nft/pull/140 + https://github.com/Itheum/core-mx-web2-backend-service/pull/62

**Comment by fuzzyduke** [comment]
Grouping is seen

![Image](https://github.com/Itheum/data-dex/assets/121969933/c4f67b37-d86b-491a-ac15-ad65d0c19b85)

Upon clicking on the card we see the above. 

Upon clicking on an item we can purchase.
