### ISSUE TITLE
Text cut off in Group View Tiles

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1187]
<img width="550" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/03e9c1c8-5fc8-4b74-bc1e-83368a90b605">

The description is being "cut off". Ideal if the description is too long:
- "Fade Out" effect on the description div
- Have X hidden scroll bar so user can scroll down and read all text

**Comment by Enciusan** [comment]
This one should be ok, the description is showing on 4 lines.

**Comment by damienen** [comment]
Text is not cut off anymore. Not all text is shown though, just the first 4 lines.

**Comment by newbreedofgeek** [comment]
@Enciusan have these been done as per intro..


```
"Fade Out" effect on the description div
Have X hidden scroll bar so user can scroll down and read all text
```

**Comment by damienen** [comment]
Also, seems like the issue is not solved. Went onto your branch, on mainnet (locally), and saw this:
![Image](https://github.com/Itheum/data-dex/assets/44813558/05067343-62a2-4c88-8055-96cad114a6d2)
