### ISSUE TITLE
Favorites not appearing in Wallet > Favorites

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1188]
I made a favorite:
<img width="942" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/079778e8-d1b9-4d32-8807-a9389ddd0348">

And then went to Wallet > Favorites but it's not there. Waited 5 mins, reloaded page etc and did not work

<img width="809" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/93f3a9c7-47d9-4c6e-bb19-a1a9b2c46521">

It should also show "how many" in the tab. i.e. Favorite(s) 1

**Comment by Enciusan** [comment]
The favorite page from wallet should work in any case even you have or not have a data nft.

**Comment by damienen** [comment]
Checked with an empty wallet. Works. Nice jop.
