### ISSUE TITLE
Clicking on Data NFT image on group view should open the Collection View Model

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1189]
When I click on this image:
<img width="423" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/2ac43f2b-2fa7-40f5-932b-5ad610aa1169">

It should open the same **Data NFT Collection Details model** you get when u click on this button.

<img width="228" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/b056956d-5af9-4dac-92e6-4ef5bc61ebb0">

**Comment by damienen** [comment]
Made it so when one clicks the image the details modal opens up. Changed the positioning of the image just a little bit to avoid a bug that allows the clicking under the image and still opening up the details modal

**Comment by fuzzyduke** [comment]
Works as described, clicking on the image opens the same details modal. Closing
