### ISSUE TITLE
Text change required in Itheum Enterprise

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1192]
Text change required in Itheum Enterprise

![image](https://github.com/Itheum/data-dex/assets/121969933/5e9613fa-c864-4836-abee-7115e856ada5)

"Protocol Tax: 20%" -> "Protocol Tax: 20% of Royalties"

**Comment by Enciusan** [comment]
On the enterprise page i've just added the text on % field.

**Comment by damienen** [comment]
Tested. Works. Closing.
