### ISSUE TITLE
In Public Marketplace - My Listed, details page does not work right

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1215]
@fuzzyduke please watch this and confirm issue and raise bug with details tnx
https://www.loom.com/share/89370864d23d48709c416fa644ee9fe2

**Comment by fuzzyduke** [comment]
Confirmed.

Steps
1. Log into the datadex.
2. Browse to marketplace
3. Keep "Show all offers" unchecked
4. Go to My listed Data NFTs.
5. Launch the first NFT. It is seen that the data NFT is not accurate.
6. Now go back to the marketplace and check "show all offers"
7. Next go to "My Listed Data NFTs" and launch the first NFT; now the detail page is accurate.

It seems that when "Show all offers" is unchecked and the first data NFT of the marketplace is different from the first data NFT under "My Listed Data NFTs" then the first data NFT of the marketplace will be shown under "My Listed Data NFTs" when launching the first data NFT under the latter.

It is noticed that if "Show all offers" is unchecked then the first

**Comment by damienen** [comment]
Solved. Closing
