### ISSUE TITLE
Hotfix: TimeCapsule Launch UX Improvements

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1216]
To improve the UX for new users coming in for the TimeCapsule launch, the following UX improvements have been added:

1. ONLY on details page: If Creator and Owner is the same, we show a "Mint Data NFT" button that does exactly the same as previewed button. But gives the impressions that your a are "minting" a new collection direct from the Creator. This simulates a candy-machine type experience that MvX users are used to. BUT keep in mind that this is just some UI update, the behaviour is exactly the same as before. "Transaction Toasts" will also say "Minting..." in the case where user sees "Mint Data NFT" button

2. Text Change: Title of app changes to "Own and trade your data as Data NFTs"

3. Content Change: Whitelist page now shows all the Data NFT collections.

4. Text Change: Some other heading changes to pages etc..

5. Text Change: "You are the Creator" -> "You Created this"

6. Text Change: "You are Owner" -> "You Own this"

7. Text Change: "Procure Data NFT" -> "Buy Data NFT"

8. Text Change: "Amount" -> "Quantity" (this is everywhere)

**Comment by damienen** [comment]
Solved. Closing.
