### ISSUE TITLE
Bonding UI & SC full integration complete - public dashboard

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1222]

**Comment by fuzzyduke** [comment]
Freshly created Data NFT with bond shows expired liveliness score even though the duration defined is 1 hour

![image](https://github.com/Itheum/data-dex/assets/121969933/34ddd5ae-9b43-4c20-a508-1883431d5b37)

**Comment by fuzzyduke** [comment]
Renew Bond throws error 

https://devnet-explorer.multiversx.com/transactions/1133e284d1ed15a3b854df0cfc0998c40b899782d0ff7d65fd1e5da46893c3d0

![Image](https://github.com/Itheum/data-dex/assets/121969933/4de6d623-249f-4c67-99b9-3a9a5d1788de)

**Comment by fuzzyduke** [comment]
If a user is penalized 50% and then attempts to withdraw he sees an error which is correct.

However the user might need to see that they will not be able to withdraw if the early withdrawal penalty exceeds the withdrawal amount(ie the user has already been penalized more percentage than what the user can withdraw)

![Image](https://github.com/Itheum/data-dex/assets/121969933/4570c66a-1f4d-49d7-a8c9-3def167f713f)

**Comment by fuzzyduke** [comment]
verified
