### ISSUE TITLE
Bonding admin dashboard

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1223]
Will attach wireframe privately

**Comment by fuzzyduke** [comment]
Few observations and clarifications

1. Failure was encountered below; Data NFT was first penalized 10% then slashed. Relevant failure message required.
https://devnet-explorer.multiversx.com/transactions/986a7a6c448025061d3c823b9324699b14812fa26ac84b0b4f650875b07f6ec7

2. If a claim date is set for owners, this is only effective in the admin as a parameter. There is no current followup claim action implemented.

3. If a creator has been penalized, the values are stored in the dashboard, is not consumable by the creator.

4. Claims for creators are yet to be implemented. To test once penalization has been enforced.

**Comment by damienen** [comment]
- remove tx on 0 on add

**Comment by fuzzyduke** [comment]
1. When setting "Maximum slash in percentage" value, there is a validation on the Minimum slashable bond.
![image](https://github.com/Itheum/data-dex/assets/121969933/afeb247a-ce71-4e2d-a593-b81cabfa3f00)
2. Total Bonded shows as 30k ITHEUM, Is this accurate?
![image](https://github.com/Itheum/data-dex/assets/121969933/eed3a3bd-20b4-44b5-89ca-e8bb2c154f5e)
3. Renewed a bond for a Data NFT in the creator bonding tab. However the Data NFT does not show in the admin dashboard, 
![image](https://github.com/Itheum/data-dex/assets/121969933/621a5d51-a83c-4b1f-a0a2-a8e7eb926144)
4. The bar does not reduce as the score reduces
![image](https://github.com/Itheum/data-dex/assets/121969933/e2165dbb-05d9-468c-ab23-2b971b53bd8f)
5. After a user withdraw bond for a Data NFT, that NFT is taken out of their bonding tab. 
In the Admin view the Data NFT is removed as well.

**Comment by damienen** [comment]
I think after @bucurdavid's upgrade today it won't disappear from the map anymore

**Comment by bucurdavid** [comment]
Not really, it's removed from the main mapper, which is used to get all active bonds

**Comment by fuzzyduke** [comment]
To keep everyone on the same page, a few consolidated feedback below.

1. If the Bond has been withdrawn by the creator, the data NFT is removed from the bonding tab of the creator and the admin.
2. If any max slash penalty is more than the available bond then the admin is required to manually penalize.
	I.e., if the slash is 90% but the previous penalty applied was 15% then the max slash will fail.
3. "No penalty on early withdrawal" sets the bond to expired; the creator can invoke a full refund.
4. Compensation self-claim can be tested when claim for owners is implemented.
5. Math on mint, penalty, slash, early withdrawal(2 scenarios) tested.
6. Bonding duration vs bond amount tested; for a single duration.

**Comment by fuzzyduke** [comment]
Attempted to add 10 ITHEUM slashable bond to 3600 seconds entry.

Entries were
3600 seconds with 12 ITHEUM
2 seconds with 14 ITHEUM
1000 seconds with 250 ITHEUM


https://devnet-explorer.multiversx.com/transactions/4964020182bddcae40224d0a2ffd631784a8a34d2a4c9439df9176ba40c3afdc

**Comment by fuzzyduke** [comment]
Cosmetic:

When mentioning to the user that they can withdraw with no penalty. there can be cases they were penalized for other behavior.

Therefore suggest mentioning there will be no Early withdrawal Penalty instead of just Penalty.

"You can withdraw your full bond with no penalty"

![Image](https://github.com/Itheum/data-dex/assets/121969933/b7b7be14-0e7d-4a41-97bb-82013bdc456f)

**Comment by fuzzyduke** [comment]
Upon deleting all period bonding periods and amounts blank page is seen.

Attempted to remove all periods to update the already existing entry for 3600 seconds with 12 ITHEUM and update it to 10 ITHEUM

https://deploy-preview-1252--frosty-hermann-85ca4f.netlify.app/bonding

**Comment by damienen** [comment]
Should be solved @fuzzyduke

**Comment by fuzzyduke** [comment]
Bonding dashboard is not populating data NFTs. Data NFT minted: https://devnet-explorer.multiversx.com/transactions/6ac9a04bc55daf0c21f22e7690be63f5434916225f7f6d8196ac52966954b1f1

![Image](https://github.com/Itheum/data-dex/assets/121969933/72f1f211-510c-4dd0-a1a5-0eb98c1327fb)

**Comment by fuzzyduke** [comment]
1. currently withdrawal is set to 50% in admin dashboard
2. penalty of 30% was applied in admin dashboard.
3. user attempts to withdraw but sees the below. the user still has 20% withdrawable.

![Image](https://github.com/Itheum/data-dex/assets/121969933/39ddec0a-c186-4d05-acea-ea0d6363ea9e)

![Image](https://github.com/Itheum/data-dex/assets/121969933/28f5666c-011c-4d3a-b2eb-245c70b3adc5)

**Comment by fuzzyduke** [comment]
Item 3

1. mint Data NFT
2. apply 9% penalty
![Image](https://github.com/Itheum/data-dex/assets/121969933/998fe7e3-e968-448f-9e57-cad461c40f13)
3. click withdraw (current early withdraw percent is set to 50%)
![Image](https://github.com/Itheum/data-dex/assets/121969933/64eb0a88-50bc-4e54-8ff4-29a1301ce3ce)
4. Upon withdrawing it is seen that 5 ITHEUM is sent back. Only the early withdrawal fees was deducted, not the penalty of .9
https://devnet-explorer.multiversx.com/transactions/b3481e9fde9851df6c02e49377f202ad6f28d400abd2d2a3db4f4cc5dd0e6e35#71ab950d69625d25695d54267d4017ba6d85c215b3aa601f6d1ef77d6c382b64

**Comment by fuzzyduke** [comment]
Item 4

Was able to apply 5% for penalty on a Data NFT despite the minimum penalty being set to 6%

After applying 5% penalty to the data NFT, 6% was deducted.

![Image](https://github.com/Itheum/data-dex/assets/121969933/340ea9b7-b9b5-4cd3-bac8-380062da8648)

**Comment by damienen** [comment]
> Item 3
> 
> 1. mint Data NFT
> 2. apply 9% penalty
>    ![Image](https://private-user-images.githubusercontent.com/121969933/314488563-998fe7e3-e968-448f-9e57-cad461c40f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDg3MTksIm5iZiI6MTcxMDk0ODQxOSwicGF0aCI6Ii8xMjE5Njk5MzMvMzE0NDg4NTYzLTk5OGZlN2UzLWU5NjgtNDQ4Zi05ZTU3LWNhZDQ2MWM0MGYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNTI2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGI0NDk4OGE4MjNlZTA4Zjk5NzA3ZjAxMGZlMzM1OGI0MzFkMzg3NTQyNGY5MGYwMmMxMWMwY2U2OWZkNzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TZAzmzP1ViDjz_FJJA0oopgC4vFmQ7mLE0ZQS1lkZK0)
> 3. click withdraw (current early withdraw percent is set to 50%)
>    ![Image](https://private-user-images.githubusercontent.com/121969933/314488886-64eb0a88-50bc-4e54-8ff4-29a1301ce3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDg3MTksIm5iZiI6MTcxMDk0ODQxOSwicGF0aCI6Ii8xMjE5Njk5MzMvMzE0NDg4ODg2LTY0ZWIwYTg4LTUwYmMtNGU1NC04ZmY0LTI5YTEzMDFjZTNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNTI2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDhiOGIxYTE0OTYzNTQ1NjA1NDE3MzE2YzJhMTM5N2U3YzcwZTJkMjdmMDdkNDQyNDFlYWJjOWY2MTc1OWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.376vrazDwEhBg0GPeyEMDt_jsMwN2ydF9bwh47pb-Vo)
> 4. Upon withdrawing it is seen that 5 ITHEUM is sent back. Only the early withdrawal fees was deducted, not the penalty of .9
>    https://devnet-explorer.multiversx.com/transactions/b3481e9fde9851df6c02e49377f202ad6f28d400abd2d2a3db4f4cc5dd0e6e35#71ab950d69625d25695d54267d4017ba6d85c215b3aa601f6d1ef77d6c382b64


Indeed, I can confirm this is the logic of the SC and that this bug is coming from the fact that withdraw is using bond_amount instead of remaining_amount for the withdraw operation:
https://github.com/Itheum/core-mx-life-bonding-sc/blob/bb99e6ed0e348177bde61c184d408338258c053c/src/lib.rs#L137
