### ISSUE TITLE
Error seen in Minting a dataset

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1226]
Upon minting on test.datadex the below is seen

Seems to be stuck on "Minting your new Data NFT on blockchain" step

![image](https://github.com/Itheum/data-dex/assets/121969933/35c14730-93ff-4a6c-b9f6-677ed464d907)

**Comment by fuzzyduke** [comment]
different error seen

![Image](https://github.com/Itheum/data-dex/assets/121969933/acce46bd-4d21-4b43-bf46-22ac203f0c14)

**Comment by damienen** [comment]
Also, supply is hardcoded to 10. That is not ready to ship by any chance :)

**Comment by damienen** [comment]
Solved when updating 2.7.0-beta.3. The only thing left is hardcoding of supply
