### ISSUE TITLE
Data NFT detail button sits in front of logout menu in specific scenario.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1230]
While dropping down the menu, if there is a data NFT behind the logout button then the details action sits infront of the logout button.

![image](https://github.com/Itheum/data-dex/assets/121969933/a65b5e15-0d9f-417a-8523-8d47c096405c)

**Comment by damienen** [comment]
Solved. @fuzzyduke you can close if you can't reproduce if closing

**Comment by fuzzyduke** [comment]
fixed
