### ISSUE TITLE
Validation failure when user does not have sufficient Itheum while minting.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1235]
When user does not have  enough ITHEUM for anti-spam OR bonding, we have to show above errors. To keep it simple, in the UI.. just add the anti-spam + bond and then check if it's less than current balance and then show the error and disable the mint button 

![image](https://github.com/Itheum/data-dex/assets/121969933/e10ec8c1-a011-4af5-9172-689f72feac67)

**Comment by damienen** [comment]
Solved. Closing.
