### ISSUE TITLE
After minting click on close and return. the user is sent back to the form populated with previous entries.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1240]
After minting click on close and return. the user is sent back to the form populated with previous entries.
This was not the previous behavior.

Upon clicking close and return the user should go to the mint page where the user can click on "Advertise Data" and run a second fresh mint.

![image](https://github.com/Itheum/data-dex/assets/121969933/5f1bdd50-216f-4735-89b9-e88224f62d79)

![image](https://github.com/Itheum/data-dex/assets/121969933/8426ed4b-8815-459f-828f-fef3503f9f36)

**Comment by damienen** [comment]
Solved. Closing.
