### ISSUE TITLE
listing data NFT does not work when using xportal.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1242]
listing data NFT does not work when using xportal.

Just stays in a connection state.

![image](https://github.com/Itheum/data-dex/assets/121969933/2ec05e4f-9d81-497c-97af-036b364ffd98)

**Comment by fuzzyduke** [comment]
similar for buying a data NFT

**Comment by damienen** [comment]
Closing for now. If reseen, can be opened
