### ISSUE TITLE
There is a scenario where the mint does not go through.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1244]
There is a scenario where the mint does not go through. The mint is stalled on the 4th step with the uncaught exception as shown.

At the moment it seems it has something to do either with the mint url or the entry for title/tokenname.
Unable to reproduce.

![image](https://github.com/Itheum/data-dex/assets/121969933/e5a2901c-c1d1-4777-9674-acd4a3cbeb9f)

**Comment by damienen** [comment]
@fuzzyduke will need some more details so I can reproduce. Can you give me the params you used to mint when you saw the error?

**Comment by damienen** [comment]
Closing until it can be reproduced
