### ISSUE TITLE
Data NFT - Maiar Chrome Extension do not throw an error when a tx with bigger amount of Itheum than balance is sent

### ISSUE THREAD

**Issue by icegriffinguru** [Itheum/data-dex#125]
![image](https://user-images.githubusercontent.com/97042732/202325116-47ecc8a0-0b19-419e-b696-45ea4e8428b5.png)
I only had 20 ITHEUM but maiar chrome extension did not throw an error when i tried to send 1020 ITHEUM on devnet.
The tx was sent by `sendAcceptOfferEsdtTransaction` function in the `src/Elrond/dataNftMarket.ts/`.

**Comment by newbreedofgeek** [comment]
Might not be a Data DEX bug but an Elrond wallet bug... but keeping it open.

**Comment by newbreedofgeek** [comment]
We should fix this.

In the confirmation model, before purchase. We check user's ITM balance and if it's not enought.

- Show message : "You do not have enough balance for this transaction"
- The "proceed" button is disabled.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/743169/215676954-6a6df068-ba31-4a3a-996a-3dcc238a1ea3.png">

**Comment by icegriffinguru** [comment]
![image](https://user-images.githubusercontent.com/97042732/215693992-acc2e0fb-3d89-4a01-be69-c9f2e856ddb1.png)

@newbreedofgeek 
we better disable Procure button if there is not enough balance. what do you think?

**Comment by newbreedofgeek** [comment]
@icegriffinguru 

Let's do it in the confirm popup:

Let's do this:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/743169/215942711-7b0edcba-b4da-438c-9c6e-17ed4c7694ab.png">

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
fixed
