### ISSUE TITLE
Compensation public UI

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1257]

**Comment by fuzzyduke** [comment]
blacklisted address was able to deposit and claim.



![Image](https://github.com/Itheum/data-dex/assets/121969933/f6a567c6-18a7-4430-b30f-a8c53ccdc8e3)


Kindly confirm the flow for blacklisted addresses.

**Comment by damienen** [comment]
Did the blacklisted address actually receive the tokens as well(

**Comment by fuzzyduke** [comment]
blackliast address erd1xdq4d7uewptx9j9k23aufraklda9leumqc7eu3uezt2kf4fqxz2sex2rxl
other 2 addresses that submitted 
erd1xnlznshy5y39mawwp6msh6h2t6a4dkqa339dejwr7aqszj3nxfms30ejtw
erd146cv4kcyl28rpk2xa723rupck9fsegda8gxj70xvn0x6p6qvd68q364n9c

**Comment by fuzzyduke** [comment]
When the xl address tried to withdraw it got only the Data NFT

The other 2 NFTS got the right distribution of ITHEUM compensation and Data NFTs.
