### ISSUE TITLE
Compensation admin UI

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1258]

**Comment by fuzzyduke** [comment]
awaiting implementation

**Comment by fuzzyduke** [comment]
Unable to find new data NFT in Bonding admin UI to apply penalty.
https://devnet-explorer.multiversx.com/nfts/DATANFTFT-e0b917-0123/transactions

![Image](https://github.com/Itheum/data-dex/assets/121969933/25ddd77f-e4fb-4457-bd95-a228a6604485)

**Comment by fuzzyduke** [comment]
Workflow post deadline date set does not reflect adequately. Users should be able to see the item in the compensation tab.

**Comment by fuzzyduke** [comment]
Few observations

1. SC level compensation split looks fine for legible and blacklisted users.
2.  Post Cooldown period admin should not be allowed to blacklist unless theres a new deadline or unmet cooldown period. Post cooldown blacklist should be disabled to avoid funds getting stuck in contract.
3.  Claim amount to be amended for users. Currently the front end takes blacklist accounts into consideration, however the backend correctly omits the blacklised.
4. If users have not claimed before the second penalty/claim cycle then they will be part of the next cycle and may get less as per original allocation as the redistribution is to all users in the second cycle. This is a more complex scenario as we do not have a deadline for claiming before the new claim cycle begins.

**Comment by fuzzyduke** [comment]
noticing some odd behaviour 

1. Purchased 2 data NFT each from 2 accounts
2. applied penalty and set deposit deadline
3. deposited from both accounts however the below was seen

![Image](https://github.com/Itheum/data-dex/assets/121969933/809c5c58-aff3-41e5-9a1d-7ecc86aea089)
was still able to deposit after depositing once. however on retry this error was encountered https://devnet-explorer.multiversx.com/transactions/381706b925850b533422f5dda5603bc25cddb50e23cf77ea17cce402a2f82fbd

**Comment by fuzzyduke** [comment]
Scenario

1. penalty of 10% or 100 ITHEUMhas been applied
2. 10 users deposit 1 each
3. 9 users claim
4. New penalty of 50% is applied, 500 ITHEUM. 
5. Until the deadline is set the 10th user who did not claim earlier can claim the whole amount from the second cycle. Once deadline is set the claim button is disabled. Allowing other users to deposit and claim and equal share after the deadline has elapsed.
