### ISSUE TITLE
Bitz Game Launch : In "View Data", show "Play Get BiTz Game" button

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1276]
- The View Data for the new Data NFT will throw an error like this
<img width="524" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/d7b85c78-a72f-4777-bc07-56b668d9caa2">

- This is because the BitZ Game returns "403" error code (as it's protected by Native Auth and has game play logic). 

To show a better UX, let's do this:
1. In the above screen, just for the BitZ Game Data NFT nonce (7), show a nice "Play Get BiTz Game" button that takes them to http://explorer.itheum.io/getbitz [pass native auth token like we do for other Explorer links]

**Comment by damienen** [comment]
Solved. Closing.
