### ISSUE TITLE
Bitz Game Launch : XP Score In Header (like in Explorer)

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1278]
Do this in Data DEX:

<img width="885" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/9c51339b-ab5c-470d-88f9-4f6df14be393">

On the CTA action link, take them to http://explorer.itheum.io/getbitz in a new window [pass native auth token like we do for other Explorer links]

**Comment by damienen** [comment]
Solved. Closing
