### ISSUE TITLE
Restyling after dapp-core 2.x upgrade

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#128]
We should identify exactly the parts of the UI that need fixing after the upgrade

**Comment by icegriffinguru** [comment]
- [ ] login page modal layout & color is bad
![image](https://user-images.githubusercontent.com/97042732/202834663-a6f38ea6-6193-4ae7-8d0a-430729d461f8.png)

- [ ] user wallet button css broken
![image](https://user-images.githubusercontent.com/97042732/202834693-6f05562e-5607-4ef7-9bd0-62bd5f260e7d.png)

- [ ] wallet connection waiting modal css broken
![image](https://user-images.githubusercontent.com/97042732/202834726-c6fff162-6186-480b-89af-f81fc6df88db.png)

- [ ] cannot buy Data NFT - Maiar Chrome Extension throws "Cannot get Token" error
![image](https://user-images.githubusercontent.com/97042732/202834793-7d22fb1b-a7ec-4fec-88c2-bb82df96633e.png)

- [ ] tx status modal css broken
![image](https://user-images.githubusercontent.com/97042732/202834801-20d7adcb-0997-4ce7-a5b8-642ca987148f.png)

**Comment by newbreedofgeek** [comment]
Let's also fix the decimal issue for token balances, here are the rules:

Rule 1:
Actual: 1000099.7999999999
UI: 1000099.79

Rule 2:
Actual: 1000099.700000000
UI: 1000099.7

Rule 3:
Actual: 1000099.000000000
UI: 1000099

Let's make these rules apply to all places we show token balances

- [ ] Header ITHEUM Balance
- [ ] "My Claims" Balances on home screen
- [ ] "View Claims History" popup

**Comment by newbreedofgeek** [comment]
Retest 23/11/22:

- [ ] Why does this take over the whole UI? It used to just be a model in the centre:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/743169/203490658-d09416a7-1446-41fb-b806-0b81cf9d7ec1.png">

- [ ] Make the icon smaller and the close x cannot be seen
<img width="380" alt="image" src="https://user-images.githubusercontent.com/743169/203490749-b2ea19a8-309a-403e-831c-b23b5bea5d0f.png">

**Comment by damienen** [comment]
@newbreedofgeek can thiis issue be closed? Seems done to me.

**Comment by newbreedofgeek** [comment]
Nope.. as per the updates on Discord by community tester. There seems to issues with Ledger. 


[ ] - Ledger popup with addresses not styled and cant read. Need to verify it's fixed on both dark and lite mode
![image](https://user-images.githubusercontent.com/743169/204931374-25bada2a-0f3a-45fb-ad4a-e432f59df0e3.png)

[ ] - Ledger txs are failing, maybe due to devnet issues but we need to verify.
![image](https://user-images.githubusercontent.com/743169/204931619-31fc0567-f3ba-4a94-ba3a-407d25354724.png)
