### ISSUE TITLE
Allow for SFT and NFT Minter to support optional bonusNFTMediaImgUrl prop for minting

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1300]
If the user sends this, we place this in a top level bonus_media_img attribute in the NFT metadata. This is ONLY optional, if not provided we should NOT put this in the NFT metadata.

Required SDK update:
https://github.com/Itheum/sdk-mx-data-nft/issues/125

**Comment by damienen** [comment]
Solved. Closing.
