### ISSUE TITLE
NFT with Secondary Image "rotates" on Marketplace

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#1309]

**Comment by damienen** [comment]
Cool code samples I wanna save as they are related to this:
https://codepen.io/lorex_ia/pen/poyPYvR
https://github.com/simeydotme/pokemon-cards-css

**Comment by 911-Benedek-RobertGeorge** [comment]
Check this on explorer also. When there are nfts with extraAssets( bober)  you should be able to switch the image

**Comment by fuzzyduke** [comment]
First image does not auto rotate, second image auto rotates sharply. i.e., if moving from img1 to img2 the animation is smoothe, however img2 back to img1 has no animation and is a plain next transition.

https://test.datadex.itheum.io/datanfts/marketplace/market/10
![image](https://github.com/Itheum/data-dex/assets/121969933/b6287553-914b-441f-920d-dc877383978a)

**Comment by fuzzyduke** [comment]
Verified on pr 1327

1. Random image transition seen.
2. Upon invoking slider manually, the automatic slider rotation stops.
