### ISSUE TITLE
Data NFT minting form donation

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1329]
Blocked by: https://github.com/Itheum/itheumcore-elrond-data-nft-minter/issues/81

**Comment by Enciusan** [comment]
Here i've to add the dynamic value of min / max donation % admitted

**Comment by fuzzyduke** [comment]
1. Below is seen when trying to mint setting Donate percentage

https://devnet-explorer.multiversx.com/transactions/d3f3e613e813f3f9cf77bc993da3a3a80545b137c25976902c8242e6d4286544

![image](https://github.com/Itheum/data-dex/assets/121969933/666e2ba0-ae05-47d2-98d1-4aa7b8c799b5)

![image](https://github.com/Itheum/data-dex/assets/121969933/41e0c51c-76ab-4ab0-be77-508eddee8f67)

**Comment by damienen** [comment]
maxDonationPerecentage is currently set to 20% in the SC. This should be the limitation in practice as well

**Comment by damienen** [comment]
Can confirm that donation treasury address is set on devnet as:
erd1f02qxj7zcds358dlytw25ggtcwvuwd054c7mgk8hnnqwqq0hnp4sad5209

Closing
