### ISSUE TITLE
[UI Upgrade Build] - After Login - Trade My Data Screens

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#134]

**Comment by newbreedofgeek** [comment]
Some new UI/UX tasks:

- [ ] If there are any issues reading "defaults" from the smart contract backend (Number of copies, Royalties, Anti-Spam Tax) - then the UI should show an error box like below with the appropriate error code

- [ ] Once the component mounts, we need to call the "Data Marshal" and the "Generative Image API" and make sure they return a 200 OK. If not, then the UI should show an error box like below with the appropriate error code.



![Image](https://user-images.githubusercontent.com/743169/205807813-2be85ea6-39c3-40f0-9e98-d33eddae99f1.png)

CC @icegriffinguru

**Comment by newbreedofgeek** [comment]
- [ ] If the User does not have enough ITHEUM to cover the anti-spam test, there should be the following error message and the "Mint and Trade as NFT" button should be disabled



![Image](https://user-images.githubusercontent.com/743169/205808535-0ef1a7b1-3a6f-4286-8c23-6b4c8223a526.png)

**Comment by newbreedofgeek** [comment]
Dev testing commits upto https://github.com/Itheum/data-dex/commit/848dc5d2e9453e7dc0e103f22433fa80e4da8df6

Wallet: DeFI Plugin Devnet
Browser: Chrome / Mac

- [ ] When the form loads, and even before user enters anything they see the red validation errors. These should not appear until user focuses on a specific textbox. e.g. in token name box, once the user focused the textbox, then the red error should appear

<img width="300" alt="image" src="https://user-images.githubusercontent.com/743169/206436376-8afb06fc-d21f-4a56-9a6b-93b4f5747965.png">

- [ ] When i reload the main page, "/selldata" the 200OK URL validation seems to be happening - but this should only happen once I clicks on the "advertise data" button and the form slides into view. But ideally, the only URL we 200 test is the "Data Marshal" and the "generative image API" endpoints (and also if we can read the smart contract and get the "defaults" for fields like supply and tax). The other URLs can be removed.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/743169/206437399-898b6780-4f3b-4b4b-9832-b9b9fd72b6fb.png">

- [ ] Remove Data Stream URL and Data Preview URL defaults.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/743169/206437773-53cd433e-f381-421f-aadd-c87b9e55c4e5.png">

**Comment by newbreedofgeek** [comment]
Other errors:

- [ ] For some reason, clicking on "Maiar App" option in devnet login screen is going to "Web Wallet" instead of opening the Maiar App popup:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/743169/206439698-360d1ac8-b6e4-45a6-8adc-d9da64be957e.png">


CC

**Comment by newbreedofgeek** [comment]
- [ ] How are we going to support "web wallet for minting the Data NFT"?? As it takes the user away from the browser and the UI will close. Any suggestions?

**Comment by icegriffinguru** [comment]
> * [ ]  How are we going to support "web wallet for minting the Data NFT"?? As it takes the user away from the browser and the UI will close. Any suggestions?

I think using url param in callback url is the solution. The same solution is used in some Elrond dApps.

**Comment by newbreedofgeek** [comment]
[ ] - In the form, do not allow a user to enter the same url for data preview url and data stream url

**Comment by newbreedofgeek** [comment]
Closing as most above are fixed. New bugs can be new issues.
