### ISSUE TITLE
UI/UX improvements to donation on mint

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1379]
If the "Number of copies" results in this scenario. i.e. no donations can happen if the user is sliding the bar and it reaches a % that wont work. Then under the "Donation Percentage" box (under Min: 0% Max 20%), should a message to the user: [in same red as other alert text] "As the number of copies is low, no Data NFTs will be sent for donations"

Also, there is no message to the user on what this feature is:
description:
"When you mint, you can optionally choose to donate a percentage of the total supply to a community treasury, which will then be used for community airdrops to engaged community members who actively use the Itheum BiTz XP system. This is a great way to get a "engaged fanbase" for your new collection and drive awareness. Learn more here [A external link in the same style as other external links that goes here : https://docs.itheum.io/product-docs/product/data-dex/minting-a-data-nft/creator-donations-for-community-airdrops]

**Comment by fuzzyduke** [comment]
Set number of copies to 9 and directly saw this screen

![image](https://github.com/Itheum/data-dex/assets/121969933/67c35332-3977-4094-8a5a-a0c89baa7d3a)

As the Percentage was increased to 15% the message disappeared, as then donation quantity becomes 1 which is fine. However the user does not know they have to toggle the bar to be able to donate.

Therefore probably just need a different message like "As the supply is X you need to set a minimum of Y% to donate." 
If 20% of the amount still does not amount to a quantity of 1 then we can have the message "As the number of copies is low, no Data NFTs will be sent for donations"

Also note that the number of copies is on the second step and donation is on 3rd step. Might be useful to move them on the same page so the user can edit accordingly.

**Comment by damienen** [comment]
Changes needed:
1. Stepper can be teal
2. Warning message can be yellow/orange
3. Info message for donated quantity can be teal
4. Default percentage for donation should be half ot the max value

Changes to blue informational box:
1. $ before all ITHEUM
2. Space before all (
3. Information -> Minting Fees

**Comment by fuzzyduke** [comment]
The bar is at 10% but shows at 0, only i the bar is moved slightly and back again it picks the correct percentage.


![Image](https://github.com/Itheum/data-dex/assets/121969933/5c91e985-f0f5-41f6-9cb1-35275157375c)

**Comment by Enciusan** [comment]
@fuzzyduke Just pushes a quick fix

**Comment by fuzzyduke** [comment]
Changing the quantity reflects conditional check seems to be performed after 10 seconds +

![image](https://github.com/Itheum/data-dex/assets/121969933/b39ad8f2-faf3-4070-a138-438bb0a37a4b)

Also, user is able to go from step 1 to step 2 without  filling required fields. This results in mint button being disabled and the user not being able to identify why without manually going to each page.

**Comment by Enciusan** [comment]
Just pushed a new version @fuzzyduke . Good catches :)

**Comment by fuzzyduke** [comment]
Confirmed fixed.
