### ISSUE TITLE
Pre-requisite mint alert

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1380]
Pre-requisite alert:
Can we give the users a pre-requisite alert - i.e XX Itheum tokens needed ( preferably in USD value in total to mint a data set on Itheum )
These tokens will be used for:
xx on Bonding.
25 ITH as Anti-Spam.
~0.02 EGLD to cover gas for the transaction
This might help the users to have sufficient ELGD+ITH to complete the minting process.

Should be shown above the Data Asset Detail in the form

**Comment by fuzzyduke** [comment]
Verified. Fixed.
Also seems bonding amount is coming from storage which is correct.
