### ISSUE TITLE
Minting form UI/UX improvement

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1381]
- [x] Add stepper
- [x] Change from drawer to modal

**Comment by fuzzyduke** [comment]
Not intuitive for the user that they have to click on number 2 to go to the next step. Maybe have a Next button.

Else the minting went through smoothly.

![image](https://github.com/Itheum/data-dex/assets/121969933/a580e71b-c581-4202-8fc0-392fcc6dc79c)

**Comment by fuzzyduke** [comment]
Verified on pr 1397
