### ISSUE TITLE
Add volume for individual NFTs

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1383]

**Comment by bucurdavid** [comment]
Release with: https://github.com/Itheum/core-mx-web2-backend-service/pull/62

**Comment by damienen** [comment]
AC:
1. Volume is shown in the details page of each NFT
2. Backend has an endpoint that sends TOP 50 NFTs by volume

**Comment by fuzzyduke** [comment]
Volume seen on dashboard and details page. Volume also correctly updates.

**Comment by damienen** [comment]
Solved. Closing
