### ISSUE TITLE
elrond devnet : using a ledger for 1st time, when getting token balance the API sends a "internal server error"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#142]
Usually, we get a 404 and show "no tokens", but with a ledger we are getting a "internal server error". We need to investigate if it's a bug in our data dex or in a elrond library/api.

See below:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/743169/205467180-0a376dee-905a-48f0-8955-8fc8ea593e9b.png">

**Comment by newbreedofgeek** [comment]
Some new observations:
- The new ledger did not have any devnet xEGLD in it when I saw the error.
- After I got some devnet xEGLD and then logged back into the ddex, then the the "internal server error" went away ad we got the normal "404" (which means there is no ITHEUM tokens)

**Comment by damienen** [comment]
Duplicate of #137

**Comment by newbreedofgeek** [comment]
Closing as it's a duplicate
