### ISSUE TITLE
DataNFT Wallet SC Result decoding error

### ISSUE THREAD

**Issue by icegriffinguru** [Itheum/data-dex#144]
In DataNFT/MyDataNFTsElrond.js, this function throws an error.
`const decodedAttributes = codec.decodeTopLevel(Buffer.from(nft['attributes'], 'base64'), dataNftAttributes).valueOf();`

![image](https://user-images.githubusercontent.com/97042732/206282632-20157d14-7302-4935-9b72-9d16ae998211.png)

**Comment by newbreedofgeek** [comment]
fixed
