### ISSUE TITLE
Tweaks to solana mint

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1455]
Remove the below from the datadex

1. Royalties section, donation section from Mint process
2. Disable normal data NFT minting from the UI

**Comment by 911-Benedek-RobertGeorge** [comment]
I added back the normal minting process as it works normaly 
removed the donation and royalties from mint

**Comment by fuzzyduke** [comment]
This is passed, Minting of normal data NFT is available as agreed.
