### ISSUE TITLE
Possible DappCore Bug - Login Options have some weird caching issues

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#146]
Dev testing commits upto https://github.com/Itheum/data-dex/commit/848dc5d2e9453e7dc0e103f22433fa80e4da8df6

Wallet: DeFI Plugin Devnet
Browser: Chrome / Mac

Other errors:

For some reason, clicking on "Maiar App" option in devnet login screen is going to "Web Wallet" instead of opening the Maiar App popup:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/743169/206439698-360d1ac8-b6e4-45a6-8adc-d9da64be957e.png">
Actually after further testing, for me - clicking on Maiar App just reloads last wallet clicked on. i..e if I used DeFi wallet last time, it just reloads that option.

_Originally posted by @newbreedofgeek in https://github.com/Itheum/data-dex/issues/134#issuecomment-1342609077_

**Comment by damienen** [comment]
Maybe we should raise this on dapp-core?
