### ISSUE TITLE
Data NFT - web wallet support for BOTH Minting and Burning

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#148]
How are we going to support "web wallet for minting the Data NFT"?? As it takes the user away from the browser and the UI will close. Any suggestions?

_Originally posted by @newbreedofgeek in https://github.com/Itheum/data-dex/issues/134#issuecomment-1342616002_

**Comment by newbreedofgeek** [comment]
Idea:   Given these work with a "Model", you will need to possible use React Router to push URL fragment to capture each state change so that web wallet can restore this UI state during the callback.

e.g. for minting
selldata/datanft
This route opens the input form

selldata/datanft/minting
This opens the progress model. But we also need a way to restore the "step" of progress

**Comment by icegriffinguru** [comment]
![image](https://user-images.githubusercontent.com/97042732/207950441-6798fbba-d423-4b81-b791-72430544b0c4.png)

Is this modal should be kept after web-wallet redirection?
What states should we keep?

**Comment by damienen** [comment]
@icegriffinguru's right on this one.

Seems to me like web wallet is working just fine. @newbreedofgeek should we close this or is there something I am missing?

**Comment by newbreedofgeek** [comment]
[ ] - Web Wallet Data Marshal signature verification does not work
<img width="587" alt="image" src="https://user-images.githubusercontent.com/743169/211275955-3672fe0c-b422-4fa0-b1d4-0052ddb45b22.png">

**Comment by newbreedofgeek** [comment]
The UX is still wrong on Web Wallet.. let's keep this closed by I will put in a new UX issue on https://github.com/Itheum/data-dex/issues/150
