### ISSUE TITLE
View Data After Minting the Data NFT

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#153]
Wallet: Maiar App
Device: Laptop
Browser: Google Chrome

Description: After minting a Data NFT-FT, I wanted to check Data NFT Functions. When clicking on "Preview" the result was as expected, open a new tab with the dataset preview. When clicking on "View Dataset" the UI tells me that I need to sign a transaction on Maiar App and I receive an error

1) Mint a data NFT
2) Go to https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/datanfts/wallet
3) Click on "View Data"
4) The error pop-up
The error returned can be seen in the picture

Expected Behaviour/Behaviour:
When clicking on View Data I expected a Maiar Pop up to sign a transaction that the Dataset will be opened in a new browser webpage

![image](https://user-images.githubusercontent.com/118804443/211613967-9f69dff4-0eb4-4603-9c8a-1e183f0b7854.png)

**Comment by newbreedofgeek** [comment]
@damienen Maiar App does not allow for signatures as well??

**Comment by damienen** [comment]
@newbreedofgeek it does as far as I know.

I can recheck

**Comment by newbreedofgeek** [comment]
Fixed with upgrade to walletconnectV2. User needs to use the new Maiar App when logging in and should not pick the "use legacy app". 

Note - Elrond team will be decommissioning the old Maiar app soon so we wont support it.
