### ISSUE TITLE
I should not be able to "procure" my own Data NFT from the marketplace

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#156]
Current Behaviour:
I am the creator of `EcoGPRace1 ` (the last NFT). I should not be able to procure this.

Expected Behaviour:
The red box SHOULD NOT appear

![image](https://user-images.githubusercontent.com/743169/214770233-7c4a8b98-ed9c-4706-9164-560b3d2df44d.png)

**Comment by newbreedofgeek** [comment]
Above is UI work that @icegriffinguru can do.

@bucurdavid @damienen Pls confirm that the SC also disallows Owner from buys their own SFT from marketplace. We should have a unit test for this.

**Comment by bucurdavid** [comment]
The current implementation disallows the offer owner and the creator to buy back his NFT. We have a unit test for this. In the latest PR, we updated and only the offer owner cannot accept his own NFT. 

I tested it and what to keep in mind is that the marketplace UI shows that you are the creator even if others list you NFT. I think the best check is to show "De-List" if `offer owner address == logged in address`

![image](https://user-images.githubusercontent.com/46384319/214778605-3e676932-7ddb-4a1b-80c7-e644b9d06a32.png)

**Comment by newbreedofgeek** [comment]
@icegriffinguru Just tested and it's partly fixed but still not working correctly.

1. Alice is creator of new SFT. Mints 10 supply : **WORKS**
2. Alice lists 10 supply onto Marketplace. Alice goes to marketplace and can see her SFTs in the "My data nfts" tab : **WORKS**
3. Alice can also see the 10 supply in the "public marketplace" tab but should not see the "Procure" button : **WORKS**
3. Bob (new buyer) goes into the Marketplace and buys 5 supply from Alice. Bob can see it in his wallet ; **WORKS**
4. Bob lists all 5 into the marketplace again setting a higer price. Bob sees his 5 in his  "My data nfts" tab. He also sees his 5 in the "public marketplace"  tab but he cannot buy his own. `NOT WORKING`
- Current Behaviour:
Bob only see's Alice's 5 remaining SFTs. The 5 he just listed is missing from the "public marketplace" tab and "My data nfts" tab. These 5 have disappeared from all UI (it's not even in his data nft wallet). Even if a new user (e.g. Carol) logs into the Marketplace, she only see's Alice's 5 SFTs.

5. Bob can see Alice's remaining 5 SFTs and should be able to buy that : **WORKS**
6. Alice (Creator) goes to "public marketplace" tab and still sees her 5 SFT (and should not be able to buy them)  - **WORKING**
7. Alice should also see the 5 SFTs published by Bob and SHOULD be able to buy them - `NOT WORKING`
- Current Behaviour:
Alice cannot see the 5 SFTs that Bob bought from her and then placed back into the marketplace. Alice should be able to see these and buy them back. She is the Creator and not Owner - so she can buy them back.


CC @bucurdavid @damienen

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
I think it's because there are more than 25 offers now. Current marketplace only 25 offers. My NFT on marketplace also filters among first 25 offers so other NFTs won't be visible.
I will add pagination soon.

**Comment by damienen** [comment]
> Alice should also see the 5 SFTs published by Bob and SHOULD be able to buy them - NOT WORKING

> Bob lists all 5 into the marketplace again setting a higer price. Bob sees his 5 in his "My data nfts" tab. He also sees his 5 in the "public marketplace" tab but he cannot buy his own.

**Comment by icegriffinguru** [comment]
> > Alice should also see the 5 SFTs published by Bob and SHOULD be able to buy them - NOT WORKING
> 
> > Bob lists all 5 into the marketplace again setting a higer price. Bob sees his 5 in his "My data nfts" tab. He also sees his 5 in the "public marketplace" tab but he cannot buy his own.

@damienen , what do you mean? Does it not work?

**Comment by newbreedofgeek** [comment]
@icegriffinguru and @damienen 

I just tested this with latest code. 

98% working. BUT if I am the Creator and NOT owner of a SFT supply listed on the marketplace - I should be able to buy it back.

E.g.
User A (Alice)
<img width="523" alt="image" src="https://user-images.githubusercontent.com/743169/215660083-883a7f5d-fddc-4234-a0f9-53f3c43c4c73.png">
I should be able to buy Bob's 2 SFT back from him as I am not the owner.



User B (Bob)
<img width="540" alt="image" src="https://user-images.githubusercontent.com/743169/215660110-277f06b1-d636-4ba4-90fe-5bd25184910d.png">
This is correct! Bob cant buy his own SFTs but he can buy Alice's remaining 2

**Comment by icegriffinguru** [comment]
updated

**Comment by fuzzyduke** [comment]
Scenario verified.

Observations over previous anomalies.
1. When Bob can purchases 5 NFTs from Alice, he acquires 5 NFTs in his wallet. Working
2. When Bob lists all 5 NFTs, the NFTs do not show in his wallet, it shows in the "My data NFTs" and "Public Marketplace". Working
3. Alice(creator) can see Bob's(Owner) 5 NFTs listed. She can also buy the NFTs as she is the Creator and not the owner. 

Fixed.

Additional Suggestion: Currently an owner can see Data NFTs that have been placed on the Marketplace under their "My Data NFTs" as well. Perhaps change the "My Data NFTs" to "My Listed Data NFTs".

**Comment by damienen** [comment]
Good suggestion, @fuzzyduke . Will implement that, too, then close the issue
