### ISSUE TITLE
Deep Link does not work

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#158]
Current Behaviour:
User was logged in with their wallet and reloaded the browser on the marketplace page. `https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace` URL.  But the deep link did not work and showed the home page:
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/743169/214771384-bde1aaf1-6971-40d1-ba4f-f81ccb048236.png">

Expected Behaviour:
As the user was logged in, it should go to the deep link (datanfts/marketplace) and show the data nfts in the marketpalce.

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
Where does this happen?
I can't find the same behavior.

**Comment by newbreedofgeek** [comment]
Seems to happen when you open a new tab and paste link.

1. Go to https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app and login and go to /datanfts/wallet
2. Reload page -- it will work fine
3. Open a new tab and paste, https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/datanfts/wallet
4. It shows the wallet login screen. Clicking on 'devnet' immediately works so I guess the session is there.

What ideally should happens:
in Step 4. If does not show login screen

**Comment by icegriffinguru** [comment]
> Seems to happen when you open a new tab and paste link.
> 
> 1. Go to https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app and login and go to /datanfts/wallet
> 2. Reload page -- it will work fine
> 3. Open a new tab and paste, https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/datanfts/wallet
> 4. It shows the wallet login screen. Clicking on 'devnet' immediately works so I guess the session is there.
> 
> What ideally should happens: in Step 4. If does not show login screen

It works normally on my side.

**Comment by newbreedofgeek** [comment]
> Seems to happen when you open a new tab and paste link.
> 
> 1. Go to https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app and login and go to /datanfts/wallet
> 2. Reload page -- it will work fine
> 3. Open a new tab and paste, https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/datanfts/wallet
> 4. It shows the wallet login screen. Clicking on 'devnet' immediately works so I guess the session is there.
> 
> What ideally should happens: in Step 4. If does not show login screen

@damienen do u see this error?

**Comment by damienen** [comment]
It works well on my side as well

**Comment by damienen** [comment]
Closing for now. Will reopen if needed
