### ISSUE TITLE
marketplace - buyer confirmation model calculations are wrong

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#160]
Current Behaviour:
The current popup looks like this for a multiple NFT:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/743169/214775683-e6a79604-43ed-43da-a909-2fc661596421.png">

and like this for single NFTs
<img width="426" alt="image" src="https://user-images.githubusercontent.com/743169/214775749-7b540f64-632f-496c-8ccd-1a26040b7fab.png">

The 'Fee per NFT' and 'Total Fee' text is wrong.

Expected Behaviour:
As per design:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/743169/214775929-391fbd86-73c9-4a8a-978a-4b0a2d5abc80.png">

**Comment by damienen** [comment]
Talked to @bucurdavid about this. 

SC side should be fine, I think it's FE.

CC: @icegriffinguru

**Comment by newbreedofgeek** [comment]
Looking good @icegriffinguru 

Once small change needed so we should buyer fee in ITHEUM as well. See red arrow

<img width="455" alt="image" src="https://user-images.githubusercontent.com/743169/215004575-8ef52a7b-fe14-46ef-8ca0-d6333e64514a.png">

**Comment by icegriffinguru** [comment]
updated

**Comment by newbreedofgeek** [comment]
Checked and looks mostly good.

But I think we need to change text table "Buyer Fee" to "Buyer Fee (per NFT) " for the calculation to make sense.

We can close this after this is doen

**Comment by icegriffinguru** [comment]
updated
