### ISSUE TITLE
Marketplace - Show price per NFT if Owner

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#161]
Currently, if i'm the "Owner" we don't show "procure" button - this is correct.

But we should show the "Price per NFT" so the owner knows how much he listed the NFT for. Price should show in both the "public marketplace" and the "my data nft" tabs.

See updated figma designs.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/743169/215003749-63e9bc0f-1f9d-4de1-a626-28bca45ed689.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/743169/215003775-9bb994f5-3abc-4620-a519-d4bf2f2477cb.png">

**Comment by damienen** [comment]
Should also show listing date

**Comment by icegriffinguru** [comment]
> Should also show listing date

@damienen , OfferOut struct does not have listing date.
Listing date is not in the design. 🤔

**Comment by icegriffinguru** [comment]
updated

**Comment by newbreedofgeek** [comment]
"Price per NFT"  is now showing... let's close asn its fixed.
