### ISSUE TITLE
Text Change for " You must agree on terms of use "

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#162]
Small Suggestion
1.Currently, there is a " You must agree on terms of use "
Maybe we can change that text to " You must READ and Agree on Terms of Use

2. The same checkbox to be added in the "Anti Spam Fee"?
![image](https://user-images.githubusercontent.com/118804443/211644058-2dacbb81-39ad-4341-880d-b285f88fd0aa.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1377748244_

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
I will update the first part.
Regarding the second issue, I think there will be too many things to input and check to mint one NFT.
What text should I put in the checkbox? (like "I have read all terms and agree to them")

**Comment by newbreedofgeek** [comment]
> @newbreedofgeek I will update the first part. Regarding the second issue, I think there will be too many things to input and check to mint one NFT. What text should I put in the checkbox? (like "I have read all terms and agree to them")

The 1st checkbox should be:
[] I have read and I agree to the Terms of Use

The 2nd checkbox for anti-spam fee should be:
[] I accept the deduction of the anti-spam minting fee from my wallet

User needs to check both checkboxes for the minting to be allowed.

@icegriffinguru

**Comment by newbreedofgeek** [comment]
let give this to @bucurdavid

**Comment by icegriffinguru** [comment]
> let give this to @bucurdavid

I'm going to update it.
David will do frontend, too?

**Comment by icegriffinguru** [comment]
updated, @newbreedofgeek
