### ISSUE TITLE
Data NFT Wallet - Burn supply on UI does not reflect due to API latency issues

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#163]
Visual  Issue/Bug/Feedback

Wallet: Maiar App 
Browser: Google Chrome 
Device: Laptop 

Description: Minting a Data NFT and owning one is really good, but what happen when I want to burn some of this supply? I can see how many Data NFTs are in the "collection" how many are out there, and I can Burn. The burn function worked properly ; but when checking after a refresh my supply is 4 out of 5. 

Suggestion: After burning- Update the maximum number of NFTs from that collection 
If not possible- A "warning" message that x NFTs were burned

Steps

1) Go to : https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/
2) Mint a Data NFT with more than 1 as the total supply
3) Go and see your Data NFT
4) Burn some of this supply ( min 1 ) 
5 ) Check the description of the Data NFT

Expected Result

After burning I expected that the total supply to decrease with the amount of burned NFTs ( Visual ) 

Actual Result

The Maximum supply remained as minted 

![image](https://user-images.githubusercontent.com/118804443/211625633-ad6a4fe3-b23d-4f32-91f6-9f5920bbf2e3.png)

**UPDATE!** 

After I've been disconnected, the UI now shows 4 instead of 5, but I've burned another 3, and the new Total supply is not updated (I tried to disconnect and re-connect multiple times )

**UPDATE 2**

Now the balance shows ok after one more refresh; But still it takes too long to be correctly displayed.

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1377649891_

**Comment by newbreedofgeek** [comment]
This is caused by API latency issues. 

We dont need to fix this for initial version but if we have time before mainnet release. We can do some UI tricks to cache locally the counts and decrease the local values when the burn TX succeed. This was the UI immediately reflects changes until API can show live correct numbers.

**Comment by newbreedofgeek** [comment]
Let's aim to fix this via he solution @damienen has

**Comment by damienen** [comment]
Escalated to the MX team, hoping they will solve the endpoint bug. If not, we will use the good endpoint for getting supply

**Comment by damienen** [comment]
Solved by the MX team
