### ISSUE TITLE
UI Suggestion: Compressed view of Data NFT Tiles WHEN NOT LOGGED IN

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#165]
UI Suggestion:

Description: Data NFT Wallet shows the NFTs in a quite big format. 
Suggestion: *Shrink the Data NFT Image
                    *Keep in the "preview" only what's in a green area and add an "EXPAND" button to show all the details of the NFT, such as " Owner, copies, description, creator etc "

![image](https://user-images.githubusercontent.com/118804443/212023188-366912c0-9804-4847-8680-245cceb6a4ab.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1380008775_

**Comment by newbreedofgeek** [comment]
Good idea with the small compressed view of the Image, Title and Short title only. BUT the Expand wont work as it will push content down.

Maybe we need a Model when user clicks on a item that shows full details.

This is low priority for now until we fix feature bugs but we will come back to this in a UI upgrade soon.

**Comment by damienen** [comment]
Added this here as they are related:
> ```
>           UI Suggestion:
> ```
> 
> Clear visual segregation suggested between short title, title and description. ![image](https://user-images.githubusercontent.com/121969933/211082376-e8d53b64-1e84-47ea-833f-e447545128eb.png)
> 
> _Originally posted by @fuzzyduke in [#150 (comment)](https://github.com/Itheum/data-dex/issues/150#issuecomment-1374022527)_

**Comment by icegriffinguru** [comment]
Pushed update but need to be checked.

**Comment by fuzzyduke** [comment]
Verified Fixed, with comment.

Compression is observed in the not logged in view.

Note: Titles are not aligned. Kindly confirm this is expected.

![image](https://user-images.githubusercontent.com/121969933/232912779-f0b509e3-7df5-40bd-a830-added1f0fa3d.png)

**Comment by damienen** [comment]
This is fine. Closing.
