### ISSUE TITLE
Data NFT minter form - numeric input box issue

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#167]
![image](https://user-images.githubusercontent.com/121969933/212977864-4f3a072e-a17a-4a46-a943-5062a966b65d.png)
Description
Intended to place in the value '999', However while clicking within box to "Backspace" the value 1, the action is not permitted.

Expected Behaviour
Backspace should be permitted on single digit so the user can input any digit. 

Actual Behaviour
Backspace is not permitted when single digit is within cell.

_Originally posted by @fuzzyduke in https://github.com/Itheum/data-dex/issues/150#issuecomment-1385831886_

**Comment by newbreedofgeek** [comment]
Let's not fix for now.. we need to revisit the both this and royalty input box behaviours soon.

**Comment by newbreedofgeek** [comment]
see also:

https://github.com/Itheum/data-dex/issues/150#issuecomment-1385838270

**Comment by newbreedofgeek** [comment]
see also - https://github.com/Itheum/data-dex/issues/150#issuecomment-1405488839

**Comment by damienen** [comment]
Advice: usually such input issues are caused by having the validation of the input on the onChange hook.

It can be changed on onBlur so validation only takes place whenever the user is done typing his input (when they deselct the input)

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
If min_royalties is 10, you will never see one digit number on InputBox because invalid value does not work.
If you want to see one digit number, i need to allow invalid amount in InputBox and show error message as I did in the past. This behavior was changed since last issue.

**Comment by newbreedofgeek** [comment]
@icegriffinguru 

Should be same as solution for here: https://github.com/Itheum/data-dex/issues/186#issuecomment-1409791602

```
RULES:

I should be able to delete the input and ONLY put in a number, if I put in 0 or more than available supply or any other character (NOT a number) it should error

I can also use the UP/DOWN. Should not go below 1 and should be less than available supply

IF the input is wrong as above, the button should be disabled.
```

It's best we make a new component that wraps the Chakra input component with all this rules so we can reuse it across all pages.

@icegriffinguru

**Comment by newbreedofgeek** [comment]
fixed
