### ISSUE TITLE
Feature Suggestion - Update selling price or delist part of listed supply

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#170]
Community+Internal:

Suggestion: In the Data NFT Marketplace can we add a button to change the selling price?
Or either delist a small part of the Data NFTs?

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1402486817_

**Comment by newbreedofgeek** [comment]
This is a very good idea. We need to think about it and add some requirement for it.

**Comment by newbreedofgeek** [comment]
@damienen @bucurdavid 

Will these need new endpoint? are they hard to do? if not too hard - I will write up the requirement and we can do it.

**Comment by bucurdavid** [comment]
I think the endpoints are not that hard to be implemented

**Comment by bucurdavid** [comment]
@newbreedofgeek  any updates on this ?

**Comment by damienen** [comment]
This was implemented in the SC side.

@newbreedofgeek @icegriffinguru What are we gonna do on FE?

**Comment by newbreedofgeek** [comment]
I will do the UI design and send to @icegriffinguru

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
updated

**Comment by damienen** [comment]
The "de-list some" button should only be visible if there's more than one NFTs in the listing.

Moreover, as a suggestion, the "new price" when preffering to update the price should start at the actual price.

**Comment by icegriffinguru** [comment]
updated as @damienen  recommeded
