### ISSUE TITLE
Data NFT Marketplace - Show "Listing Time" for Marketplace items

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#171]
For all Data NFT tiles in the "Public marketplace" and the "My Data NFTs" sections, we need to show "listing time". This is the date for when the Owner listed it into the Marketplace. @damienen @bucurdavid is this possible - i.e. to get the date?

@icegriffinguru UI should look like this: (note that the Listing time text size and font needs to be same as Creation Time)

<img width="283" alt="image" src="https://user-images.githubusercontent.com/743169/215010618-4d508bb2-0582-4538-8442-92c02561fe99.png">

**Comment by bucurdavid** [comment]
It is possible to store the timestamp in the Offer struct

**Comment by newbreedofgeek** [comment]
... but is it a good design pattern to store it in the SC. Or should we store this in a Web2 API?

**Comment by bucurdavid** [comment]
The listing time could be handled with the Web2 API, because it is not critical data. If we will need to deal with refund policy, I think the purchase time needs to be stored in the SC.

**Comment by bucurdavid** [comment]
The listing time could be handled with the Web2 API, because it is not critical data. If we will need to deal with refund policy, I think the purchase time needs to be stored in the SC.

**Comment by newbreedofgeek** [comment]
yes agree - for phase 1 we dont need the 'refund'. We can aim to do this in the web2 API which we are designing now
