### ISSUE TITLE
Cosmetic: "Read Terms of Use" and "Read about Anti-Spam Fee" popups need to be updated with content.

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#173]
Cosmetic:

"Read Terms of Use" and "Read about Anti-Spam Fee" popups need to be updated with content.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/121969933/211083210-d4c99813-0f32-4f17-a17e-6cd04ffca152.png">

_Originally posted by @fuzzyduke in https://github.com/Itheum/data-dex/issues/150#issuecomment-1374026628_

**Comment by bucurdavid** [comment]
@newbreedofgeek What content should be there ?

**Comment by newbreedofgeek** [comment]
fixed

**Comment by newbreedofgeek** [comment]
nice.. small UI FIx needed

<img width="164" alt="image" src="https://user-images.githubusercontent.com/743169/216239947-f129d442-1d63-4bd6-860a-4e294e99a012.png">

**Comment by fuzzyduke** [comment]
Lorum Ipsum content is seen in version 240
