### ISSUE TITLE
Add Data NFTs history

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#177]
We have Claims History

Can we add Data NFT's history?
Minting/Burning/Buying/Selling

![image](https://user-images.githubusercontent.com/118804443/212996154-f3ebc426-3bb4-4e09-94b1-887fcd973291.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1385954991_

**Comment by damienen** [comment]
I would like to start implementing this.

@newbreedofgeek Should this an NFT sales history? Sales & buying? What do you think?

**Comment by newbreedofgeek** [comment]
Hi @damienen 

Ideally it should cover all TXs I did with Data NFTs.

**My Interaction History:**
- Minted Data NFT
- Burned Data NFT
- Added Offer to Marketplace
- Changed price in Marketplace
- Removed offer from Marketplace

**My Trade History:**
- Bought someone elses NFT from Marketplace (purchase)
- Someone else Bought my NFT from the Marketplace (sale)

**My Royalties History:**
- Royalty received from XXX trade

If this is too hard... we can do it in a phased approach. (in which case, let's clone this ticket into 3 so we can track it seperately )

1. My Trade History
2. My Royalties History
3. My Interaction History

**Comment by newbreedofgeek** [comment]
It can be the same component as used in this ticket - https://github.com/Itheum/data-dex/issues/326

**Comment by damienen** [comment]
I think a phased approach is the best one here. It would also encourage a modular approach. Once I start working on it I will separate this issue into three.

**Comment by damienen** [comment]
Just realized that everything is pretty easy to put into a table, except for the royalties. Will explain in weekly

**Comment by newbreedofgeek** [comment]
Without a web2 backend we can limit to last 50 TX of above (due to perf issues )

**Comment by damienen** [comment]
I will have to wait for the new SC implementation for this, but I've got an idea on it.

**Comment by bucurdavid** [comment]
Until having a backend with db, the following are hardly doable:
- Royalty received from XXX trade
- Someone else Bought my NFT from the Marketplace (sale)

**Comment by damienen** [comment]
Claims history is already there. Interaction history is nice, I like where this is going.

**Comment by bucurdavid** [comment]
We could improve interactions history with more informations.

**Comment by damienen** [comment]
Okay, you have my attention. What more do you want to add?

**Comment by bucurdavid** [comment]
Maybe another column with “value”

**Comment by newbreedofgeek** [comment]
- Check for duplicate issues
- "Recent Data NFT Interactions"
- Do some paging on the client side, show 25 per page. use the data table component
<img width="871" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/1f28d367-65ae-4522-b48b-7271e776b030">
- Make the Width bigger:
<img width="717" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/8687c03b-ff4e-4175-a09b-c424cacada6b">
- After this is done, make the Claims table and popup look the same

@damienen

**Comment by damienen** [comment]
New table looks ok. But there is a scrolling issue:
![image](https://github.com/Itheum/data-dex/assets/44813558/0d267fc1-770b-4988-82b5-311fa435917e)
I can't scroll down to see all of it
@bucurdavid

**Comment by bucurdavid** [comment]
@damienen please check

**Comment by damienen** [comment]
I looked over it. I like how it looks now. Functional.

Some food for thought:
1. It'd be wise to rename how the button to get here is named in the navbar manu, too. It's View interactions or something similar. It should contain Data NFTs in the name to make it clear
2. If we could in any way show an extra column that contains what has been minted (ex: 3 x DATANFT-nonce) it would be amazing. Let me know if this is doable considering the current no-backend limitations

**Comment by bucurdavid** [comment]
Implemented 1 and 2. Waiting for your thoughts...
@damienen
