### ISSUE TITLE
Add update listing possibility

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#179]
Community+Internal:

Suggestion: In the Data NFT Marketplace can we add a button to change the selling price?
Or either delist a small part of the Data NFTs?

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1402486817_

**Comment by newbreedofgeek** [comment]
Closing as dep - https://github.com/Itheum/data-dex/issues/170
