### ISSUE TITLE
Make the active tab highlighted

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#182]
Internal Suggestion
Highlighted Tab is usually the active tab, on our Data DEX is other way around

Check the screenshot below
1) active tab
2) inactive tab

Can we highlight the active tab and give a gray nuance to the inactive ones?

![image](https://user-images.githubusercontent.com/118804443/215119338-2d69c89c-d224-45a8-91bf-6a7cf8d7f0f6.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1406634983_

**Comment by bucurdavid** [comment]
@newbreedofgeek fixed this

**Comment by newbreedofgeek** [comment]
Seems to have broken something else - https://github.com/Itheum/data-dex/issues/194

**Comment by fuzzyduke** [comment]
UI convention for active/inactive/disabled/parentcategory has to be defined. The inactive tab currently(partially greyed out) gives the impression that the section(s) are disabled.

**Comment by damienen** [comment]
Solved in commit https://github.com/Itheum/data-dex/commit/94382e68e51bd29ceb1f4349311d72ebe20c4a18
