### ISSUE TITLE
Delist appearing on all items on marketplace

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#183]
Community:

Description: While procuring 1 Data NFT, imedtiatlly after signing the TX go to "MY DATA NFTs" and you are able to see all other Data NFT's listed on Marketplace but with one BIG difference. All appear as yours and you can see a " Delist" button, and you can interact with that ( TX fail )

Step1- Go to Data NFT Marketplace
Step2 - Procure 1 Data NFT
Step3 -Quickly swap the pages to "My Data NFT"
Step4 -The visual bug appear

Expected behavior - When i click on the My data nft page after signing the tx to procure 1 Data NFT it's supposed to display my own data NFTs, not the ones listed on marketplace with a delist option
![image](https://user-images.githubusercontent.com/118804443/215194423-ea797beb-296c-4b8f-8097-de8918e33879.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1407060557_

**Comment by newbreedofgeek** [comment]
Seems to be fixed. Cant repro anymore.
