### ISSUE TITLE
iPhone zooming in when opening form

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#185]
Community ( Personally i cannot confirm it, tried with a mobile version with Android, and works ok with my phone, maybe other phones with get this )

Description: After successfully signing a transaction you get a message, that the transaction is going through. If you go to Advertise data and click on the Data Stream URL or another field, everything will be zoomed in and you cannot close the transaction message. On this point zooming out won't work

Step 1) Claim Faucet Tokens
Step 2) Go to Advertise data
Step 3) Click on Data stream URL field 
Step 4 ) Get the error 

Expected behavior:
TX message to be closed automatically or, not to zoom in after clicking on the Data Stream field

See more details in the pics attached:
Pic1 before clicking on Data Stream URL
Pic 2 After clicking on Data Stream URL
![image](https://user-images.githubusercontent.com/118804443/215322403-62b9f7cf-1cc8-4885-a0cb-c83c7c4a21d1.png)
![image](https://user-images.githubusercontent.com/118804443/215322451-23cb8b2f-4187-473a-a2a5-814d85c40aad.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1407634371_

**Comment by newbreedofgeek** [comment]
Let's do a few mobile CSS fix for critical issues.

**Comment by damienen** [comment]
Solved. Closing
