### ISSUE TITLE
Cannot properly update the number in burn form

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#186]
Community:

Description: Trying to burn NFTs, if you try to delete the numbers from the keyboard is not working properly, automatically gives you the error that the amount cannot be 0

To reproduce
Step1) Go to your Wallet
Step2 ) selected one Data NFT
Step 3) Click on Burn
Step 4) in the How many do you want to burn area try to delete the preset number 1 and get the error. The same thing applies if you already change to another number, eg 9 and you try to delete

Internal suggestion 
If I try to delete the number written in the box, and it goes to 0, then the burn button is deactivated ( Change it's color too, make it red, until you choose a number higher than 1 and lower than the total supply owned  )

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1407636932_

**Comment by damienen** [comment]
@icegriffinguru 

              Advice: usually such input issues are caused by having the validation of the input on the onChange hook.

It can be changed on onBlur so validation only takes place whenever the user is done typing his input (when they deselct the input)

_Originally posted by @damienen in https://github.com/Itheum/data-dex/issues/167#issuecomment-1408788957_

This is to solve people not being able to delete their number temporarily

**Comment by newbreedofgeek** [comment]
RULES:

- I should be able to delete the input and ONLY put in a number, if I put in 0 or more than available supply or any other character (NOT a number) it should error
- I can also use the UP/DOWN. Should not go below 1 and should be less than available supply

- IF the input is wrong as above, the button should be disabled.

@icegriffinguru

**Comment by icegriffinguru** [comment]
> 

@newbreedofgeek 
this was original behavior - do you want this?
https://github.com/Itheum/data-dex/issues/150#issuecomment-1381561836

**Comment by damienen** [comment]
Solved everything except this:
> RULES:
> 
> a) I should be able to delete the input and ONLY put in a numeric positive number, if I put in 0 or more than available supply/min/max royalty or any other character (NOT a number) it should not allow me to enter it. User should also be able to backspace to remove a value and enter new one.

User can still input 0, everything else is good. And when they blur, the zero changes to the min amount acceptable. The current implementation is very clean in terms of how it is written and I think it's not worth changing it for that 0.

//TODO: talk this at meeting in the morning

**Comment by newbreedofgeek** [comment]
it's fine.. let's close
