### ISSUE TITLE
Numeric boxes - up/down does not work

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#192]
These buttons no longer work :

<img width="206" alt="image" src="https://user-images.githubusercontent.com/743169/215938139-f3aef279-108a-48bb-8e73-b3f0aa2b9e59.png">

Please fix this in all numeric inputs (with up/down) across all screen that use it.

**Comment by icegriffinguru** [comment]
![image](https://user-images.githubusercontent.com/97042732/215952424-c2fe7a67-3fb4-43fb-b323-4e00c626ec4e.png)

@newbreedofgeek 
These first numbers are your current balance.
Numeric inputs work on my side.

**Comment by damienen** [comment]
Works for me, too. 

@newbreedofgeek can you update?

**Comment by newbreedofgeek** [comment]
Fixed
