### ISSUE TITLE
Data NFT Listing Should allow for FREE offers

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#193]
As per design, when a user lists a Data NFT in the marketplace they should be able to select a 0 (FREE).

Note that the UI labels on button should reflex these designs:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/743169/215938419-36900dff-3f45-478a-92fc-4d5ff25ad8f5.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/743169/215938486-71633bd2-915c-4ebc-8f9a-bd85e0c4baa2.png">

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
fixed

**Comment by newbreedofgeek** [comment]
nice.. small UI FIx needed

<img width="164" alt="image" src="https://user-images.githubusercontent.com/743169/216239947-f129d442-1d63-4bd6-860a-4e294e99a012.png">

**Comment by icegriffinguru** [comment]
it was already fixed
i'm not sure why it shows in that way.

**Comment by damienen** [comment]
We should have similar behavior when we look at NFTs priced at 0 ITHEUM, too.

On marketplace view it shouldn't be "Fee per NFT: 0 ITHEUM", but rather "Fee per NFT: Free"

**Comment by icegriffinguru** [comment]
updated
