### ISSUE TITLE
ChainSupportedInput menu buttons are broken

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#194]
In the last UI change pushed by @bucurdavid, these buttons are now broken. (previously they worked)

<img width="219" alt="image" src="https://user-images.githubusercontent.com/743169/215939322-595e4e5f-df2d-4a2b-bf0b-e6aaaec3ec58.png">

Note that these buttons are wrapped like so:
https://github.com/Itheum/data-dex/blob/main/src/App/AppElrond.js#L328

They use a custom wrapped ChainSupportedInput component around to prevent uses clicking on them in chain environments (devnet vs mainnet) that don't support the feature yet. 
See - https://github.com/Itheum/data-dex/blob/main/src/UtilComps/ChainSupportedInput.js

**Comment by damienen** [comment]
Solved in commit https://github.com/Itheum/data-dex/commit/94382e68e51bd29ceb1f4349311d72ebe20c4a18
