### ISSUE TITLE
When listing my Data NFT in the marketplace, it should not let me exceed "max price limit"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#195]
In the marketplace contract we configure a "max price limit". 

When the user is trying to enter the price, we need to notify the user that they exceeded this price limit (if they go over it).

We should them an UI message AND/OR disable the action button.

e.g. message
"Your price exceed the maximum price limit" (in red)

This is not high priority as max will be already high like 1000 ITHEUM and plp trying to go over this are probably trying to spam system. So them paying gas to get the SC reject the TX is not bad.

**Comment by icegriffinguru** [comment]
fixed
