### ISSUE TITLE
Section active state

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#198]
Description
Upon browsing to the Marketplace "Public Marketplace" is active however it is visually counter-intuitive as it has an inactive shade.

![image](https://user-images.githubusercontent.com/121969933/216291216-049f03dd-9a94-4d83-b6db-8902f24962eb.png)

Expected Behavior.
The active section "Public Marketplace" should show as an active state against other sections "My Data NFTs"

**Comment by newbreedofgeek** [comment]
Fixed in new UI I believe
