### ISSUE TITLE
Standard navigation behaviour for Wallet and Marketplace.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#199]
Description

If you freshly log in and click on "Wallet" or "Marketplace" you see the below. However if you toggle between them you see the actual page of the Wallet and Marketplace respectively. Is this intended?
ImgRef1
![image](https://user-images.githubusercontent.com/121969933/216358692-c5dee6a5-8090-4491-b8e5-09bec16a6235.png)

Expected Result:
1. Post fresh login, when a user browses to Wallet they should see the below and not ImgRef1
ImgRef2
![image](https://user-images.githubusercontent.com/121969933/216359690-ff19a97e-42fc-403b-81e3-ef96f37aa9bd.png)
2. Post fresh login, when a user browses to Marketplace they should see the below and not ImgRef1
ImgRef3
![image](https://user-images.githubusercontent.com/121969933/216359831-68d3fd78-b00e-4003-93ac-a57d7ae25ee4.png)
3. If Imgref1 is to be seen it can be so on clicking the parent node Data NFTs

**Comment by newbreedofgeek** [comment]
Seems to be old UI and behaviour so closing as it's fixed in new UI
