### ISSUE TITLE
Regression - Minting Form checkbox validation issues

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#206]
1. should not enable button if user does NOT agree to "I accept the deduction...."
<img width="557" alt="image" src="https://user-images.githubusercontent.com/743169/216876479-1690534f-c156-4b33-9367-4b4c6186d117.png">

2. Validation message should be "You need to agree to anti-spam deduction to mint"

**Comment by icegriffinguru** [comment]
Fixed
