### ISSUE TITLE
Regression - Minter Form validation is broken. 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#207]
This button should not be clickable until all validation passes.

On Page load -- broken
<img width="946" alt="image" src="https://user-images.githubusercontent.com/743169/216885304-afee8157-db72-46f5-93f3-e6a5db676d19.png">

On Form Focus -- broken
<img width="278" alt="image" src="https://user-images.githubusercontent.com/743169/216885406-042adbea-47e9-4cfd-bff2-9f83d43f7a80.png">

**Comment by newbreedofgeek** [comment]
most likely also linked to https://github.com/Itheum/data-dex/issues/206

**Comment by icegriffinguru** [comment]
Fixed.
We should use `isDisabled` instead of old `disabled` attribute.

Chakra UI rule has been changed a little bit since last package.json update. I think it's due to eslint rules or react version. (Chakra version is not updated.)
