### ISSUE TITLE
Suggested Feature: Associate name service or herotag for readable identification

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#211]
Feature Rationale:
Associating a name service with creators/consumers can assist in quicker identification.

**Comment by damienen** [comment]
We need the herotag (and other account information that comes with it) saved inside a store variable in order to access it around the Data Dex

**Comment by icegriffinguru** [comment]
mx-sdk-dapp's `useGetAccount` hook returns `AccountType` which has `username` attribute.
`username` attribute is maiar tag.
I can save it in the store but it seems redundant logic.

**Comment by damienen** [comment]
Does the hook have the username in its store? Or does it make a call whenever you use the hook? If it makes a call, then it's better we save it in our own store. If it does not make a call, then yes, it's redundant.

CC: @Enciusan

**Comment by icegriffinguru** [comment]
username (maiar tag) is stored in a hook and its value is set once dapp loaded. No call every time.

**Comment by damienen** [comment]
Perfect.

Then we can close this.

CC: @Enciusan

**Comment by Enciusan** [comment]
Awesome thank you @icegriffinguru
