### ISSUE TITLE
Possible Paging Issue in marketplace

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#213]
Current Behaviour:
- I minted a few Data NFTs and posted them onto the marketplace. 
- The last one I posted, appears in "my listed data nfts" but is missing in the public marketplace 

![image](https://user-images.githubusercontent.com/743169/217105768-fbb098c9-d679-4604-995b-7fc46f42a866.png)

- but does not appear in the "public marketplace"
- note that the public marketplace has 8 NFT already... but the paging (next page) is not clickable.

![image](https://user-images.githubusercontent.com/743169/217105714-fa9b6fab-5335-4571-ab44-5a752b89a1f4.png)

Expected Behaviour:
- if only 8 allowed per page, then we should be able to go to next page.

**Comment by icegriffinguru** [comment]
Fixed
