### ISSUE TITLE
Upon Cancelling Mint transaction and Re minting, Error message shows.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#216]
Description:
Upon Cancelling initial mint and Re-Minting with different metadata, "Process Error" message is still seen while mint workflow proceeds.

fig1
![image](https://user-images.githubusercontent.com/121969933/217159895-ac62a303-8e30-4141-bb8d-1cec2958af75.png)

Also the first 3 steps show as already completed, despite the metadata being changed.

Steps to reproduce.
1. Click on "Advertise Data"
2. Fill in all the fields in the to create the Data NFT.
3. Click "Mint and Trade as NFT"
4. Click on "close".
5. Change value in a field and click on "Mint and Trade as NFT".

fig2
![image](https://user-images.githubusercontent.com/121969933/217160402-ca8cd7f8-9aca-4588-a0f1-b4eb863495b7.png)

Expected Behaviour.
1. Upon reminting with different metadata, the first 3 steps should reprocess.
2. There should be no error message on minting the second time as shown in fig1.

**Comment by damienen** [comment]
1. First 3 steps reprocessing it not necessary
2. 2. No error message is pretty necessary

**Comment by newbreedofgeek** [comment]
- When user closes the "Process Error" model, we reshow the form with data filled in - THIS IS CORRECT
- But as we dont reset the "progress model" state, when user mints again. It shows the old progress model state. - THIS IS WRONG. To fix, also reset the progress model state.

**Comment by damienen** [comment]
Tested. Works. Closing
