### ISSUE TITLE
Paging buttons should not be clickable if there is less than 8 (or page number)

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#217]
- Currently, in Public Marketplace there are more than 8 items so paging works well
![image](https://user-images.githubusercontent.com/743169/217248660-4598befd-d02e-48e5-865a-c9fcde48f69f.png)

- BUT, in "my listed Data NFTs" - I only have 4 items so paging buttons should be greyed out and not clickable.
![image](https://user-images.githubusercontent.com/743169/217248942-3d0d66c5-0bbe-44fe-b69b-4bbfa8bbee46.png)

**Comment by fuzzyduke** [comment]
QA verified. Fixed.
