### ISSUE TITLE
Listing price automatically adjusted to 1000 ITHEUM if you try to list for 1000+

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#220]
Bug 

### **Description:** 
Mint a Data NFT and list it. In the listing process manually adjusted the sale price to "1111" and after I clicked to list I've been restricted to 1000 ( automatically change the price box to 1000 )

### **Steps to reproduce** 
1: Go to Mint a Data NFT
2: Try to place it on the marketplace with more than 1000 ITHEUM tokens
3: The price box will be automatically adjusted top 1000 after you click on "List 1 for 1000+..."

### **Expected Behavior:** 
When I add 1300 in price text box I expect to list the Data NFT for 1300, not to receive a pop up and automatically adjusted the list price to 1000

### **Device:** 
Laptop
### **Browser:** 
Chrome
### **Wallet:** 
DeFI Wallet

![image](https://user-images.githubusercontent.com/118804443/217635448-606cb99a-dc10-4359-b67f-dcf1f77c3e57.png)

**Comment by damienen** [comment]
A warning should be shown when the user goes over the max or under min listing price allowed in order to let them know they went over it.

Else, this is expected behavior.

Red colored message, under txtbox, "Maximum listing price is X", "Minimum listing price is X"

**Comment by icegriffinguru** [comment]
Fixed
@damienen

**Comment by fuzzyduke** [comment]
QA verified. Fixed.

Note: The list button is active if the amount is increased. However if clicked on, then the amount is reset to the max of 1000.

![image](https://user-images.githubusercontent.com/121969933/218049553-d3f4d19d-bc41-4c52-be41-451dee9d93e0.png)
