### ISSUE TITLE
Interface not refreshing while waiting for a tx to go through

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#222]
Bug

### **Description:**
While waiting for a transaction to go through, you're not able to see what's in your Data NFT Wallet/ or on Data NFT Marketplace ( Pics attached )

### **Steps:**

1)Claim from the Claims Portal ( Sign the transaction )
2)Go to Data NFT's Menu
3)Go to Wallet/Marketplace
4)The error is there ( You cannot view anything )
4.1) This error appears for any type of transaction that's ongoing( You can procure 1 Data NFT and then change menus - from marketplace to Wallet and vice-versa )
### **Expected** behavior: 
While waiting for a transaction message to disappear from the interface I expect to be able to see what's on the Marketplace or in my Wallet

![image](https://user-images.githubusercontent.com/118804443/217637657-de145fc4-c29e-4fb5-b639-914f98ca94f9.png)
![image](https://user-images.githubusercontent.com/118804443/217637700-1a8bcdb9-7509-4081-a6f9-37f09217a630.png)

**Comment by damienen** [comment]
The ideal behavior is that having a processing transaction the user should be able to move anywhere and it should work

**Comment by newbreedofgeek** [comment]
... we need to 1st investigate what is going on. MAYBE -- pending TXs are casing other Elrond products to "pause". But we have to confirm this

**Comment by damienen** [comment]
Leave this as the last issue in the Data NFT Public Testing Round 2 Milestone

**Comment by icegriffinguru** [comment]
@damienen , this issue was fixed.

**Comment by damienen** [comment]
@fuzzyduke Please test

**Comment by damienen** [comment]
I tested myself. It is indeed solved.

Closing
