### ISSUE TITLE
View claims history not functional

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#224]
Type: Bug

**Description:**
 Claims history is not visible, you cannot access that. Instead of getting the claims history you will get an error message " ER4 Could not get your recent transactions from MultiversX Blockchain

**Steps to reproduce**

1. Go to Claims ( Add some claims by requesting from faucet )
2. Claim Allocation
3. Claim Rewards
4. Click on view Claims History

**Expected behavior:**
 When I click on View Claims History I expected to see a full list of my previous claims

**Actual behavior:**
1. History is not viewable and error "Could not get your recent transactions from MultiversX blockchain" is encountered.

**Device**: Laptop
**Wallet**: DeFi wallet
**Browser**: Chrome

![image](https://user-images.githubusercontent.com/121969933/217647964-75bf5f0a-6fa0-43ac-b234-a70956e3c2bf.png)

**Comment by newbreedofgeek** [comment]
@damienen as part of this ticket, the claims history should also be updated to show claims of type "royalty"

**Comment by damienen** [comment]
Solved
