### ISSUE TITLE
Attempting to burn NFTs in a scenario throws error.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#226]
**Type:**Bug

**Description**: 
Entering amount to burn NFTs throws "Not enough Balance" when toggling up the count.
Say you mint 500, then as you toggle upward to 6, then above message is seen.

**Steps to Reproduce**

1. Go to advertise data
2. Create a Data NFT ( Choose more copies )
3. Go to Burn
4. Increase the burning amount by 1, multiple times, in the text box until you encounter an error.
5. If you mint 300 NFT's you will get the error when trying to burn 4.

**Expected behavior:** 
Burning of NFTs should be permitted till the amount of owned NFTs.
![image](https://user-images.githubusercontent.com/121969933/217654224-737749ff-b826-496b-a265-d461d01bede0.png)

**Comment by damienen** [comment]
Also the error should be something more specific like "Data NFT balance exceeded"

**Comment by damienen** [comment]
This will be fixed if you fix #229

**Comment by damienen** [comment]
Solved. Closed
