### ISSUE TITLE
Pagination Anomaly encountered when switching from max Marketplace page to "My Listed Data NFTs"

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#227]
Type: Bug

Description: 
Pagination anomaly seen when toggling between Marketplace and "My Listed Data NFTs"

Steps:
1 Go to the public marketplace
2 Push the right arrow to see the last page(3 of 3)
3 Go to My listed Data NFT and get the error (1 of 1)

Expected Behavior:
Upon going back to My Listed Data NFTs from page 3 of marketplace, My Listed Data NFTs Should show correctly.

Actual Behaviour
Upon going back to My Listed Data NFTs from page 3 of marketplace, My Listed Data NFTs Should shows truncated data as in the figure below.

![image](https://user-images.githubusercontent.com/121969933/217666584-819b8585-7765-4db2-a99c-fd360fe69c89.png)

**Comment by damienen** [comment]
Details of "my listings" should be available regardless of which page you are moving from into "my listed..."

**Comment by damienen** [comment]
@icegriffinguru It's not happening under stress and when moving to the other page everything works fine. Maybe talk with @fuzzyduke about reproducing it.

**Comment by BogdanCostinas** [comment]
Update:
If you do all the steps listed above, and click on "DELIST ALL" You will get a black screen

**Comment by icegriffinguru** [comment]
@BogdanCostinas , fixed.

**Comment by damienen** [comment]
@fuzzyduke please test

**Comment by damienen** [comment]
Test. Solved. Closing

**Comment by damienen** [comment]
@icegriffinguru now when you move from page 2-3 or more to my listed data nfts the details of the listed nfts are not shown. You can only see the photo, preview data button, but not actual information about the Data NFT. 

Refreshing makes it so that the details are then shown.

To reproduce: (Precondition: have a listed NFT)
1. Go to marketplace
2. Go to last page
3. Switch to my listed nfts
4. Refresh page to actually see details

**Comment by icegriffinguru** [comment]
@damienen 
Can you check API is working when NFT metadata is not shown?

**Comment by damienen** [comment]
Yes, it is working. A refresh solves the issue. Switching to the my listed nfts tab from the first page of market does not create this issue.

@icegriffinguru

**Comment by icegriffinguru** [comment]
I don't get such issue unless API refuses query.
What do you think is the solution?

**Comment by newbreedofgeek** [comment]
If Elrond API is slow to fetch any data.. we have to show the "skeleton" loading. This will be the best UX

**Comment by damienen** [comment]
@icegriffinguru bug is not fixed. check video for instructions on reproducing

https://user-images.githubusercontent.com/44813558/220632998-cb42065e-2755-4bbe-a444-393be9278597.mp4

**Comment by damienen** [comment]
I had some time so I fixed it on your branch, @icegriffinguru

**Comment by fuzzyduke** [comment]
Fixed.
