### ISSUE TITLE
Large amounts should be handled in the buttons. "I want to burn my 23xxx Data NFTs"

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#228]
Description:
Upon Adding more than the number of owned Data NFTs, the button updates as well. 

Steps to Reproduce

Expected Behavior
1. "I want to burn" button should be handled as large numbers are added.  Perhaps allow max of owned Data NFTs in the "I want to Burn my.." button.

Actual Behavior.
1. As a user adds extra digits even beyond the owned data NFTs, the count continues to increase

![image](https://user-images.githubusercontent.com/121969933/217666920-d38647d4-1571-42f4-89d1-771f093b922b.png)

**Comment by damienen** [comment]
Max should my balance
Min should be 1

Behavior should be the same as for the other numberinputs.

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
QA verified. fixed

Note: The button reflects exceeded amount

![image](https://user-images.githubusercontent.com/121969933/218048116-868270db-f59e-4b88-9e8a-8c3e262a3e77.png)
