### ISSUE TITLE
When I press backspace to clear numeric inputs, I get NaN error

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#231]
1. On this screen:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/743169/218090709-cf39ad70-2f74-42a5-950f-17348c27d9c9.png">

2. I select the input box and hit backspace. I get a NaN
<img width="423" alt="image" src="https://user-images.githubusercontent.com/743169/218090781-2114ce70-0ed2-4914-bce8-d906f9a5282d.png">

3. Also happens in the Data NFT Wallet screen
<img width="274" alt="image" src="https://user-images.githubusercontent.com/743169/218090936-39f4777e-6303-4979-a5c9-5bce55210cce.png">

And other inputs as well.. please check and FIX ALL INPUTs as part of this issue ticket. (not just the above ones)

**Comment by icegriffinguru** [comment]
Empty string won't work in NumberInput now because it's tied to number state (only 0 works but not NaN value)

**Comment by damienen** [comment]
@fuzzyduke to be tested

**Comment by damienen** [comment]
Test. Works. Closing
