### ISSUE TITLE
Preview Data button in the Data NFT Marketplace view

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#232]
- When user is in the "Public Marketplace" tab, we need to provide them the option to "Preview Data"
- This SHOULD not appear in the "My Data NFTs" tab
- Logic can be copied from the "Data NFT Wallet", where data preview option is already implemented.

Design Recommendation :
<img width="365" alt="image" src="https://user-images.githubusercontent.com/743169/218256845-718d4378-fa67-4aec-86ee-7c80ee451699.png">

**Comment by damienen** [comment]
You can copy the functionality from the Data NFT Wallet

**Comment by damienen** [comment]
@fuzzyduke please test

**Comment by damienen** [comment]
My listed data NFTs preview button is not working

**Comment by damienen** [comment]
Seems to work now!

Closing
