### ISSUE TITLE
Add "Royalties" claims option to Claims Portal UI

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#233]
Once we add support for the new "royalties" type in the Claims Portal Smart Contract and integrate it with the Data Marketplace creator royalties distribution feature, we need to update the Claims Portal UI to suppoer royalties claims.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/743169/218257307-c94740a8-d95b-451a-8c56-a8d535ea425f.png">

Existing logic for other claims buckers (rewards, royalties etc) should remain the same.

**Comment by newbreedofgeek** [comment]
@damienen assigning to you.. feel free to reassign as you feel fit.

**Comment by damienen** [comment]
Done.

@fuzzyduke Check when you have time
