### ISSUE TITLE
Offers/Negiciations/Barganing

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#235]
Suggestion:

Negociations / Barganing 

Atm, I am surfing through the Data NFT Marketplace and I can see a dataset that might be attractive. I am checking the price but it might be too spicy for me. I have 2 options now: Accept the spicy price or refuse this. Let's add the 3rd option to the Data Marketplace: OFFERS

By seeing a Data NFT with a spicy price, I might be willing to buy it for a lower price, if I can send a counteroffer that might increase the trade numbers

**Comment by fuzzyduke** [comment]
Valid point @BogdanCostinas 

Suggestion: To add "Offers" by interested consumers. We can have a list of offers in descending order for the Lister to consider for issuance of sale.

**Comment by damienen** [comment]
Duplicate of #184
