### ISSUE TITLE
"Delist some" options-pop up message don't show you how many are listed

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#236]
Suggestion community

If you want to delist some Data NFTs if you hit that option, you won't be able to see how many you have listed. Add a "field" in the pop-up message that shows your amount of listed data NFTs.

See the example in the pic attached:

![image](https://user-images.githubusercontent.com/118804443/218333943-60e30e65-9444-4a2a-99c3-58b80272ba75.png)

**Comment by fuzzyduke** [comment]
Verified Fixed.

Feild added "Listed Supply"

![image](https://user-images.githubusercontent.com/121969933/226431527-64205ca3-5440-4ae3-b619-9c062ed10e08.png)
