### ISSUE TITLE
Update the price for a data NFT will redirect you to Public Marketplace

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#237]
Bug Community

### **Description:**
If you want to update a data nft price, you'll be redirected to Public Marketplace right after signing the tx ( Web Wallet )

### **Steps to reproduce**
1) List a Data NFT
2) Go to My listed Data NFT
3) Update Price
4) Sign the tx
5) You'll be redirected to public Marketplace

### **Expected Behavior:**
Once signing the tx to update the price, I expect to see that price updated in my Listed Data NFT, not to be redirected to the Public marketplace

### **Device:**
Laptop/Desktop
### **Wallet:**
Web Wallet
### **Browser:**
Chrome

**Comment by icegriffinguru** [comment]
@BogdanCostinas , what kind of wallet have you used?
It did not redirect for me.

**Comment by BogdanCostinas** [comment]
@icegriffinguru Web Wallet and Chrome as browser. Just tried, again and again, I've been redirected

**Comment by damienen** [comment]
It redirects me, too. This is happening because the Web Wallet hook redirects back to the page we were on, but the state is reset when getting back as we have no mechanism of preserving it.

In order to solve this we would either:
A. Need some tool to keep state between web wallet hooks, 
B. Separate the Data NFT Marketplace page route from the My Listed NFTs page route

@icegriffinguru I think B is easier. What do you say?

@newbreedofgeek Should we prioritize this or defer it to future work?

**Comment by icegriffinguru** [comment]
B is the choice.

**Comment by newbreedofgeek** [comment]
Let's go for B.

`/datanfts/marketplace/my` (When user clicks on the "My Listed Data NFTs", we need to use react-router to push this route)

**Comment by damienen** [comment]
@icegriffinguru can you do this change, please?

**Comment by icegriffinguru** [comment]
i'm on it

**Comment by icegriffinguru** [comment]
@damienen 
Fixed

**Comment by damienen** [comment]
Confirmed. Closed

**Comment by fuzzyduke** [comment]
Note: If the Item price is updated on page 2, then post update the redirect is seen to page 1. (However the item is on page 2)
Kindly confirm the behavior.

**Comment by icegriffinguru** [comment]
@newbreedofgeek , @damienen 
Do you think dynamic url for pagination is needed?

**Comment by damienen** [comment]
Yes, let's do it

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Checked. It is actually fixed. Not merging yet as I am waiting for another issue on the branch to be touched up
