### ISSUE TITLE
One can remint Data NFT with same metadata in a scenario.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#242]
Ability to remint Data NFT with same metadata in a scenario.

Steps
1.  Click on Advertise Data
2.  Enter details for the Data NFT-FT
3.  Click "Mint and Trade as NFT"
4.  Click close button instead of confirming the transaction
5.  Now click "Mint and Trade as NFT" again
6.  Previous error message seen.
7.  Continue the mint.
8.  Fig 1 seen.
9.  Click on close.(error message)
10.You can remint as the error close button does not exit the main Data NFT FT popup.

Expected Behaviour.
1. Error message should not be seen on re minting as it is from a previous event.

Fig1
![image](https://user-images.githubusercontent.com/121969933/218598030-b1fcc5e1-e19c-4a75-a99d-5a7239f4a203.png)

**Comment by newbreedofgeek** [comment]
Related to https://github.com/Itheum/data-dex/issues/216 - fixing the other should fix this as well.

**Comment by damienen** [comment]
Tested. Works. Closing.
