### ISSUE TITLE
UI Enhancement for items with varying descriptions.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#244]
Description:
There seems to be too much empty space in the case a Data NFT is minted with a short title and description.

![image](https://user-images.githubusercontent.com/121969933/218663382-66780f14-50f1-4e32-8a57-ff9548f5cd7d.png)

**Comment by damienen** [comment]
Show first two lines and when you hover over it it shows the whole description as a tooltip

**Comment by newbreedofgeek** [comment]
We should do show first 2 lines with this "fade effect". When you hover over it it shows the whole description as a tooltip.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/743169/220260166-381a189a-4ab9-4354-a943-413d3b7ee658.png">

**Comment by damienen** [comment]
@fuzzyduke balance seems aligned, doesn't it? What is the expected behavopr of it occupies two rows?
@Enciusan please check it out

**Comment by Enciusan** [comment]
I'll take a look.
