### ISSUE TITLE
Suggestion: Have preview URL as optional

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#246]
Suggestion Rationale:
There may be cases in which a preview is difficult to provide, this could be for streams or AI models.
In such a case consideration for optional can be placed.

Factors to consider.
1. While the user is entering they can see an option and also a note mentioning that the preview provides more insights, to encourage them to provide a preview.
2. Place a disclaimer for consumers that the preview is not available. This may trigger them to do due diligence on the creator. Note: creator data NFT publishing history and reputation can be useful here.

**Comment by damienen** [comment]
Decided to keep the preview data as mandatory in order to decrease the likelihood that someone just mints some garbage as their data and not show a preview
