### ISSUE TITLE
Provide more options for Time limited access.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#247]
Could we kindly have more "Access Time Limit per SFT:" options. Like 1 day, 1 week, 1 month.

![image](https://user-images.githubusercontent.com/121969933/218867983-0d95ff60-9c7e-46f5-971d-e6b3b2dd672b.png)

**Comment by damienen** [comment]
We should hide the

"Advanced
... Unlimited"

until we implement more functionality for it as it causes confusion

**Comment by damienen** [comment]
@fuzzyduke please test

**Comment by damienen** [comment]
Works. Solved. Closing
