### ISSUE TITLE
Public google drive .txt file is not allowed in the data stream URL.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#250]
Please Verify if google links can be used for the data stream URL

https://drive.google.com/file/d/1S8xYpA955uyWoxP98XSkElPTR9uX6-Z5/view?usp=sharing

The link is publicly available however the message show indicates the url is not public. Kindly verify mechanism.

![image](https://user-images.githubusercontent.com/121969933/218875393-5ffc9c69-8a79-4a8b-ba93-396879475bcf.png)

**Comment by damienen** [comment]
Google Drive not allowed

**Comment by damienen** [comment]
We need validation on the Data Dex to block Google Drive URLs

Should be made so in the future we can add more blockers

**Comment by damienen** [comment]
Works. Closing.
