### ISSUE TITLE
Publicly accessible file is not detected as public

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#251]
Description:
The below URL is publicly available, however message encountered to not be available.
https://github.com/onnx/models/raw/main/vision/body_analysis/arcface/model/arcfaceresnet100-8.tar.gz

![image](https://user-images.githubusercontent.com/121969933/218881577-f775375c-77f0-4e18-a009-882f86a2b8f3.png)

Probably related to issue 250, however the link provided there is a publicly accessible google drive file.

**Comment by damienen** [comment]
https://raw.githubusercontent.com/Itheum/data-assets/main/Health/H1__Signs_of_Anxiety_in_American_Households_due_to_Covid19/dataset.json

If you use this format it will work

**Comment by damienen** [comment]
Not an issue to solve in itself. Closing
