### ISSUE TITLE
Page 2 should be populated when page 1 item slots are filled.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#252]
Description:
Within a given page, items are placed in the second page despite there being space for items in the first page.

In page 1 we see 8 items, 6 on the first row, 2 on the second row. fig1
In page 2 we see 2 items.

Fig1
![image](https://user-images.githubusercontent.com/121969933/219144631-cd9d25e5-9b4b-4873-b4fc-4a18c0b1d89c.png)
Fig2
![image](https://user-images.githubusercontent.com/121969933/219145343-19db2d53-0196-499c-bb8b-50569e288c60.png)

**Comment by damienen** [comment]
This is responsive. Will rivisit with UI revamp
