### ISSUE TITLE
Royalties do not reflect in the claims section

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#253]
Description:
Royalties do not reflect in the claims section, tested in release 241.
![image](https://user-images.githubusercontent.com/121969933/219172442-c1d96835-9355-47c0-b00e-9c758f38a3ee.png)

Step 1
1. Create a Data NFT with royalties and list.
2. User 2 acquires NFT and relists
3. User 3 buys from user 2.4. 
5. Post this royalties should be seen to user 1 as a claim.

https://devnet-explorer.multiversx.com/transactions/d83e9c71c9f9ecf008a6313313bd39d0351cb1074a6832441571c67239986159#1475ada864b1da9821af92857d70fe617b99122492e31ceb3b2f4e4f868f16c4

**Comment by damienen** [comment]
Part of the Royalties integration

**Comment by newbreedofgeek** [comment]
This is still an issue? @fuzzyduke

**Comment by fuzzyduke** [comment]
This is functional at this point. Resolved.
