### ISSUE TITLE
Royalty - When you reload the home page. NaN flashes before the actual royalty is shown

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#256]
Currently:
- Login via your wallet
- Reload the page and look at the claims UI
- It will flash NaN and then go to 0 or other royalty value

Expected:
- NaN is never flashed. like the other item (Rewards, Airdrops etc) it should show the  small spinner during load and then show 0 or actual number.

**Comment by damienen** [comment]
Solved
