### ISSUE TITLE
ITHEUM token creator royalties from marketplace trade needs to go into Claims Contract (Royalty) for creator can self-claim

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#258]
This is the main feature ticket that brings claims portal integration to the Data NFT marketplace.

```
As Bob (the Creator), when a secondary trade has happened in ITHEUM tokens and I have some creator royalty amount that needs to be paid out to me for the trade, the creator royalties should go to the Claims Contract → Royalties (Type 3) bucket); so I can self-claim my royalties via the Data DEX claims portal
```

Related tickets:
- https://github.com/Itheum/data-dex/issues/224
- https://github.com/Itheum/data-dex/issues/257
- https://github.com/Itheum/data-dex/issues/233

**Comment by newbreedofgeek** [comment]
Solved. Ready for testing.

**Comment by damienen** [comment]
@newbreedofgeek @bucurdavid Royalties still go to wallet. Tested

**Comment by damienen** [comment]
Tested. Works. Closing
