### ISSUE TITLE
Update Price in My Listed Data NFTs is broken

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#260]
In Data NFT marketplace -> My Listed Data NFTs,

Update Price is broken.. throws are JS error and goes to black screen

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
what kind of wallet did you use?
update price is working on my side and i have not changed marketplace.

**Comment by newbreedofgeek** [comment]
DeFi Wallet.. it kept going to blackscreen. 

Checked now and seems OK, but seems we have some unhandled error

**Comment by damienen** [comment]
Can't reproduce ATM. Will open if that's the case
