### ISSUE TITLE
Web Wallet - "View Data" just spins and no message to user

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#261]
- Web Wallet did not allow message signing so we did some check and show a message to the user saying that "web wallet not supported etc".. maybe the main web wallet was upgraded by Elrond team, now this message does not appear and it just spins.

Expected Behaviour:
- Check if new Web Wallet does support signatures and if so then allow Web Wallet for "View Data"
- If NOT, then show Ui message as before

**Comment by damienen** [comment]
Seems it is still not working, so will leave it as it is
