### ISSUE TITLE
Ui Update - For all Data NFT pages with "tiles", change the Skeleton Loading UI

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#262]
For :
- Data NFT Wallet
- Data NFT Marketplace (public marketplace and my data nfts tabs) 

Replace current horizontal loading skeleton with this style.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/743169/220054403-a938284e-4c4f-4ead-a612-3aeeaf6e3f6c.png">

Both the skeleton (loading state) and the Data NFT tiles (post loading state) need to be aligned in height, width, padding etc... so it's smooth and not jerky when we move from loading to loaded.

@damienen pls assign to anyone you feel fit.

**Comment by damienen** [comment]
For now the skeleton is not the same size as the tiles @Enciusan . Please change size

**Comment by damienen** [comment]
Checked. Looks fine. Closed
