### ISSUE TITLE
Data NFT Marketplace - jumping between pages has delay in loading content and shows old content 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#263]
Current Behaviour:

- Go to "public marketplace"
- Move between pages and look at the 'Data NFT tiles'
- The text content under the Image of each tile always has a delay in loading and rendering... until the correct content is fetched, it shows old content 

![image](https://user-images.githubusercontent.com/743169/220056877-b6e5a3fe-331a-45c4-8e9a-3fbd26d8d052.png)

Expected Behaviour:
- The loading skeletons appear until all new content is fetched and rendered. Images + text content

@damienen assigning to you, feel free to re-assign

**Comment by icegriffinguru** [comment]
@damienen , @newbreedofgeek  Fixed

**Comment by damienen** [comment]
Tested. Works. Closing
