### ISSUE TITLE
Listing NFT: upon entering more quantity than owned error message should show.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#266]
Description
1. When user enters more quantity than owned, there is no error message.
2. However upon moving focus the quantity is set to max owned.

![image](https://user-images.githubusercontent.com/121969933/220192805-ccd51024-1d88-4760-84fe-e869f523cde0.png)

**Comment by icegriffinguru** [comment]
@damienen , @newbreedofgeek 
Fixed

**Comment by damienen** [comment]
Works. Closing,
