### ISSUE TITLE
Listed NFT, Cosmetic: Creator address should be linked to the explorer along with the link icon.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#267]
Description:
The address of the creator should be hyperlinked along with the link icon. Currently only the link icon is hyperlinked.

![image](https://user-images.githubusercontent.com/121969933/220196054-d43a345a-57b1-4152-b93c-5c383071b850.png)

**Comment by newbreedofgeek** [comment]
Good idea.

We can do it as part of this ticket:
https://github.com/Itheum/data-dex/issues/310

But for styling, we should NOT show any underline on hover of address if possible

**Comment by fuzzyduke** [comment]
Also kindly place in a copy icon.

**Comment by damienen** [comment]
Solved. Closing.
