### ISSUE TITLE
Suggestion: A Buyer should see the address of the owner listing the NFT

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#270]
Description

Consider a scenario where an NFT is purchased by user B from user A. B then relists this NFT, User C buys this from User B.

Currently there is no visible trail, unless the user goes into the explorer.

Below is a listing of the NFT one from user A and one from user B. Question is, should there be any differentiator?

![image](https://user-images.githubusercontent.com/121969933/220206752-171b56e8-2bb0-4ab2-acf0-3d528d810587.png)

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
what kind of info shoud i add?
`Owner: erd12323221` like this?

**Comment by damienen** [comment]
The same way the the creator is shown (with hyperlink, too)

**Comment by newbreedofgeek** [comment]
Add it after Creator, in the same format and with the same link like Creator has.

**Comment by damienen** [comment]
Works. Closing

**Comment by fuzzyduke** [comment]
Verified. Fixed.

![image](https://user-images.githubusercontent.com/121969933/221539736-fcd348c0-f28a-4e83-9552-6d5f2593c39d.png)
