### ISSUE TITLE
Delisting popup requires to show total quantity listed and error message if quantity exceeds amount already listed.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#271]
Description:
Owner should not be able to delist more quantity that he has listed. There should be an error message. Also in the popup show the quantity in this listing, so the owner knows how many he has listed.

In the scenario below, the user had 16 listed NFTs, therefore if 19 is entered then the user should see an error message.

![image](https://user-images.githubusercontent.com/121969933/220208451-bd41d007-21e5-4486-86c6-1b1a9fa74991.png)

**Comment by newbreedofgeek** [comment]
Title is wrong.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/743169/220261694-d511b001-0a05-4179-9a8e-bfb1f65a76b7.png">


Should be "De-List Data NFTs from Marketplace"

**Comment by newbreedofgeek** [comment]
Under the "SFT Name" also should "available supply : XXX"

<img width="494" alt="image" src="https://user-images.githubusercontent.com/743169/220261945-f03553b0-551a-4b83-8395-48d6da28ced4.png">

**Comment by newbreedofgeek** [comment]
Also.. make this model header uniform as with the other model headers with SFT details (like above)

<img width="486" alt="image" src="https://user-images.githubusercontent.com/743169/220262519-7fa5e838-b759-4b90-b357-1042ec1250e3.png">

**Comment by damienen** [comment]
Solved.

**Comment by icegriffinguru** [comment]
Fixed. Waiting for merge

**Comment by damienen** [comment]
Tested. Works.
