### ISSUE TITLE
XPortal App Login - Styling Broken

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#273]
Seems Elrond has changed Maiar/XPortal App and no styling is broken.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/743169/220227590-8843ff1d-6fbf-4ea6-a67f-101873ffa78f.png">

**Comment by damienen** [comment]
Ledger styling was problematic, too. I solved that, too

**Comment by fuzzyduke** [comment]
Verified. Fixed.

![image](https://user-images.githubusercontent.com/121969933/221539189-ab721603-312d-478a-a4c1-8e75687b92d1.png)
