### ISSUE TITLE
Debounce the user clicks on Pagination

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#274]
When user is jumping between pages, put in a 2Second debounce.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/743169/220263551-955161ee-bca5-4185-b356-780e8c47a3b0.png">

**Comment by damienen** [comment]
While the debouncer is on, the button should be shown as disabled to avoid confusion.

@Enciusan

**Comment by damienen** [comment]
Checked. Works. Closed

**Comment by fuzzyduke** [comment]
Verified. fixed.

Button disabled within 2 second switch.

![image](https://user-images.githubusercontent.com/121969933/221583281-f22718f6-f641-4d5e-837a-f00f55f0ee35.png)
