### ISSUE TITLE
Data NFT Mint: Minting NFT with royalty of 7% lists with 7.000..1 %

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#294]
Description

1. Click on Trade Data
2. While creating a Data NFT for mint enter royalty amount of 7%.
3. Upon minting the Data NFT, royalty seen is 7.00....001%

![image](https://user-images.githubusercontent.com/121969933/220882321-340d56ab-f3c2-47ae-9398-a26d5140b54d.png)

**Comment by icegriffinguru** [comment]
Fixed. Waiting for merge

**Comment by damienen** [comment]
Tested. Works. Closing

**Comment by newbreedofgeek** [comment]
Just reopening as i'n curious why this specific SFT showed that a weird precision? How can we reproduce it? and what made it happen?

@damienen

**Comment by damienen** [comment]
Discussed this and clarified with Mark
