### ISSUE TITLE
Trade Data: URLs should be non editable while minting Data NFT from Data CATs.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#296]
Description:
While minting Data NFT from a Data CAT like OK pulse, the URLs should not be editable

![image](https://user-images.githubusercontent.com/121969933/220883753-c5dbe942-93c6-4241-8e34-de9de9a617a5.png)

**Comment by icegriffinguru** [comment]
@damienen 
this issue looks tricky. Is it needed?
"not editable While minting" means while pending transaction?

**Comment by damienen** [comment]
No. This is specifically when minting from the Data CAT. i.e that URL is auto completed and thus that text field should not be editable by user

**Comment by damienen** [comment]
Solved it myself. Closing.
