### ISSUE TITLE
Allow scroll click/open in new tab on multiple Data Dex features

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#302]
- [x] Navbar logo (getting to home page)
- [x] Navbar drop down list/burger menu
- [x] Maybe there are some other places where this would be viable?

**Comment by newbreedofgeek** [comment]
Same as

https://github.com/Itheum/data-dex/issues/318

**Comment by newbreedofgeek** [comment]
Don't worry so much about making the "menu items open in a new window" -- this is nice to have but not mandatory.

The main things is the Itheum Home Logo.. if this open in new window then that's enough.

@Enciusan @damienen

**Comment by damienen** [comment]
Solved myself. Closing.
