### ISSUE TITLE
Colors of disabled buttons is currently the same as the color of unselected buttons on the Data Dex

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#303]
**Issue Description: The color of the gayed out option in the data nft markeplace should be changed**

**Current Behaviour: When entering the data nft marketplace, you are able to switch between public marketplace and my listed data nfts. When one is selected, the other goes into a grayed otu color. This exact same color is used by the arrows on the right side when there are no more options left, suggesting that “public marketplace” option in this case is not valid to be clicked.**

**Expected Behaviour: Colors used should properly portray the usability of the feature**

**Comment by newbreedofgeek** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/743169/221460243-70e6253e-f078-4e3e-8be3-29ea715b05ed.png">

**Comment by newbreedofgeek** [comment]
No hurry to do this,

We 1st need to align on some UI states. The UI redesign will provide this.

**Comment by damienen** [comment]
Solved by redesign. Closing.
