### ISSUE TITLE
Legal Work : Waive Withdraw right

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#307]
Not an issue, but an idea for “Waive Withdraw right”,

[https://v2.akord.com/signup](https://v2.akord.com/signup)

[https://docs.akord.com/v/app-docs/legal/2022](https://docs.akord.com/v/app-docs/legal/2022)

Can you explain this to me, @newbreedofgeek ?

**Comment by newbreedofgeek** [comment]
@damienen 

It's part of the legal work we need to do. i.e. as part of GDPR, in terms of use... we need to cover this. It's becoming common in NFT projects now. Leave this with me

**Comment by newbreedofgeek** [comment]
This may not be needed. Moving it to future work

**Comment by damienen** [comment]
Not needed
