### ISSUE TITLE
On scroll click redirects in a new tab and disconnects wallet

### ISSUE THREAD

**Issue by Enciusan** [Itheum/data-dex#308]
Working on #302 I've found that on redirect with the desired link the wallet disconnects.

**Comment by damienen** [comment]
To be more precise, it prompts you to choose mainnet or devnet. After you choose one of them if you are logged in you are redirected to that one.

@newbreedofgeek should we change the behavior?

**Comment by newbreedofgeek** [comment]
@Enciusan @damienen 

This is related to the issue https://github.com/Itheum/data-dex/issues/331

Once that is fixed, then this can be closed. 

Basically, when opening a new window user should NOT be asked to select wallet to login again as their session is still active.

**Comment by damienen** [comment]
Solved! Closing!
