### ISSUE TITLE
Use ShortAddress component when "address shortening" in various pages

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#310]
For all these "address shortening" instances in various NFT views,

<img width="206" alt="image" src="https://user-images.githubusercontent.com/743169/221448734-9e8d19e7-7026-4c6a-b94f-f5ed2d4c6a1c.png">

use the  already available ShortAddress component :
https://github.com/Itheum/data-dex/blob/stg/src/App/AppMultiversX.js#L379

**Comment by damienen** [comment]
Solved, but I had to modify ShortAddress from p rendering to span rendering.
