### ISSUE TITLE
Rename NFT balance and max supply view labels.

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#313]
This screen is confusing.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/743169/221450489-a3f35278-55de-427a-ac2e-01d93e8c4f84.png">
In this instance if someone buys another NFT and lists it it should clearly communicate that with that listing there is only 1 available but the “total supply” should be shown. In this case I wanted to buy 2 but was puzzled why it didn't let me since 98 are available?

**Let's do it like this:**
(Seperate Lines)

Available: 1
Max Supply: 98
Royalty: 6%

**Comment by damienen** [comment]
I'd rather:

Listed:
Total supply:
Royalty:

**Comment by damienen** [comment]
Solved. Closing

**Comment by fuzzyduke** [comment]
Shown as per requirement. Verified, Fixed.

![image](https://user-images.githubusercontent.com/121969933/222228088-dffb35c1-8f67-4492-9c7b-e7fa4937c5ed.png)
