### ISSUE TITLE
Description Model getting cropped

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#314]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/743169/221451051-14161123-4ae2-44f7-9b93-76e18a9f2a60.png">

Pls check all models across all pages (wallet / marketplace etc)

**Comment by damienen** [comment]
Solved. Closing.

**Comment by fuzzyduke** [comment]
Verified, Fixed. 

No crop seen.

![image](https://user-images.githubusercontent.com/121969933/222227391-8cfbd234-a500-4a68-838a-739c776ea4f6.png)
