### ISSUE TITLE
When a transaction is active, most screens that need to show data are in "loading mode"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#315]
for eg:
Data NFT Wallet does not display anything if a existing Tx is taking place to buy an NFT, same for other Txs it doesn't load if any other Tx taking place

<img width="789" alt="image" src="https://user-images.githubusercontent.com/743169/221457270-547b27e7-51f5-4019-b9fc-c14eadfd9be7.png">

In the above, the user bought a Data NFT and as the TX was active... went to their wallet and saw the above.

Expected Behaviour:
If a TX is active, then screens like above should still be shown. Only think we need to prevent is "active" buttons, i.e. wait until the TX if complete before the user can submit a new TX.

**Comment by damienen** [comment]
I don't think that's actually true. Just tested, the only such screen seems to be the wallet and that is a coincidence as the devnet wallet NFT API call takes lots of time, not because the tx is loading.

**Comment by damienen** [comment]
@fuzzyduke can you try testing to see if the transactions are related to this?

**Comment by fuzzyduke** [comment]
@damienen It seems to be connected.

Tests performed.

1. Toggling between wallet and marketplace with low time interval. States are seen to be loaded within a second.
2. Procuring and then switching to Wallet. Multiple tests indicated that the wallet state cards are only loaded post-transaction completion.

Note: If during the transaction pages are toggled within marketplace then cards still continue to load correctly. 

![image](https://user-images.githubusercontent.com/121969933/222233972-54da6531-5ff7-4fe6-b15e-616f08ac8024.png)

**Comment by icegriffinguru** [comment]
@fuzzyduke 
can you show developer console on browser?

![image](https://user-images.githubusercontent.com/97042732/223676765-8b877c07-06ce-4b41-bd8c-0c044765192f.png)

Like the above
I always keep opening developer console while testing and it shows every single error.

**Comment by fuzzyduke** [comment]
@icegriffinguru kindly find the requested below.

![image](https://user-images.githubusercontent.com/121969933/223721778-61e46f2f-52a6-4de9-9714-6eefdc819d90.png)

**Comment by fuzzyduke** [comment]
@icegriffinguru kindly also find a loom, notice that the images load as the transaction completes.

https://www.loom.com/share/9d6034fdd8f3460f9c734d3624596e02

**Comment by icegriffinguru** [comment]
@Enciusan 
Is there a reason to add hasPendingTransaction check statement again on MyDataNFTsMultersX.tsx?
![image](https://user-image@damienen .githubusercontent.com/97042732/223735078-2e271cdd-b9fc-4011-9846-4f898729a8d8.png)

@damienen ,
we better remove hasPendingTransaction check statement, right?

**Comment by damienen** [comment]
Agree, @icegriffinguru . You can remove it

**Comment by damienen** [comment]
@icegriffinguru I solved this on my branch as it was just a one liner. Thanks for investigating.
