### ISSUE TITLE
Better messaging for "Data Stream URL must be a publicly accessible URL"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#316]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/743169/221458224-0478600e-f644-42b2-bf6b-105f80048b18.png">

**Comment by damienen** [comment]
@newbreedofgeek Did you self assign intentionally? Do you want to handle this?

**Comment by icegriffinguru** [comment]
@newbreedofgeek , @damienen 
http status of urls are checked and status messages are shown but we can show customized messages for selected status codes
i need status<->message pairs if it's not enough

http status code check
```
const checkUrlReturns200 = async (url) => {
  // check that URL returns 200 code
  try {
    const res = await axios.get(url);
    if (res.status === 200) {
      return {
        isSuccess: true,
        message: "",
      };
    } else {
      return {
        isSuccess: false,
        message: "Data Stream URL must be a publicly accessible url",
      };
    }
  } catch (err) {
    console.log('err', err);
    let message = err.message;

    if (err.response && err.response.status) {
      if (err.response.status === 404) {
        message = "Url is not found";
      } else {
        message = err.response.statusText;
      }
    }

    return {
      isSuccess: false,
      message,
    };
  }
};
```

**Comment by newbreedofgeek** [comment]
@icegriffinguru this this catch this CORs error? this is the error that's most thrown. e.g.

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/743169/223320225-23dbdc84-50ee-4d09-b122-d20bf60fe848.png">


Try this URL for testing: https://repository-images.githubusercontent.com/183429857/e68e990a-0343-4c67-9d20-1d16ef4c0717

Let's catch and show the following 3 error messages:
1. COR error as above: "Data Stream URL is hosted in a server that is preventing public access (CORS error)"
2. 404 Code : "Data Stream URL is not reachable (Status Code 404 received)" 
3. Non 200 Code : "Data Stream URL must be a publicly accessible url (Status Code XXX received)"
4. Other Errors : "Data Stream URL is not appropriate for minting into Data NFT (Unknown Error)"

For all the above errors, make sure to console.error(new Error('issue decsription ')) so our Sentry monitor can pick it up for reports.

try {
  // my logic
} catch (err) {
  console.erro(Error("Above user error message", { cause: err }));
}


CC @damienen

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
I have not found a solution to specify types of errors because some of them all return ERR_NETWORK but nothing specific.
I discussed with @damienen  on slack but have not found a solution yet.

**Comment by newbreedofgeek** [comment]
@damienen @icegriffinguru is this because we are only trying to use axios? did we try other clients like fetch or xmlhttprequest etc. They may provide more error data

**Comment by icegriffinguru** [comment]
Fixed except catching CORS error.
https://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq

**Comment by damienen** [comment]
Just checked. It is right. Browsers don't allow code to check for CORS errors. Other is fine.

Closing for now.
