### ISSUE TITLE
Update to De-List / De-List All UI buttons

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#320]
This design is too cluttered:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/743169/221461155-b84fd559-3a32-4b01-92ca-74d5ff9e5042.png">

Replace with this:
1. In the confirmation model, design it like this:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/743169/221461418-8d53516a-7c06-4f8d-bc3e-e8282098c9b8.png">

- "How many would you like to delist?" should be on one line
- When user clicks on "de-list all" it just sets the numeric input to the max supply (e.g. 5)
- If ONLY 1 is available, then DO NOT show the  "de-list all" button (as the numeric input only allows 1)
- Align the right border of the icon,  "de-list all" button and "cancel" button

On the main page, show these 2 buttons:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/743169/221461936-850196ee-4b4d-4831-a11b-0d1ea18e9fa8.png">

**Comment by icegriffinguru** [comment]
Fixed. Wating for merge

**Comment by fuzzyduke** [comment]
Verified. fixed.

Delisting some works. Delisting all works.

Min, Max conditions verified for Delist textbox.

![image](https://user-images.githubusercontent.com/121969933/222220843-f30412d2-ddc5-403b-8209-8310aaec990f.png)

![image](https://user-images.githubusercontent.com/121969933/222221193-6fe41d36-ac2d-4a1b-84a4-1fa1909c4e15.png)
