### ISSUE TITLE
Alert message to user if they try and mint again too soon

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#322]
We had a feature where:
- user mints a data NFT and tried to mint again soon after
- The smart contract has a config value that prevents this.
- we need to show a toast or popup to user that tell them that then need to wait XXX before trying again. (the XXX needs to match the smart contract timeout value in relation to current time)

We already had this feature... but it might be broken or not seen anymore after user testing did not see it.

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
It's still working.

![image](https://user-images.githubusercontent.com/97042732/221558799-7faff229-1e23-4e30-8fad-ab60e1b1efcb.png)

**Comment by damienen** [comment]
In the battle of yields this is not exactly what was picked up. We should have the mint button disabled until the person can mint again and probably a warning message under it that says this text.

This would probably be a better behavior and I think this was the picked up suggestion. What do you think, @newbreedofgeek ?

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
1. The error is listed as "Uptime Errors" which is not the case.
2. Let's change the text to: "You can mint another Data NFT-FT after XXX"
![image](https://user-images.githubusercontent.com/44813558/223245775-34258b07-46c2-459d-a856-b7820a61a91e.png)

**Comment by newbreedofgeek** [comment]
Yes, agree. It should not be under "Uptime Errors"

- It can be under a header called : "Alerts" (the same box and icon can be kept)
- Text can be "There is a time interval enforced between mints. You can mint your next Data NFT-FT after XXX"

@icegriffinguru @damienen

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Checked. Solved. Closing.
