### ISSUE TITLE
Show Trade, Wallet and Marketplace icons on header so user can jump to them fast

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#323]
These needs to be fixed
<img width="197" alt="image" src="https://user-images.githubusercontent.com/743169/221463752-26d0e4c0-8e73-4f4b-ad88-ae992b779f93.png">

And also moved to main header for faster access

**Comment by damienen** [comment]
Tested. Works. Closing

**Comment by fuzzyduke** [comment]
Verified. Fixed.

![image](https://user-images.githubusercontent.com/121969933/222220551-89cfb563-0e59-4568-8e31-4f4d062cd8dd.png)
