### ISSUE TITLE
description height not fixed to 2 lines

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#325]
The description heigh is still not fixed to two 2 lines. This needs to be happen in wallet and also marketplace.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/743169/221451221-ddcad3ac-c41d-4cf3-8477-0884f3902510.png">

**Comment by fuzzyduke** [comment]
As of build 309,  Below are the differences with 1 and 2 lines worth of description.

Marketplace
![image](https://user-images.githubusercontent.com/121969933/222220052-9e816e86-3657-4953-a0dc-a6ed4434f2a4.png)

Wallet
![image](https://user-images.githubusercontent.com/121969933/222219990-d8178c9f-a1f5-4067-962e-70b0181f4ec6.png)

**Comment by fuzzyduke** [comment]
Needs Alignment still, please check the previous comment.

**Comment by newbreedofgeek** [comment]
As @fuzzyduke comments, it need "fixed height" for support 2 lines. So if there are more than 3 lines we get "...".. or if there is less than 2 lines it still has the fixed height.

Title and Description need to also be aligned across all tiles.

**Comment by damienen** [comment]
![image](https://user-images.githubusercontent.com/44813558/224831703-6e186389-9e6e-4cd1-a17a-1af4767e21da.png)

These do not seem to be aligned
