### ISSUE TITLE
New Data NFT Standalone Details Page

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#326]
1. We need a new "standalone" Data NFT Details Page
2. "standalone" because the page will have to also work when the user is NOT logged in. So it needs to be a "component" that we can port to other static pages (not under the DappCORE container)
3. The page needs to be available under this route `/datanfts/marketplace/DATANFTFT2-71ac28-01`
4. Implement this design.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/743169/221497145-4a371849-932e-40c4-bbc9-e6ed05a88624.png">

5. The "Data NFT Activity" should be a component. This can be the same component used here - https://github.com/Itheum/data-dex/issues/177

**Comment by damienen** [comment]
Will probably create a MultiversX Explorer style table

**Comment by damienen** [comment]
Will wait for the final creation of the page until @Enciusan creates the "data nft upper card" so I can reuse it

**Comment by damienen** [comment]
Design is almost done. but some questions:
1. How are we going to have a "Connect MultiversX wallet" feature on this page if we want to use this page outside of DappProvider? Just a redirect to the login page?
2. Taking price for an NFT Identifier itself is currently impossible from our SC. Will probably be possible in the future using a deidcated backend service.
3. Same for the owner, we can't show the owner unless we query the SC (as the SC  is shown as owner on the blockchain).

**Comment by damienen** [comment]
I'll make it have a loading state and failed to load flag

**Comment by damienen** [comment]
Done. Closing.
