### ISSUE TITLE
Add creation, upload of JSON file to IPFS and link sending of it to SC (Data NFT IPFS Metadata File Support)

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#333]
To make sure the Data NFTs are more interoperable with 3rd party marketplaces, we need to make some updates to current solution to extend it to support IPFS metadata files.

We need to have external IPFS metadata file to aid in rendering

```
{
    "description": description,  
    "attributes": [
        {
            "trait_type": "Title",
            "value": title
        },
        {
            "trait_type": "Creator",
            "value": creator
        },
        {
            "trait_type": "Creation Time",
            "value": creation_time
        },
        {
            "trait_type": "Data Preview URL",
            "value": data_preview_url
        }
    ]
}
```
(above is just a template, detailed requirements will follow)

Currently blocked until implemented on SC level

**Comment by newbreedofgeek** [comment]
I've written up the details requirements for this in our Notion requirements doc for NFT Minter.. @damienen pls review the section with title "
<img width="428" alt="image" src="https://user-images.githubusercontent.com/743169/223317496-fe0d99b9-325c-473f-9c52-37843842f951.png">
"

Let's discuss today and finalize.

**Comment by newbreedofgeek** [comment]
1. Let's go with this :

```
{  
	"description": "SFT Dataset Title : SFT Data Set Description goes here",
  "attributes": [
    {
      "trait_type": "Dropshadow",
      "value": "RectanglePink"
    },
    {
      "trait_type": "Frame",
      "value": "RectangleGreen"
    },
    {
      "trait_type": "Base",
      "value": "Teal"
    },
    {
      "trait_type": "Shape",
      "value": "CylinderPink"
    },
    {
      "trait_type": "Badge",
      "value": "Bolt"
    },
    {
      "trait_type": "BG",
      "value": "Circuit"
    },
    {
      "trait_type": "Creator",
      "value": creator
    },
    {
      "trait_type": "Data Preview URL",
      "value": data_preview_url
    }
  ]
}

```

2. The Traits come in from the `generateNFTArt` as a CSV X-Nft-Traits header that the Data DEX JS code can parse.

3. We should group the image and metadata IPFS files as per common practice

**Comment by damienen** [comment]
Solved. Closing.
