### ISSUE TITLE
De-List button is not appearing in "My Listed Data NFTs"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#336]
Some Data NFT tiles do not have the "De-List" button

<img width="763" alt="image" src="https://user-images.githubusercontent.com/743169/223005244-67663f9f-f0a5-415a-ae2f-e3e82c083704.png">

- Might be some UI error on items with only 1 supply
- Once fixed, please check that the De-List confirmation popup also works well as per the De-List one vs multiple rules (i.e. shows De-List app button ONLY if available offer supply is more than 1)

**Comment by Enciusan** [comment]
I'll assign this to me if there is no problem cause I'm working on cards and I know the problem here.

**Comment by damienen** [comment]
Checked. Solved. Closing.
