### ISSUE TITLE
When SFTs are frozen in the marketplace, the UI needs to blur them out

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#338]
Current Behaviour:
- I froze this SFT
<img width="244" alt="image" src="https://user-images.githubusercontent.com/743169/223010388-cefe728f-f566-455b-85f6-5226000139b1.png">

- I froze it against the Marketplace contract address. https://devnet-explorer.multiversx.com/transactions/da508b02c6dc8dcdc734bafe843417b7d8c95370e6a66996835f4bb876165982#smart

- But the UI does not show the blurred out NFT box. The blurred out NFT box (i.e. Data NFT is frozen due to investigation...) should appear in both the "Public Marketplace" and "My Listed Data NFTs"

Expected Behaviour:
- In the wallet, we check for frozen SFTs and show this UI that needs to also be shown in the Marketplace pages 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/743169/223011041-6ff6492b-2e14-47d5-8568-f9a03057ad0c.png">

@damienen @bucurdavid Here we are freezing the NFT Marketplace Contract's SFT. In this case, can the anyone buy this SFT from the marketplace (i.e. the SFT moves from the marketplace to buyer's wallet)

**Comment by newbreedofgeek** [comment]
[Update]..I froze another SFT in the marketplace and then tried to "de-list" it and the SC then threw the error "Account is frozen for this esdt token" : https://devnet-explorer.multiversx.com/transactions/53ca0a23b58332166a32944e88c1c66c609701d9ed28614f2a4390be4472c045

Which means we can freeze marketplace.. so then we need to show the UI overlap as above original comment.

**Comment by icegriffinguru** [comment]
Current marketplace queries NFT minter SC to get frozen NFTs. I think we need to query from Elrond API for covering all cases.

**Comment by damienen** [comment]
I think the FE only checks whether the NFT itself is frozen. It should also check if an address is frozen @icegriffinguru

**Comment by damienen** [comment]
Hey, @icegriffinguru 

In order to get all the SFTs that are frozen from the smart contract side you should:
1. Use getSftsFreezedForAddress in order to get a vector of all the nonces that are frozen specifically for the SC address and the logged in address
2. Use getUserDataOut in order to get a vector of the frozen SFTs specifically for the user.
3. Use getUserDataOut to see if the user logged in is completely frozen themselves.


I think 2 and 3 are already happening (but please check to be safe). It's just case 1 that is not covered

**Comment by icegriffinguru** [comment]
Fixed. Need a check

**Comment by damienen** [comment]
Works. Closing

**Comment by newbreedofgeek** [comment]
Does not seem to work. @damienen @icegriffinguru 

----------
I just froze this NFT (it belonged to the marketplace):
https://devnet-explorer.multiversx.com/nfts/DATANFTFT2-71ac28-a0

<img width="256" alt="image" src="https://user-images.githubusercontent.com/743169/225554362-e650383a-9c0d-4571-afd3-dae63f8b166d.png">

Freeze TX: 
https://devnet-explorer.multiversx.com/transactions/823c70a787efa6f12f8083925f437b3d060df2a28d8e8dabd2dcb1c6f2539e6b#smart

BUT UI is not showing the blurred out view. 

It's not working in both the "Public Marketplace" and "My Data NFTS"

<img width="974" alt="image" src="https://user-images.githubusercontent.com/743169/225554822-1d4f4b47-21fb-4382-b418-18145d8ef82a.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/743169/225555381-dc9570e4-c211-4655-be86-63f715bdaec2.png">



----------

**Comment by damienen** [comment]
@icegriffinguru Please check

**Comment by icegriffinguru** [comment]
WTF, someone removed code checking freezed nonces 😅

**Comment by damienen** [comment]
Probably @enciusan when he merged, by mistake 😅

**Comment by icegriffinguru** [comment]
Fixed again. :)

**Comment by damienen** [comment]
Checked. Works. Good job! Closing
