### ISSUE TITLE
NFT Tiles are centered in desktop view

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#353]
Most likely related to this ticket - https://github.com/Itheum/data-dex/issues/334

NFT Tiles are centered in desktop view for wallet, marketplace.. (it should only be centered in mobile view)
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/743169/224580163-5958f03d-68b8-40e3-ae1e-1062adcbc968.png">

**Comment by damienen** [comment]
Yep, related to that. I'll solve this myself
