### ISSUE TITLE
SC should not check Data Steam URL length

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#360]
As it is encrypted it is often very long, but the unencrypted value is not so big. This change should probably be moved into the data marshal (it is also already implemented in FE). This causes issues such as these:

https://devnet-explorer.multiversx.com/transactions/3cbbecc15b949fa5887c80df9f7def55a428d71932109eb30ac3f7f5aab32aab#smart

The normal URL was around 150 chars, but the encrypted one is 320 so the mint fails.

**Comment by bucurdavid** [comment]
Fair enough for me

**Comment by bucurdavid** [comment]
[Implemented](https://github.com/Itheum/itheumcore-elrond-data-nft-minter/pull/41) #360

**Comment by damienen** [comment]
Cool. Closing.

**Comment by newbreedofgeek** [comment]
@damienen @bucurdavid SC change has removed the check for other URLs. This is wrong.

This should ONLY apply to Data Stream URL. reopening

**Comment by bucurdavid** [comment]
Changed only to Data Stream URL

**Comment by damienen** [comment]
@newbreedofgeek Please update SC

**Comment by damienen** [comment]
This has been solved. Closing

**Comment by fuzzyduke** [comment]
Issue with minting big URL seen again

![image](https://user-images.githubusercontent.com/121969933/228958664-aca28e5d-aa4f-445d-b6ea-d01de690f6d3.png)

**Comment by bucurdavid** [comment]
This is due to `title` or `description` being too long.

```rust
require!(title.len() <= 30, ERR_TOO_MANY_CHARS);
require!(description.len() <= 400, ERR_TOO_MANY_CHARS);
```
Current implementation: 

- **Title**: max `30 chars`
- **Description**:  max `400 chars`

Maybe FE didn't catch the title length. @damienen

**Comment by Enciusan** [comment]
Yes here is a problem in FE, the validation was for 50 max chars for title. I will fix the validator there.

**Comment by damienen** [comment]
Solved. Closing.
