### ISSUE TITLE
Data NFT Markectplace: Empty Page encountered, suspected timeout issue indication from console.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#363]
Description:
Empty pages encounter, console indicates timeout.

Steps to Produce
1. Browse to data marketplace.
2. Browse towards page 5 of 6, for instance.

![image](https://user-images.githubusercontent.com/121969933/224848196-ddb5e2c4-6483-4a2f-818e-01187157c4f5.png)

**Comment by damienen** [comment]
Waiting to contact a private gateway provider in order to stop hitting this issue on devnet...
