### ISSUE TITLE
Data NFT  Minting: Minting Datasets throws error.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#368]
Description:
Minting datasets throws error

Steps to Reproduce
1. Mint a datasets; Data CAT or normal.
2. Error encountered, explorer details in url Below

URL:
https://devnet-explorer.multiversx.com/transactions/dda90a7e495c3e4e13d6f7de888aca92a7975536e8adac82f1ded0c60e69b469

![image](https://user-images.githubusercontent.com/121969933/225237625-f4da37b1-6413-4dad-839c-b4fef22446aa.png)

**Comment by damienen** [comment]
SC upgraded. Works fine now. Closing!
