### ISSUE TITLE
Minting Form refactoring

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#372]
Packages to be used to efficientize how the minting form is checked, etc.:

https://www.npmjs.com/package/yup
https://www.npmjs.com/package/react-hook-form

The manual validation should be swapped to industry standard ones using a validationa schema. Moreover, the UI experience should change, you shouldn't get all the fields red with errors as soon as you touch the form.

It's pretty much a "get the UI/UX as smooth as possible" kind of task.

**Comment by icegriffinguru** [comment]
@Enciusan , if you update one form as an example, it will be great for me. 🙏

**Comment by Enciusan** [comment]
@icegriffinguru it's ok, i can do it sir.

**Comment by damienen** [comment]
Love the new form behavior! Good job! Closing.
