### ISSUE TITLE
Remove all hardcoded config that uses network IDs based logic etc

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#378]
There seems to be a lot of hardcoding of network ID values like "ED", e.g. 

<img width="495" alt="image" src="https://user-images.githubusercontent.com/743169/225824593-265d20ae-b97a-42a0-beaf-0d0ac816a581.png">

We need to go over the full app and remove all these hardcodes or we will have many gaps when we go to mainnet. `useChainMeta` should have the dynamic values you need.

**Comment by newbreedofgeek** [comment]
also.. need to look at other items in code that are MX "environment specific" logic and make sure it's dynamic and not hardcoded.

**Comment by icegriffinguru** [comment]
Removed "ED" hardcoded parts.
I think current env logic is unnecessarily complex.
What about removing redundant cross-chain logic?

![image](https://user-images.githubusercontent.com/97042732/226450901-fde07900-e24c-47f0-96e7-096b3cbfed32.png)

**Comment by damienen** [comment]
You can simplify it as long as you keep the contract addresses in one place only.

**Comment by icegriffinguru** [comment]
@damienen , I think @newbreedofgeek meant the above config part is redundant at the moment but we will need it in the future when we go for cross-chain.
I think we can leave it now. What do you think?

**Comment by damienen** [comment]
He said that most likely the other chains will be on a separate version of the data dex so we can remove the complicated logic

**Comment by icegriffinguru** [comment]
Okay. I wil let you check once I make an update on this issue. It can be disasterous. ;)

**Comment by icegriffinguru** [comment]
@damienen , It's better leave current multichain logic for future multichain update. We might need it in the future.

**Comment by damienen** [comment]
Fair enough
