### ISSUE TITLE
Data NFT details page: preview, procure, share button

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#383]
Description

1. Buttons missing in detail page; Procure, Preview.
2. From homepage, click on an NFT to procure under "Recent Data NFTs"

![image](https://user-images.githubusercontent.com/121969933/226475476-3e841621-20c3-4613-b28d-b2acdd6abe5b.png)

**Comment by damienen** [comment]
I will add the preview button and procure if user is logged in and we send the offer part

**Comment by damienen** [comment]
Also, need to change logic for listing price in case offer is given

**Comment by damienen** [comment]
Should also add a share button

**Comment by icegriffinguru** [comment]
Fixed.

**Comment by damienen** [comment]
Needs some tweaks. Procure button should only be shown if the user is logged in. It is currently shown in all cases.

Other stuff is good. Nice job!

**Comment by damienen** [comment]
Solved this myself as it was a quick fix. Will push once github's git operations will be back online

**Comment by damienen** [comment]
Pushed. Closing
