### ISSUE TITLE
Data NFT Details: Detail page should contain URL with Data NFT identifier.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#384]
Description
Upon clicking on the detail page of an NFT in the "Data NFT Marketplace" listing page, the below is encountered. Notice that the URL doesn't point to the instance of the Data NFT detail.

Steps to reproduce.
1. Browse the listing page of the Data NFT Marketplace.
2. Click on a Data NFT within the Public Marketplace(Procurable) to view its detail page.

Expected Behaviour
The Detail page URL should be available so users can revisit the detail page via direct URL

![image](https://user-images.githubusercontent.com/121969933/226476202-875f574c-0fd7-4da1-a25e-7cb9359c218c.png)

**Comment by damienen** [comment]
When the slider comes in we should change the URL to the deep link

**Comment by icegriffinguru** [comment]
Fixed on my branch. @damienen , @fuzzyduke

**Comment by damienen** [comment]
@icegriffinguru just checked, but when the drawer opens, the link doesn't change from 

datanfts/marketplace/market/0          to        dataNfts/marketplace/{nftId}/offer-{offerId}

**Comment by icegriffinguru** [comment]
I misunderstood the issue.
NFT detail should be an independent page if it needs an independent url.
Drawer is not the optimal solution, @damienen 
What about making a new page for NFT detail?

**Comment by damienen** [comment]
We already have a page with it. The reason for which we wanted the URL to be set to it temporarily while the drawer is open is so that people can easily copy paste the URL with the drawer open and send the link to friends

**Comment by icegriffinguru** [comment]
Do you think it's possible keeping marketplace page in background while showing drawer?

**Comment by damienen** [comment]
Tried researching some more. I don't think it's doable unless we either:
1. Have some funky workaround
2. Use some react routing bugs as features

I think neither is desirable.

Let's talk in the meeting about possibly closing this

**Comment by newbreedofgeek** [comment]
@damienen @icegriffinguru 

we need the drawer so user can browser and scan NFT details. Loading the details page in a new seperate page just breaks the whole UX and the user has to go back each time and the market+page is always in loadings state.


ideal behaviour:
- when the drawer opens, the URL changes to dataNfts/marketplace/{nftId}/offer-{offerId} from datanfts/marketplace/market/0(n)
- the url change should not "reload" the page. This UX is common and i've done it in the past but cant remember. see (https://stackoverflow.com/questions/57101831/react-router-how-do-i-update-the-url-without-causing-a-navigation-reload)
- when the user closes the drawer, you need to replace url back to datanfts/marketplace/market/0(n)

If you are 100% sure you can't do the above and have tried everything then:
- when the drawer opens, the URL changes to something like dataNfts/marketplace/?nftId={nftId}&offerId=offer-{offerId} to from datanfts/marketplace/market/0(n) 
- when the user closes the drawer, you need to replace url back to datanfts/marketplace/market/0(n)
- we now need a react router path to handle the redirect of dataNfts/marketplace/?nftId={nftId}&offerId=offer-{offerId} to dataNfts/marketplace/{nftId}/offer-{offerId}

**Comment by newbreedofgeek** [comment]
If this is taking too long... 
This again is lower priority compared to other critical feature work.

**Comment by icegriffinguru** [comment]
Fixed. Need to be checked.
