### ISSUE TITLE
Data NFT Detail page: There should be a way to reset clear filters.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#385]
Description

If a user selects a value for a filter, they are not able to clear the value to restore the original rows. This can be accommodated with an 'x' for each field. Currently, the users have to select the whole text within the field and delete it.

Expected Behaviour
1. User should be able to reset the HASH field to view all rows.

![image](https://user-images.githubusercontent.com/121969933/226477426-339b6586-c473-4709-b6a8-daae2edff5b5.png)

**Comment by damienen** [comment]
![image](https://user-images.githubusercontent.com/44813558/226530432-a29059f4-f244-456b-a3f3-260eac9f8f75.png)

**Comment by damienen** [comment]
You can just use backspace to delete what you have written?

**Comment by damienen** [comment]
Should add a clear all filters button

**Comment by damienen** [comment]
Solved. Closing
