### ISSUE TITLE
Add race conditions checks for chainMeta for all queries & api calls

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#389]

**Comment by damienen** [comment]
@icegriffinguru is this ready to be closed? If yes, feel free to close it when you see this comment.

I have checked and it looks good.

**Comment by icegriffinguru** [comment]
Fixed another part.

**Comment by damienen** [comment]
Seems to be better. Good job! Closing.

Note: Will reopen if will see the behavior
