### ISSUE TITLE
Description: Menu should be visible to non logged in users

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#393]
Description.

1. Menu items("Marketplace") doesn't show if a user is not logged in.

As per the latest change, a user should be able to browse the marketplace while not logged in. However, the menu is not available, if a user is not logged in.

![image](https://user-images.githubusercontent.com/121969933/226691276-176d6041-162b-4b27-9f18-e68279b9e6d4.png)

**Comment by newbreedofgeek** [comment]
We can show only the "Market" menu button on header if the user is NOT logged in.

This is a low priority ticket compared to some of the other more critical work.

@damienen

**Comment by damienen** [comment]
Made it available on desktop, but I need some ideas on how to do (or if I should do it) on mobile, too

**Comment by newbreedofgeek** [comment]
Desktop only is enough for now @damienen .. rest we can do later

**Comment by damienen** [comment]
Great
