### ISSUE TITLE
Data NFT Marketplace: Directly accessing marketplace listing URL shows broken cards.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#394]
Description:
1. Upon directly accessting Marketplace URL as a non logged in user below is seen on https://deploy-preview-382--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/my/0.

![image](https://user-images.githubusercontent.com/121969933/226692709-5a282cbf-fddf-4765-901d-bf7d0feb89eb.png)

This works however on https://deploy-preview-309--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/my/0

![image](https://user-images.githubusercontent.com/121969933/226693062-8fc10fcf-702c-4f13-86a2-e26c52d07c0e.png)

**Comment by damienen** [comment]
I can understand why this happens. I will monitor this depending what Mark responds at #393

**Comment by damienen** [comment]
Will close this and quote it on the refactoring issue on this
