### ISSUE TITLE
Data NFT Marketplace: Price per NFT doesnt show on latest build

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#395]
Description:
"Price per NFT" doesnt show on 
https://deploy-preview-382--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/0

![image](https://user-images.githubusercontent.com/121969933/226709074-2fcc5d05-67c0-4539-bfb0-29e4817d7a42.png)

However it does show on 

https://deploy-preview-309--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/0

![image](https://user-images.githubusercontent.com/121969933/226709385-225673bc-3fdd-4a6f-99c5-80aee12d7d3e.png)

**Comment by Enciusan** [comment]
I'll fix this

**Comment by icegriffinguru** [comment]
It's because my PR is not merged yet.

**Comment by damienen** [comment]
Can be closed as we have a resolution
