### ISSUE TITLE
Data NFT Wallet, PR 382: Card view lacks fields; token name, title, description

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#399]
Description:
Data NFT Wallet, PR 382: Card view lacks fields; token name, title, description

Launch the Wallet on https://deploy-preview-382--frosty-hermann-85ca4f.netlify.app/datanfts/wallet

![image](https://user-images.githubusercontent.com/121969933/227051173-fc48e2d8-1676-4f5b-8486-8f5ab2a3d44f.png)

**Comment by damienen** [comment]
I will close this as it's part of #297
