### ISSUE TITLE
"List to Marketplace" and "procure from marketplace" confirmation model UI/UX changes

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#401]
We need 2 UI updates. 

1. When a user wants to buy a NFT from the marketplace, current model looks like this.
<img width="463" alt="image" src="https://user-images.githubusercontent.com/743169/227178553-0e5ba11c-1a4d-4eb0-9a71-7f84a99bbfa1.png">

- NEW: Update it to make it look exactly like this (text changes, remove the red text etc):
<img width="468" alt="image" src="https://user-images.githubusercontent.com/743169/227178288-7db7a803-a633-4c76-b56f-a791b429ed74.png">

2. When a user wants to list an item on the marketplace from their wallet, the see the current model.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/743169/227178807-ba24d39a-6e1e-4e3c-b3fd-69776be6181e.png">

- NEW: Update it to make it look exactly like this (text changes, header changes etc):
<img width="464" alt="image" src="https://user-images.githubusercontent.com/743169/227178892-9b123042-655c-47cd-a4e8-71e6c82ccaad.png">

CC @fuzzyduke

**Comment by newbreedofgeek** [comment]
Once David completes the "List on marketplace Slippage" feature to smart contract, we can look at how to update the "List to Marketplace" model.

But for launch, we don't need any changes as we discussed.

**Comment by damienen** [comment]
Done. Closing!
