### ISSUE TITLE
Data Marketplace: components loading, lag sequence observed while moving between pages..

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#404]
Description:
1. Components lag seen while moving between pages. We see that for instance the images are placed in first and after a brief moment the data is then populated i.e., fields title/desc and so on.

https://deploy-preview-309--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/3

https://www.loom.com/share/2aaf7a9031ec4f048e295824194bd04f

![image](https://user-images.githubusercontent.com/121969933/227511455-d7b0e720-f3f4-4391-83d6-913fc91dbc54.png)

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Works as expected. Closing.
