### ISSUE TITLE
Clarification: Briefing on NFTs criteria in Recent Data NFTs section.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#405]
Clarification:
Please brief on the mechanism/criteria to list NFTs in "Recent Data NFTs"

![image](https://user-images.githubusercontent.com/121969933/227515608-4a215200-d8a8-45cd-88c0-ba71213f393a.png)

**Comment by damienen** [comment]
There is no exact criteria for now. In principle, the most recently listed will be shown, but it's not 100% the case.

This is due to some indexing we are doing in the SC @fuzzyduke
