### ISSUE TITLE
Data NFT Marketplace: Light mode Review

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#407]
Clarification/Reivew:
Readability and view of elements of for instance "Frozen NFTs" in **light mode** has to be done.
Please consider font sizes of the smaller sizes of text; "Token name", "creation time", "fee per NFT", "How many to procure".

![image](https://user-images.githubusercontent.com/121969933/227531016-a9249534-00e4-4800-a4af-42e0bde639f6.png)

**Comment by Enciusan** [comment]
I've resolved the freeze text color problem but i don't really understand what you mean by:
Please consider font sizes of the smaller sizes of text; "Token name", "creation time", "fee per NFT", "How many to procure".

**Comment by fuzzyduke** [comment]
Was of the opinion readability of those fields mentioned required review as they were small and the contrast with the background made it slightly tougher to read.

**Comment by Enciusan** [comment]
@newbreedofgeek @fuzzyduke I'll leave you attached in here a photo, please confirm if everything looks good.
![image](https://user-images.githubusercontent.com/92076681/227791333-54610473-415f-4de1-ac34-02985db7e35c.png)

**Comment by newbreedofgeek** [comment]
This is good enough and all that's needed.. 

One improvement you can do @Enciusan in lite mode.. make the grey BG a bit lighter as well so it suits the light mode better.

Of course, any changes made to light mode needs to toggle back in dark mode. Once confirmed, ticket can be closed.

@fuzzyduke

**Comment by damienen** [comment]
Looks good! Good job! Closing
