### ISSUE TITLE
Buying Data NFT from details page.. does not reflect supply changes.

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#412]
Current Behaviour:
1. I bought this Data NFT from the details page. it only had 1 Supply in marketplace.
https://deploy-preview-309--frosty-hermann-85ca4f.netlify.app/dataNfts/marketplace/DATANFTFT2-71ac28-05/offer-57?

<img width="767" alt="image" src="https://user-images.githubusercontent.com/743169/227834143-b27c3312-494b-4613-9ac5-0410e40cc4c0.png">

2. After I bought it, the details page did not refresh to indicate that supply has dropped. As only 1 was available and it was sold, i tried to but it again and it failed (which is accurate)
<img width="938" alt="image" src="https://user-images.githubusercontent.com/743169/227834279-1baa2119-f3de-4a80-a67d-8fe4d8fa67a2.png">

Expected Behaviour:
1. In details page, after someone buys supply. This section needs to update to reflect the supply changes.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/743169/227834357-b1dae0d3-4298-4caa-b61c-469774f146d1.png">

2. IF the supply drop from 1 -> 0, Just make "Listed: 0" and "disable" the following textbox and button.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/743169/227834504-ab6a676a-ceb4-4edb-8542-ca339d60e8fa.png">

3. ** These changes needs to be fixed in both the standalone details page AND the drawer page

**Comment by damienen** [comment]
Solved. Closing.
