### ISSUE TITLE
Data NFT Marketplace: Preview Data not functional in Data NFT Detail page(Marketplace)

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#414]
Description:
Preview data doesn't current work in the NFT detail page(Marketplace). Upon invoking preview data a new blank tab is seen.

![image](https://user-images.githubusercontent.com/121969933/227855143-1027c66b-6f7e-46b4-8efd-6bfcd8adc86b.png)

**Comment by damienen** [comment]
Duplicate of #409
