### ISSUE TITLE
Data NFT Detail view: Negative Value permitted for Pagination in Data NFT Activity Section.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#415]
Description
Data NFT detail view allows negative values for pages.

Steps to reproduce
1. Go to Marketplace
2. Click on the image of an item to view its details
3. Modify the pages in the "Data NFT Activity" section, toggle it to negative amounts.

![image](https://user-images.githubusercontent.com/121969933/227899832-565f8c74-ae01-4c6e-80c7-89e2fd783fc7.png)

**Comment by damienen** [comment]
Solved. Closing.
