### ISSUE TITLE
Data NFT Detail Page: Data NFT Market Detail view shows only "addOffer" under Data NFT activity.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#416]
Description

Data NFT Activity should show blockchain interactions with respect to the Data NFT. Currently only "addOffer" is seen.

For instance purchase actions, price update actions and so on, are not seen under the activity section.

![image](https://user-images.githubusercontent.com/121969933/227902091-bc892efb-f7ed-4a77-b6eb-16df0ce95c89.png)

**Comment by damienen** [comment]
You are right. Just had a look over the MX API and ideally we would need a backend server and database in order to solve this

**Comment by newbreedofgeek** [comment]
Ideally.. we show "addOffer" and "acceptOffer".. and we can limit to last 50 of these TX (due to performance issues)... until we have a web2 backend

**Comment by damienen** [comment]
I will have to wait for the new SC implementation for this, but I've got an idea on it.

**Comment by damienen** [comment]
SC is upgraded so work can start on this. This is more of an algorithmics problem and I will pass it to @bucurdavid so I can prioritize other stuff.

The way the transactions should be fetched is this:
1. Get last 10K txs of the marketplace via API
3. At each TX, decode the data field from base64
4. At each tx, hex decode the data field
5. At each tx, if it's a listing, check if the sent NFT to the SC is the desired one. If yes, save the data needed for the tx to be displayed in the details table in an array. This must be done without any additional API calls. (You can infer the listing id by counting the number of listings made)
6. At each tx, if it's not a listing, check whether the ID at which the user buys/changes the listing corresponds to one of the IDs which are saved as related to this NFT. If yes, save the data needed to display the tx in the table of txs.

The end result of the created function (or functions) should be an array of txs which can be passed as a prop to the table from TokenDetailsTable.

**Comment by fuzzyduke** [comment]
Verified, Fixed. #485 

methods: addoffer, changeOfferPrice, acceptoffer, burn

![image](https://user-images.githubusercontent.com/121969933/230099126-cac2e7a4-6de3-4e71-ae80-2fdbad709fd2.png)
