### ISSUE TITLE
Marketplace Data NFT Listing: Images within the listing page failed to load.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#419]
Description
1. This was seen on PR 309 and 411. Upon loading the marketplace some cards fail to load the image.
2. Currently this was seen with a non logged in user, however, it is not conclusive that this is a factor.

Not Reproduceable

![image](https://user-images.githubusercontent.com/121969933/228035607-bc65beec-b32c-466c-9928-6c4e0a9d65b9.png)

**Comment by damienen** [comment]
We can use this to have a fallback image in case images don't load:
https://stackoverflow.com/questions/34097560/react-js-replace-img-src-onerror

**Comment by damienen** [comment]
https://media.elrond.com/nfts/thumbnail/default.png

This is the image we should use, saved locally, though.
