### ISSUE TITLE
Data NFT Detail Page: Procure Button should not be available for non logged in users. PR 411

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#420]
Description
1. In the Data NFT Detail page(Marketplace listing), If a user is not logged in they should not be able to see the Procure button.

Noticed on PR 411

![image](https://user-images.githubusercontent.com/121969933/228038250-983e944a-9407-498e-a881-f9c6a84bc16f.png)

**Comment by damienen** [comment]
Not present in newer builds. Closing.
