### ISSUE TITLE
For "description", remove the "markdown support" label. BUT support URLs

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#422]
In this form:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/743169/228134577-f4d08f45-b8d6-4866-9028-25e1fef79354.png">

Remove this " Markdown (MD) allowed."

"URL allowed." should be "URLs allowed."

AND if a user pastes a URL, in the wallet, marketplace or details page.. use some local javascript to render the LINK as clickable (check if possible)

**Comment by damienen** [comment]
Something's not right. If I input this description:
![image](https://user-images.githubusercontent.com/44813558/228684701-384eccc2-3417-4700-8143-90b25f2df4ac.png)
It is saved like this on IPFS ^

But it is displayed like this in the card:
![image](https://user-images.githubusercontent.com/44813558/228684757-73d4365d-bf7b-4be7-b1d6-7f10d0fc25ab.png)

The link seems to be moved at the end of the description string.

**Comment by fuzzyduke** [comment]
Verified on 474, pending merged test.

**Comment by damienen** [comment]
Solved. Closing.
