### ISSUE TITLE
Data NFT Detail view: "How Many to Procure" has to have a default value of 1, similar to listing page.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#427]
Description

Data NFT Detail view: "How Many to Procure" has to have a default value of 1, similar to listing page, and not the max amount of Data NFT listed.

![image](https://user-images.githubusercontent.com/121969933/228381715-27c8df72-cf2b-4e67-8de6-b678166565e4.png)

**Comment by icegriffinguru** [comment]
@damienen 
I made it as max for UX. That's what we did before.
That's better UX, isn't it?
???

**Comment by damienen** [comment]
Depends.

Is the average user going to most likely procure 1 NFT or max supply? Here, most likely one, I'd say.

For burning, though (where this was also implemented) most likely max supply or close to max supply burn.

So here, default 1 is probably better

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
All good. Closing.
