### ISSUE TITLE
NFT Detail View, Data NFT Activity: User can invoke page outside bounds.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#428]
Description

Data NFT Detail View: Paging is faulty Under "Data Activity NFT". A user can  exceed the pages available.

![image](https://user-images.githubusercontent.com/121969933/228383526-80d2c293-5a14-47a9-8efc-574c62a9b368.png)

**Comment by damienen** [comment]
Solved. Page changing is now onBlur, not onChange
