### ISSUE TITLE
Details Page Image needs to be fixed and Centered

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#430]
We need to fix and center the image in the details page / model.

e.g image is growing and shrinking based on text content.
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/dataNfts/marketplace/DATANFTFT2-71ac28-a5/offer-41

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/743169/228421706-66307092-2a31-4907-9081-bf9759e0c283.png">

here is another link:
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/dataNfts/marketplace/DATANFTFT2-71ac28-a7/offer-undefined

Expected Behaviour:
- Fix the image container and "center" the image like so:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/743169/228422015-91be01a2-0a3c-4f8a-a4a4-354595d9b111.png">

**Comment by damienen** [comment]
Solved. Closing.
