### ISSUE TITLE
NFT Boxes UI Alignment is broken after last fix

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#433]
Wallet and Marketplace has this weird alognment.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/743169/228422737-396ee392-5b51-4202-94c2-10082197417d.png">

Can you look into Simple Grid so we are aligned across all grids

**Comment by newbreedofgeek** [comment]
This is also wrong. The spacing needs to be uniform

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/743169/228428387-6ef832bd-a376-47e2-8cfa-7e5907e21eb6.png">

**Comment by newbreedofgeek** [comment]
It needs to be "clean and uniform" like this:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/743169/228428468-2f9d8a7c-50e0-4638-85c5-2252cee78819.png">

The solution i'm almost certain is Simple Grid

**Comment by damienen** [comment]
Simple grid is planned to be implemented. I am aware the spacing is not good right now. The other issue about this is still WIP so I will close this one as suplicate
