### ISSUE TITLE
Check and verify 3rd party NFT marketplace UI view compatibility 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#434]
As discussed in weekly meeting, now that we have compatible NFT metadata format. Let's explore if the NFTs appear on 3rd party marketplaces correctly.

identify any gaps if there are any and document them.

**Comment by damienen** [comment]
Good news: FrameIt shows our attributes as expected. Check here: https://test.frameit.gg/marketplace/nft/DATANFTFT2-71ac28-e1
Bad news: XOXNO does not show our attributes as expected. Check here: https://dev.xoxno.com/nft/DATANFTFT2-71ac28-e1

We would have to kindly ask for XOXNO to check for the attributes on the second assets URI

**Comment by damienen** [comment]
Solved. Closing.

Attributes appear in all marketplaces mow
