### ISSUE TITLE
PR 436, Data NFT Mint form; Field behavior needs to be rectified

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#437]
Description:

Fields below need to be ammended

Token Name: User can enter space as a character, which throws an input field validation error. Earlier the box was not allowing space which made it intuitive for the user.
   Expected behaviour: User should not be able to enter space in the form.
![image](https://user-images.githubusercontent.com/121969933/228605735-4eab54cb-9ab2-4716-aede-b055dbabd31f.png)

Dataset Title: If a User inputs a space they are prompted with error.
   Expected Behaviour: User should be able to enter space.
![image](https://user-images.githubusercontent.com/121969933/228605873-75a76111-418e-4a63-9f6b-e526f1d202c4.png)

**Comment by damienen** [comment]
Works as expected now. Closing.
