### ISSUE TITLE
Form validation issue : does not check if data steam and preview are same anymore

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#440]
There used to be a check to make sure that data stream url and data preview url were same.. this error message is no longer there

<img width="647" alt="image" src="https://user-images.githubusercontent.com/743169/228801119-68d6a84d-fbac-4b76-9443-1786ea27ed46.png">

**Comment by fuzzyduke** [comment]
Verified on 474, pending merged test.

**Comment by damienen** [comment]
Solved. Closing
