### ISSUE TITLE
Form validation issue: non 200 error codes no longer showing

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#441]
The validation that makes sure data stream urls and data preview urls are "public".. no longer appears.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/743169/228801685-138e21f6-041e-4948-9702-2ac1e70df044.png">

**Comment by fuzzyduke** [comment]
474 -- (Unknown error)

![image](https://user-images.githubusercontent.com/121969933/229628503-b64f6c12-1493-4f7c-acc7-1f090dd8563d.png)

**Comment by damienen** [comment]
This is the expected behavior for possible CORS error

**Comment by damienen** [comment]
Solved. Closing.
