### ISSUE TITLE
After new minter contract deployed... UI form is broken.

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#443]
After deploying new minter smart contract to devnet, 

Minter form is throwing a getUserDataOut error
![image](https://user-images.githubusercontent.com/743169/228806747-36be118f-8b02-440d-8e5b-94fb6e7bc143.png)

PR for new minter contract address is here: https://github.com/Itheum/data-dex/pull/442

PS: I'm not unpaused contract yet as I want to check if the form shows correct validation errors for "paused" and "not whitelisted"

**Comment by damienen** [comment]
Solved. Closing.
