### ISSUE TITLE
Trade NFT, Minting form: 

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#447]
Description
Mint and Trade NFT: Button disabled entering all fields with all valid field validations.

Steps to Reproduce
1. Load Test Data
2. Select "Trade Program Data" for Data CAT; OkPulse
3. Enter all fields without validation violations.

Expected Result
Mint and Trade NFT should be enabled but it is not.

![image](https://user-images.githubusercontent.com/121969933/228933864-43ce0637-c75a-4556-b2b6-eed171cee5b4.png)

**Comment by damienen** [comment]
@fuzzyduke can you still reproduce this?

**Comment by fuzzyduke** [comment]
This seems to be because of the special character ":", dint catch this at the time. There needs to be a validation message over that field however.

**Comment by damienen** [comment]
Closing with reference in another issue
