### ISSUE TITLE
Minting Form: Validation on field fails for alphanumeric entries.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#449]
Description:
In the minter form, validation should be set for fields for their input type. Currently character such as "-" throws no error

![image](https://user-images.githubusercontent.com/121969933/228957353-cde0943e-3dbb-474d-a0e7-9d02361fc55f.png)

**Comment by Enciusan** [comment]
Yes cause "-" is not alphanumeric but sure i can add an exception for "-" character. On it

**Comment by fuzzyduke** [comment]
There was no error message when "-" was added. No way for the user to know why they cannot submit. Can keep the restriction on the character just need the message to show.

**Comment by fuzzyduke** [comment]
Verified on 474, pending merged test.

**Comment by damienen** [comment]
Solved. Closing.
