### ISSUE TITLE
Reseller should see creator royalties deducted

### ISSUE THREAD

**Issue by bucurdavid** [Itheum/data-dex#450]
If a reseller list a purchased data NFT, it should see in this view the amount of royalties deducted for the creator.
i.e 10% royalties in this case
Royalties: 20 ITHEUM
You will receive: 176 ITHEUM (200 ITHEUM - 4 ITHEUM - 20 ITHEUM)

<img width="512" alt="image" src="https://user-images.githubusercontent.com/46384319/228958407-1524f780-79a0-48ae-8938-c4bcaef17f11.png">

**Comment by damienen** [comment]
Solved. Closing.
