### ISSUE TITLE
Data NFT Marketplace: Post minting a Data NFT and listing, the Data NFT is not observed in Marketplace.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#451]
Description:
1. Mint Data NFT.
2. From the wallet list the NFT
3. Attempt to navigate to marketplace.

Listed NFT is not seen in the marketplace.

![image](https://user-images.githubusercontent.com/121969933/228961009-166d1de8-9601-44df-aed4-aedb62b4d98c.png)

**Comment by damienen** [comment]
Solved on my branch. Merging soon. Closing
