### ISSUE TITLE
Unexpected behavior when switching between the "Listed" and "Marketplace" 

### ISSUE THREAD

**Issue by bucurdavid** [Itheum/data-dex#453]
Keep in mind that the second offer is mine, which is displayed correctly. 
Some weird behavior when toggling between `Listed` and `Marketplace`. 
Refreshing fixes it.

https://user-images.githubusercontent.com/46384319/229077918-590c7516-915e-4aeb-8646-2bf3c088704d.mov

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Solved. Closing.
