### ISSUE TITLE
Data NFT Wallet, invoke Listing: Error seen on listing free dataset.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#454]
**Description**:
Listing an NFT from the wallet with free pricing raises error.

**Steps to Reproduce:**
1. Browse to wallet.
2. Input quantity of 11.
3. In "Listing price for each" select current amount and hit backspace to remove all numbers.
4. List the Dataset

**Result**
3a. Upon hitting backspace "Nan" is seen
![image](https://user-images.githubusercontent.com/121969933/229079629-aba2acb1-0bbb-4acf-ae0c-140704d5d014.png)

4. Error is encountered as shown below.

![image](https://user-images.githubusercontent.com/121969933/229080275-a4c77022-be40-4a2a-8289-587842d1d09a.png)

https://devnet-explorer.multiversx.com/transactions/6578f37848a54d3a919d7ac4533dc0e241f4d03072989c49caf2773b9bfd1570
![image](https://user-images.githubusercontent.com/121969933/229078117-2f6aba0e-a91f-4b9c-8f15-8eb20cc26315.png)

**Expected result.**
1. Nan should not be seen on full backspace, should show as 0.
2. Error should not be seen on free mint and Data NFT should be seen in Marketplace.

**Comment by damienen** [comment]
Solved. Closing.
