### ISSUE TITLE
Data NFT Wallet: Detail page is not available for Data NFTs in Wallet.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#455]
Description:
Data NFT Detail page needs to be available in the Wallet for Data NFTs.

**Comment by damienen** [comment]
@newbreedofgeek does it?

**Comment by damienen** [comment]
Almost good. but I should be able to actually open the details page if I click the NFT image, like on the market

**Comment by damienen** [comment]
Solved. Closing.
