### ISSUE TITLE
Data NFT details page needs to show full details

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#456]
Data NFT Details Page Doesn't show fully entered description

![image](https://user-images.githubusercontent.com/121969933/229082578-a8b758da-1f90-4341-94e3-7e9f9db26240.png)

https://devnet-explorer.multiversx.com/nfts/DATANFTFT3-d0978e-06

**Comment by fuzzyduke** [comment]
Please note that the formatting of the details for both the listing popup distorted. When the details were entered there was certain items put on next line. However next line is not observed in both listing popup or details slide-in.

![image](https://user-images.githubusercontent.com/121969933/229083487-f200a3e1-e48e-44cd-bdeb-2ac25f4123ae.png)

**Comment by damienen** [comment]
Solved. Closing.
