### ISSUE TITLE
Data NFT Details Page doesnt reflect correct values for fields "Listed" and "Fee per NFT"

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#457]
Description:

Data NFT Details Page doesnt reflect correct values for fields "Listed" and "Fee per NFT", on the left side you can see the listing tile shows 

Listed: 1
Total supply: 20
Royalty: 55%

![image](https://user-images.githubusercontent.com/121969933/229084159-ab16e092-db51-41d4-a0cf-faa60d38a570.png)

**Comment by damienen** [comment]
Solved. Closing.
