### ISSUE TITLE
Data NFT Detail drawer should close if user clicks outside the details area on the page.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#458]
Description

The slide-in should disapear if the user clicks on the non focused area on the left. Currently the details page only closes if the close button is invoked.

![image](https://user-images.githubusercontent.com/121969933/229084832-6c3248ae-af67-4890-a483-beed23679140.png)

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Almos good. but I should be able to actually open the details page if I click the NFT image, like on the market

**Comment by damienen** [comment]
Works. Closing.
