### ISSUE TITLE
NFT Details Page:  suggestion to have the field autovalidate in some cases 

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#459]
Description
As the user increases the character count the validation error remains. If the users crosses the minimum characters, the error should dynamically disappear as the validation criteria has been met.

![image](https://user-images.githubusercontent.com/121969933/229085280-0a2c354e-9f20-42b2-8cf5-10c157f81d86.png)

**Comment by damienen** [comment]
I'd rather leave it be like this, so only when the user is done it is checked
