### ISSUE TITLE
Data NFT Wallet: Delisting or updating price doesnt work.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#462]
Description:
1. Delisting NFTs or updating price causes error

https://devnet-explorer.multiversx.com/transactions/72e71ec4236fe1e379f3e76a1c67c404363cb4ab196702f95ec153cd6528dc52

https://devnet-explorer.multiversx.com/transactions/37d06f9b4da29bea0bf6732ebaad99bb8f6b29f359ec67a55ee354954417d8e1
![image](https://user-images.githubusercontent.com/121969933/229111393-7706d1b6-c26d-42a2-9213-95b642d305e8.png)

**Comment by damienen** [comment]
Solved. Closing.
