### ISSUE TITLE
UI Polish - Minter Form

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#465]
- We need to align the page to the new design.
- Needs to be pixel perfect, people will judge the whole data dex based on UI 
- Make it look good on Mobile, Tablet and Desktop
- Ask on Slack for Figma link

**Comment by newbreedofgeek** [comment]
Still pending...

**Comment by damienen** [comment]
- [ ] Error messages are overlapping text

**Comment by damienen** [comment]
Solved. Closing
