### ISSUE TITLE
Description: Delisting NFTs throws error.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#469]
Description: Issue seen while delisting an item from the marketplace. Delist count of 3 was requested from a total of 5 items.

https://devnet-explorer.multiversx.com/transactions/10b48f4226105f6a4b32b1af06875345f6a1f49760108ae09bbef82f13041152

![image](https://user-images.githubusercontent.com/121969933/229499889-53fec265-48eb-4914-bf19-f55b6f89c9a6.png)

![image](https://user-images.githubusercontent.com/121969933/229499760-42a48704-a891-44d2-b23c-b9c6d8b650d4.png)

**Comment by damienen** [comment]
Solved. Closing.
