### ISSUE TITLE
Data NFT Marketplace: Data NFT Purchase fails in specific scenario.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#473]
Description

Purchase fails in scenario, where a third entity C buys from an entity B(Data NFT originally created by A with 55% royalties)

https://devnet-explorer.multiversx.com/transactions/f9b38f81fbdbc9e15fe839681e260ce50a98e01df42a60c03eb6ea987302802d

Data NFT
https://devnet-explorer.multiversx.com/nfts/DATANFTFT3-d0978e-09

Creator A
erd1ttexfnluaky2zcqr2xljgrth5580j6rx2fya2mx7mruamfvfxxjske3tea

Owner B
erd1xz6yx958ujw800hwrz50ejldp02rejzzzlyvptjj9w4sut3v4wesgcewx2

Buyer C
erd1xz6yx958ujw800hwrz50ejldp02rejzzzlyvptjj9w4sut3v4wesgcewx2

1. B buys a Data NFT from A.
2. B lists data NFT for 999.
3. C tries to buy the listed NFT

Expected result
3a. User C acquires the data NFT and sees it in their wallet.
3b. Fees is split to A,B and the DAO contract.

![image](https://user-images.githubusercontent.com/121969933/229538530-18e880a1-0950-4195-bbc4-7a03429b7d18.png)

**Comment by damienen** [comment]
This is because the marketplace SC is not whitelisted in the claims contract.

**Comment by damienen** [comment]
Solved. Closing.
