### ISSUE TITLE
Data NFT Marketplace Detail page: URLs in Detail page are not hyperlinked

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#476]
Description

NFT Detail Page: URL is not hyperlinked in detail page.

![image](https://user-images.githubusercontent.com/121969933/229624204-23cdc871-5fdb-4ef1-a2e8-a96c0f4cce9b.png)

**Comment by newbreedofgeek** [comment]
Pls test

**Comment by fuzzyduke** [comment]
Verified, fixed. #482
