### ISSUE TITLE
Marketplace does not show deterministic results when switching page

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#484]
Setp 1: Go to marketplace
Step 2: Go to second page

You will notive some NFTs.

Step 3: Refresh page

You will notice some other NFTs listed, other prices, etc.

UPDATE: It seems it's just the price that does not get updated correctly? Not entirely sure.

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
Verified. Price remains the same after refresh.

**Comment by icegriffinguru** [comment]
@fuzzyduke 
my pull request is merged
can you check it again?
