### ISSUE TITLE
Description Going to last page of Marketplace and getting back to first page throws 400.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#490]
Description Going to last page of Marketplace and getting back to first page throws 400.

Steps:
1. Browse to the marketplace.
2.  On paging click >>
3. Once you reach the final page click <<

Below is encounter

![image](https://user-images.githubusercontent.com/121969933/230089015-9b1ca421-7608-4f7d-bada-1f4c05c735f1.png)

**Comment by damienen** [comment]
I am not able to reproduce this

**Comment by fuzzyduke** [comment]
Cannot reproduce. Closing.
