### ISSUE TITLE
Faucet called within a short interval throws error.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#491]
Description: Faucet called within a short interval throws error. FE should align adequate message.

https://devnet-explorer.multiversx.com/transactions/90005070579d67ad7a78214b182c3529736e61d51e7c0e6e398bc8803b21a091

![image](https://user-images.githubusercontent.com/121969933/230105940-36557a67-be28-4964-9cc3-2cd9dd465e7f.png)

**Comment by damienen** [comment]
Change text to "Send me 1000 ITHEUM"

**Comment by damienen** [comment]
Solved. Closing
