### ISSUE TITLE
Data NFT marketplace: Error encountered on delisting NFT. PR #429 

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#496]
Description

Error encountered on delisting NFT. PR #429 

Steps
1. Browse to My Listed Data NFTs
2. Click De-list NFt.
3. Within popup select De-list all.
4. Proceed.

https://devnet-explorer.multiversx.com/transactions/3442eee40d1426304df8fbc29c69cd278c113a8952d288538a337501c0d1b3c4

![image](https://user-images.githubusercontent.com/121969933/230396416-bf6ce552-c50b-4403-ad21-32698b97ea1e.png)

**Comment by damienen** [comment]
Will reopen if we can reproduce
