### ISSUE TITLE
Singular spelling mismatch

### ISSUE THREAD

**Issue by bucurdavid** [Itheum/data-dex#497]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/46384319/230396334-cb3b7163-0b0a-4219-b4d4-63688ae81b86.png">

**Comment by bucurdavid** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/46384319/230574765-f29151e9-fbb6-4c74-bcd5-a5ac1830e90b.png">

**Comment by damienen** [comment]
Solved. Closing.
