### ISSUE TITLE
Wallet price gets NaN

### ISSUE THREAD

**Issue by Enciusan** [Itheum/data-dex#499]
If i want to update the price from my wallet and i want to delete the whole price i'm getting NaN.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/92076681/230618535-fbfd8e47-901d-4130-be05-db0d6ccdf334.png">

**Comment by fuzzyduke** [comment]
Upon deleting the value the below is seen. However user cannot place a Data NFT for 0 or Free.

![image](https://user-images.githubusercontent.com/121969933/231512746-e0ec3358-c5fe-4a8a-8a22-ba2ef183e72b.png)

**Comment by fuzzyduke** [comment]
Fixed. Updated on PR 516.

![image](https://user-images.githubusercontent.com/121969933/231536722-ce16443a-ca6b-43b3-808b-9c8217e957b2.png)
