### ISSUE TITLE
Dataset title - Character limit

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#502]
Bug- Community

**Description**
When minting a Data NFT if you use a longer version for Dataset Title, more than 30 characters, you'll get an error message saying that it has to max 30 characters. When you trim down to even 1 character, you're not announced that you are below the maximum limit|

**How to reproduce**
Step1) Advertise Data
Step2) Dataset Title-> Input more than 30 characters
Step3) Try to reduce the characters
At step3, even if you have less than 30 characters, the error still occurs except you click somewhere outside the box

**Expected Behaviour:**
When reducing the character numbers in the Dataset title, once I'm back into the limits, the error should disappear

![image](https://user-images.githubusercontent.com/118804443/230787953-f5c8ade3-ffcb-4807-8344-91ca87604a44.png)

**Comment by BogdanCostinas** [comment]
@Enciusan - I believe you already know about this one and you mentioned you're on it

**Comment by Enciusan** [comment]
Yes i know what this task is about ☺️

**Comment by fuzzyduke** [comment]
Works well on all fields requiring similar validation. Only typo update required on "30 chars" to "60 chars" in the error message.

**Comment by fuzzyduke** [comment]
Fixed. Verified.
