### ISSUE TITLE
Typo in the "Burn" Box

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#503]
Community- Typo

**Description:**
There is a small typo in the Burn textbox " on one" is actually written instead of "no one"

**Steps to reproduce**
Step1 ) Go to your Data NFT Wallet
Step2) Click on Burn
Step3) The Typo is there in the burn text box

![image](https://user-images.githubusercontent.com/118804443/230788853-4af238d8-b606-4c67-b55a-5b15fe58e67a.png)

**Comment by icegriffinguru** [comment]
Fixed

**Comment by newbreedofgeek** [comment]
@fuzzyduke pls test on demo link found here - https://github.com/Itheum/data-dex/pull/523

**Comment by fuzzyduke** [comment]
Verified. Fixed.

![image](https://user-images.githubusercontent.com/121969933/231682184-9b3810ec-beeb-42e5-804d-cbe6d87cf00c.png)
