### ISSUE TITLE
Typo#2 in the "Burn" box when you list only 1 NFT

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#504]
Typo - Burn section

**Description**
When you mint N nft's and you only list 1, you get to own N-1. There is a typo " The remaining 1 "ARE" not under your ownership

Steps to reproduce
Step 1) Mint one Data NFT with multiple copies
Step 2) List one on the marketplace
Step 3) Go to Data NFT Wallet 
Step 4) Click on burn
Step 5) The Typo is there

_Rephrase the sentence so it will make it neutral, no matter how many NFTs are not under your ownership_

![image](https://user-images.githubusercontent.com/118804443/230789408-b88a9562-f9eb-4072-8b79-7b21c85a0c80.png)

**Comment by icegriffinguru** [comment]
Fixed

**Comment by newbreedofgeek** [comment]
@fuzzyduke pls test on demo link found here - https://github.com/Itheum/data-dex/pull/523
