### ISSUE TITLE
/datanfts/marketplace should redirect to /datanfts/marketplace/market

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#510]
Currently we have the following deep links:
/datanfts/marketplace/market
/datanfts/marketplace/my

If the user enters `/datanfts/marketplace`, we need to redirect it to `/datanfts/marketplace/market`

**Comment by icegriffinguru** [comment]
Fixed

**Comment by newbreedofgeek** [comment]
@fuzzyduke pls test on demo link found here - https://github.com/Itheum/data-dex/pull/523

**Comment by fuzzyduke** [comment]
Verified. Redirection is seen for /datanfts/marketplace/market
