### ISSUE TITLE
Data NFT Layer is spelled wrong

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#517]
It is Fuscia now.

It should be Fucsia

**Comment by newbreedofgeek** [comment]
Fuchsia?

**Comment by damienen** [comment]
Yes. My bad. I wrote it in my native language 😅

**Comment by newbreedofgeek** [comment]
Fixed 

<img width="895" alt="image" src="https://user-images.githubusercontent.com/743169/233363035-58db176f-0fee-4312-ba93-945aa2bdfd8e.png">
