### ISSUE TITLE
Advertise Data button is enabled while others are disabled

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#519]
**Description:**
At one point, we decided that while a transaction is pending, we will lock some buttons to stop the "potential" glitches from swapping pages.
While claiming from Claims Portal, all the buttons are disabled, except the Trade My Data ( From different programs like Red Heart Challenge etc )

**Steps to reproduce:**
Step 1) Claim from the Claims Portal
Step 2 ) Click on Trade Data
Step 3) A new page is opening
Step 4) At this point you can choose to mint a data NFT from the listed programs

**Expected behavior:**
No particular expectation, however since we locked all the pages for a reason, maybe it will be better to block this one as well to prevent potential future issues
![image](https://user-images.githubusercontent.com/118804443/231570670-e0feebb2-ba3f-44e5-9d1f-c5e92f998990.png)

**Comment by damienen** [comment]
This is available only on devnet, so no need to worry about it for now.

Closing.
