### ISSUE TITLE
Reduce API calls on Market + Wallet + Details Page 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#524]
- Reduce API calls
- Use Context to improve reusability in Marketplace (i.e. max offer price etc)
- As part of this -- improve the loading stats of all pages (there is a delay when network speed is slow)

**Comment by damienen** [comment]
https://www.npmjs.com/package/zustand

Let's use this

**Comment by damienen** [comment]
Things to figure out:
When are we making API calls
Which ones are reasonable to enter a state and not be fetched in real time

Come up with a plan for those

**Comment by damienen** [comment]
Closing for now. Will reopen/open new tickets if needed.
