### ISSUE TITLE
Homepage URL resolution.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#526]
We have the below 2 pages.
1) https://stg.datadex.itheum.io/
2) https://stg.datadex.itheum.io/home

     Item 2) is reached on clicking on home or the logo.  
However 1) is only reachable in the Data Dex upon placing in the URL. There is no other navigational means of getting to this page.

**Comment by damienen** [comment]
For now we will leave it as it is, but when we have some articles we will put the component for the articles in the home page, too. This way there is not necessarily a need to get back to the dashboard.

**Comment by damienen** [comment]
What is now on / -> Keep there
What is now on /home -> move to dashboard
Add dashboard to navbar

**Comment by damienen** [comment]
Solved
