### ISSUE TITLE
Royalty NaN% on details page (if royalty is 0)

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#533]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/743169/232762364-b4abae23-6697-4d7d-ad9d-2c83b4a01c36.png">

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
If royalties is 0, the value should not be NaN but should be zero.
I'm not sure how it showed NaN...
Added a check ensuring to print "-" instead of NaN

**Comment by fuzzyduke** [comment]
Verified Fixed.

![image](https://user-images.githubusercontent.com/121969933/233000463-41872c9a-0201-4b53-b1e1-3e6d0bf2bd0d.png)
