### ISSUE TITLE
Show uptime of Data NFTs so user can make an informed decision if they want to proceed

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#536]
Show uptime in both these models:
- Wallet > List
- Marketplace > Procure

If the Live uptime fails, then the user cannot proceed via the UI.

**Comment by newbreedofgeek** [comment]
@fuzzyduke 

Once this PR (https://github.com/Itheum/data-dex/pull/537) is merged, you can test it on the main feature dev link - https://github.com/Itheum/data-dex/pull/523

**Comment by damienen** [comment]
Checked and works as intended. @fuzzyduke please test it, too and reopen if needed

**Comment by fuzzyduke** [comment]
When file is online, User can proceed. When file is offline user is blocked from proceeding.

![image](https://user-images.githubusercontent.com/121969933/233964317-66103901-0410-434a-aabb-ffc9c5e3dd05.png)

![image](https://user-images.githubusercontent.com/121969933/233964228-ac3d4864-2a23-4263-89b3-04ddf729be05.png)
