### ISSUE TITLE
When listing my Data NFT on the marketplace, it should not check "my wallet balance is too low"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#538]
- i'm in my wallet and I want to list on marketplace
- The model popup ups and seems we are checking if  "my wallet balance is too low" and it's disabling the proceed button

![image](https://user-images.githubusercontent.com/743169/233531650-29402a48-b481-4cc6-840f-309400f525c3.png)

- We should not be checking if any balance is low right?

**Comment by newbreedofgeek** [comment]
Only work on this ticket after this PR has been merged into feature - https://github.com/Itheum/data-dex/pull/537

**Comment by damienen** [comment]
Solved. Closing.
