### ISSUE TITLE
From wallet, when I list - the Creator Royalties is wrong

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#539]
- In my wallet, an item shows Royalty 10%
- <img width="263" alt="image" src="https://user-images.githubusercontent.com/743169/233532212-431767fa-579c-4a5b-b68e-f4c716cfec12.png">

- When I click on List, it says "0 (you are the creator)
<img width="431" alt="image" src="https://user-images.githubusercontent.com/743169/233532369-5fe7b301-593d-47e7-a1b1-d857ceca216e.png">

This is wrong.

- It should show the Creator royalties in the model popup IF I'm the creator and only show 0 if i'm NOT the creator

**Comment by newbreedofgeek** [comment]
Only work on this ticket after this PR has been merged into feature - https://github.com/Itheum/data-dex/pull/537

**Comment by damienen** [comment]
But for that NFT you ARE the creator...

**Comment by newbreedofgeek** [comment]
@damienen ok.. this is good for now.

I opened a future work ticket to look into this a bit more as there may be some boundary conditions we need to think about - https://github.com/Itheum/data-dex/issues/542
