### ISSUE TITLE
Data NFT Wallet - Creator Royalties - More clarity in UI on royalty payouts

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#542]
Need to look at these listing popups:

I am the creator:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/743169/233876937-fd873a47-4473-4d47-b9db-4a893edd859b.png">

I am the owner:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/743169/233876955-12cbcb5e-8da6-4db2-b61b-fb073aabdcd0.png">

and update to include any boundary conditions like:
- I was the creator and then I listed it and someone bought it from me and then I bought it back.. in this case, does it appear in my wallet as a creator and owner? or just creator... and if so, the next trade will deduct the royalty.. and we should show this to the owner (who is also the creator)
- there maybe other boundary cases like this we need to uncover and update ui as needed

**Comment by damienen** [comment]
This was solved in #539. Closing.
