### ISSUE TITLE
Keep the Data Access progress model that shows the "popup blocked message" open with a "close and return" option

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#543]
This model, automatically closes when the data marshal streams data out.
<img width="487" alt="image" src="https://user-images.githubusercontent.com/743169/233880531-54bfc976-a535-4010-bfaf-cbfdbe762076.png">

BUT, if the user has their popup blocked.. then the model still closes and the UX is bad. In BoY this will cause UX issues i'm sure.

To keep it easier and improve UX.. let's do this:

- DO NOT automatically close this progress model. Keep it open
- And similar to the "Trade Data" progress model that shows a "close and return" button that appears ONLY after the Data NFT has minted.. do the same in this "view data" progress model as well.

**Comment by damienen** [comment]
Solved. Closing.
