### ISSUE TITLE
Adaptive Design for Data NFT marketplace.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#547]
Description:
Having the screensizes standardized for different resolutions to avoid misalignment of elements. This would address the issues of window resizing.

Please also define the resolution ranges.

Kindly provide an approximate for this implementation.

**Comment by damienen** [comment]
We need to implement a tablet view and that's going to be fine then

**Comment by damienen** [comment]
@fuzzyduke what you should be looking into is if there are any things loking bad on tablet resolutions and if anything looks bad in other resolutions (something might get broken when addding new code)

**Comment by damienen** [comment]
@Enciusan Check out some edge case of resolution issue on Oppo Reno 5 resolution

**Comment by fuzzyduke** [comment]
Kindly Find a few items on mobile: galaxy A51

1. Page number on mobile view overlaps with pagination arrow in marketplace page

![image](https://github.com/Itheum/data-dex/assets/121969933/5ee65564-6a42-4153-b828-5bbdd797002f)

2.  Overlap seen in homepage over Data NFT, text overlaps with image.

![image](https://github.com/Itheum/data-dex/assets/121969933/65ad3897-d646-4ac5-9c3e-1535e7c8c8d4)

**Comment by fuzzyduke** [comment]
Menu Break seen at px width 1201

![image](https://github.com/Itheum/data-dex/assets/121969933/14d698a3-a903-4f9c-9723-efb50283290c)

**Comment by fuzzyduke** [comment]
@Enciusan Kindly provide the pixel breakpoints for this implementation as well.

**Comment by fuzzyduke** [comment]
iOS Version 16.5
Model: iPad Air ( 5th Gen )
Retina display using Safari Browser

1. The color of the Itheum Logo is “grey” instead of black in white mode.

2. The social buttons were displayed once on the “get whitelisting page” click on Telegram icon. After re-direction ( refresh ) they did not appear again ( Telegram, Twitter, Discord etc )

![image](https://github.com/Itheum/data-dex/assets/121969933/fa7ecadf-288b-45cd-8ffb-3eba727ba496)

3. If we click on “my address quick copy” in vertical view - there is no CTA on the screen. This works fine in horizontal view and a success message ( address is copied to clipboard ) message is displayed

![image](https://github.com/Itheum/data-dex/assets/121969933/89ed850d-5b44-441f-953b-0c047ff20693)

**Comment by damienen** [comment]
Add adaptive 200 x 200, 400 x 400, 600 x 600 (maybe) sizing for Recent Data NFTs

**Comment by fuzzyduke** [comment]
Desktop

Go to Dashboard -> Linked Data CAT Accounts. After clicking on "Load Test Data". Kindly align the buttons for both the cards. 

![image](https://github.com/Itheum/data-dex/assets/121969933/ce343289-746f-416d-abff-40b215d978f2)

**Comment by damienen** [comment]
There are issues with the current implementation:
![image](https://github.com/Itheum/data-dex/assets/44813558/9dde495a-969f-4730-bb35-629541092665)
This is how it looks on my display. On stg, it looks better with everything on one row.

Moreover, when the test Data Cat account is loading the spinner is not centered anymore.
![image](https://github.com/Itheum/data-dex/assets/44813558/213ad4e9-ce41-40e7-a999-aa12c0ff40c7)
Also not enough margin in claims.

That's all I found

**Comment by Enciusan** [comment]
On it.

**Comment by damienen** [comment]
Coming soon on NFMe is not in the middle

**Comment by damienen** [comment]
Solved. Closing.
