### ISSUE TITLE
Data NFT Marketplace - wallet: Offline file should show and indicator when view data is invoked in the wallet.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#548]
Description:
 Offline file should show and indicator when view data is invoked in the wallet.
If the file is offline there should be an indicator that the file is offline.
Currently the DM allows the file to be downloaded, however the content of the downloaded file is invalid.

Steps to reproduce
1. Set a file to offline that has already been procured by account X.
2.  From Account X browse to wallet and view this data NFT.

Actual result:
File downloads with invalid content.

**Comment by damienen** [comment]
This is because of what github returns
