### ISSUE TITLE
Feature request: Concept of spaces for Entities to have their own profile pages.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#549]
Feature Rationale:

Data Creators should have a profile page where they can have their brief and have their data NFTs listed.

**Comment by fuzzyduke** [comment]
Kindly advise on priority or potential implementation timeline. This can be useful for an upcoming usecase with social influencers where they post their profile links in their social platforms. @newbreedofgeek @damienen

**Comment by damienen** [comment]
What that profile page should contain:
1. Address
2. Herotag
3. Contact Info (optional)
4. Owned Data NFTs
5. Listed Data NFTs
6. Created Data NFTs
7. Other NFTs

**Comment by newbreedofgeek** [comment]
@Enciusan 

This is the basic wireframe you can use to start building.

![image](https://github.com/Itheum/data-dex/assets/743169/4397516f-85e0-4a22-8ea3-e74334546d4c)


CC @damienen
