### ISSUE TITLE
Data Dex Home: Wallet amounts failed to load.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#560]
Description:

Itheum balance and "My Claims balance" fails to load.

Steps to reproduce.
1. Navigate to homepage https://deploy-preview-516--frosty-hermann-85ca4f.netlify.app/home

![image](https://user-images.githubusercontent.com/121969933/234227560-7678b4dc-3cd3-4326-b898-4eb9f0b26931.png)

**Comment by damienen** [comment]
@icegriffinguru I think this has something to do with race conditions. Can you look into it?

**Comment by damienen** [comment]
That's for sentry, @icegriffinguru . The other fails are not related to sentry. Sentry is something else.

**Comment by damienen** [comment]
That's a sentry error, but the claims not loading is not related to that

**Comment by icegriffinguru** [comment]
Which commit is it?

**Comment by damienen** [comment]
It's on Enciu's PR link

**Comment by fuzzyduke** [comment]
Seen again 

![image](https://user-images.githubusercontent.com/121969933/234767103-cc3cff64-2b8d-4885-bfb4-195e086feda6.png)

**Comment by fuzzyduke** [comment]
Seen again on 1/5/2023

User logged in on Defi wallet. Upon logging the below was encountered.

![image](https://user-images.githubusercontent.com/121969933/235420847-6b477aad-1a15-45ba-93c1-fbf6dd0db242.png)
