### ISSUE TITLE
Data NFT Minting: Copies input is capped at 20.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#562]
Description:
Data NFT Copies is capped at 20.

![image](https://user-images.githubusercontent.com/121969933/234234345-e1692db8-d1db-46e3-a358-d6fc8725a3fa.png)

**Comment by damienen** [comment]
@newbreedofgeek This has to be solved from the SC config

**Comment by damienen** [comment]
Solved
