### ISSUE TITLE
Data NFT Marketplace Wallet: Upon listing more than 51% of the available supply validation error seen on field, also the Card elements misaligned. 

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#563]
**Description**
1. If a user mints 20 copies of a data NFT and lists 11 copies, the below is seen upon confirming the listing.

11 is retained as a value in the textbox "How many to list" and as the remaining balance is 9 we see the box highlighted in red.

**Steps to reproduce.**
1. Mint 20 amount for a Data NFT.
2. List 11 in the marketplace
3. Also observe the element misalignment in the card.

**Expected Behavior**

1. The amount 11 should be cleared after the listing is done.
2. Proper alignment should be observed in all elements within the card.

![image](https://user-images.githubusercontent.com/121969933/234239119-e1d80fe6-6b58-4afd-851c-e667079e6251.png)

**Comment by damienen** [comment]
Solved. Closing
