### ISSUE TITLE
Data Dex Home: Error seen on page load.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#565]
Description:
Upon switching wallet to log in below is seen.

ER2: Could not get your claims information from the MultiversX blockchain.

![image](https://user-images.githubusercontent.com/121969933/234387798-f2fa27c5-5f62-44f1-83c9-692c251ca922.png)

**Comment by icegriffinguru** [comment]
No SC on mainnet.
Closing
