### ISSUE TITLE
Data NFT Marketplace Listing: Empty listing seen on page load

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#566]
Description:

Empty marketplace encountered on page load, despite having items within marketplace listing.

![image](https://user-images.githubusercontent.com/121969933/234388824-0bb8d7fd-ad7f-408a-b0c0-d24128c02bd5.png)

**Comment by icegriffinguru** [comment]
Isn't it API issue? @fuzzyduke , @damienen

**Comment by damienen** [comment]
It is, but it is not timeout. You can see the problem is "invalid bech32 string length 0"

**Comment by icegriffinguru** [comment]
No SC on mainnet.
Closing
