### ISSUE TITLE
Description: Mobile view of wallet and marketplace listing has unclear sectioning view.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#568]
Description:
Mobile view of market place listing page and wallet now have sections, which seem skewed in the mobile view. 
 Your Data NFT(s) | Purchased | Favorite | Activity | Offers
Please provide clarity on the UI for the mobile view.
Also please review the padding for the Data NFT image that intersects with the border of the main card.

![image](https://user-images.githubusercontent.com/121969933/234405176-1b44fb74-bcaa-44dc-8d94-106cadafc9eb.png)

![image](https://user-images.githubusercontent.com/121969933/234404936-c65b5f76-62e1-461b-891a-ddb11d9a5f40.png)

**Comment by damienen** [comment]
Any updates on this?

**Comment by damienen** [comment]
Looks good. Closing.
