### ISSUE TITLE
Item Counts on the "Public Marketplace" and "My Listed Data NFTs" are wrong

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#572]
e.g. I dont have (8) in the "My Listed Data NFTs"
<img width="788" alt="image" src="https://user-images.githubusercontent.com/743169/234469851-88d1f711-89ea-4117-b1f1-abed71bb668c.png">

I think the numbers are swapped or wrong

**Comment by damienen** [comment]
@bucurdavid is it also done on FE?

**Comment by bucurdavid** [comment]
@damienen  yes

**Comment by fuzzyduke** [comment]
Verified. Fixed. 

Tested on #800
