### ISSUE TITLE
When listing.. the "royalty" calculation seems wrong

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#587]
I was testing royalties by using 3 wallets and saw some issue the royalty calculation in UI.

1. I and Bob. I bought Alice's NFT and then delisted it for 200 ITHEUM. Alice set 10% royalty. When I clicked on list, I say this popup. Notice the 20 ITHEUM royalty in the calculation.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/743169/234758553-939fd769-64f0-486e-9f56-c3b38622bc13.png">

2. Carol comes and buys the NFT from the marketplace. 

3. Alice then logs in and see 19.60 royalty.  I think the UI in step 1 needs fixing? let's discuss
<img width="261" alt="image" src="https://user-images.githubusercontent.com/743169/234758604-428224ee-c706-40cf-b274-8ab890a393ba.png">

**Comment by icegriffinguru** [comment]
@damienen , @bucurdavid 
How do we calculate royalties of an offer?

**Comment by damienen** [comment]
@icegriffinguru 

1. Please make a PR so we can easily check this
2. It should be calculated (listingFee-sellerFee)*royalties

**Comment by icegriffinguru** [comment]
![image](https://user-images.githubusercontent.com/97042732/235819627-bc2648ab-5c00-41bb-af36-9fb627c2313e.png)

This is current UI. @damienen , is it correct or should i update it?

**Comment by damienen** [comment]
That is the current UI if you are the creator or there are no royalties.

**Comment by damienen** [comment]
Please also move seller tax above royalties.
![image](https://user-images.githubusercontent.com/44813558/236389383-e77fcd0f-65ab-4740-9e4b-70e1d9bd1f33.png)
Now royalties is above

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Works. Closing
