### ISSUE TITLE
Data NFT Marketplace Wallet: Card Breaks on extra input entry in fields  "How Many to list" or "Unlock fee for each"

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#588]
Card breaks when higher value is entered for either "How Many to list" or "Unlock fee for each"

![image](https://user-images.githubusercontent.com/121969933/234766513-2007217b-87de-4d1d-b27c-ad79eeda38e1.png)

![image](https://user-images.githubusercontent.com/121969933/234766084-b4503f40-5d92-4372-a2d3-bf49d6e1a742.png)

**Comment by fuzzyduke** [comment]
Verified fixed.

Clarification: in the Below, it is seen that when an error message is encountered the button moves down. Although there is no space and it has to be, kindly confirm if this behavior is acceptable.
![image](https://github.com/Itheum/data-dex/assets/121969933/3919be23-f794-479b-a715-f6e801d80017)

**Comment by newbreedofgeek** [comment]
Keep some fixed height for error message so button does not jump @Enciusan

**Comment by damienen** [comment]
Fixed for unlock fee for each, but not for "how many to list"

**Comment by damienen** [comment]
Solved. Closing. Nice!
