### ISSUE TITLE
Data NFT Marketplace: While procuring a Data NFT from Slide-in detail page, file is always reported as offline.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#591]
Description: 
If a user procures an NFT from the Marketplace listing, then the File availability checker accurately reports the availability. However, if a user opens the slide-in and attempts to procure then they will always see the file as offline.

Steps to reproduce.
1. Browse to marketplace listing.
2. Click on the image of a procurable data NFT card.
3. Click on Procure NFT.

Expected result
1. The file availability should reflect correctly.

Actual Result
1. Currently navigating via slide-in to procure always returns offline status for files.

![image](https://user-images.githubusercontent.com/121969933/235421680-127d4e66-f996-417e-8bec-ad723f2aadc5.png)

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
Verified fixed. #612

**Comment by fuzzyduke** [comment]
Works on 612  and not on 614, please advise on the branch to be tested on.
