### ISSUE TITLE
Data NFT Marketplace: Once user lists Data NFT and navigates to My Listed Data NFTs, they encounter empty listing with errors

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#592]
Description.
Once user lists Data NFT and navigates to My Listed Data NFTs, they encounter empty listing with errors

This has been reported by a single user during #BoY1
Not reproducible.

Steps to reproduce:
1. List data NFTs for price of 20 Itheum.
2. Browse to Update the price of the Data NFT under My Listed Data NFTs.

Expected result.
1. User should see their data NFTs under the section to perform actions of updating price or delisting.

Actual Result
1. The below errors are encountered.

**Comment by damienen** [comment]
@fuzzyduke what below errors?

**Comment by fuzzyduke** [comment]
Kindly find the below. @damienen 

![image](https://user-images.githubusercontent.com/121969933/235511190-f4521f23-ebfd-4ffb-81ff-c45bf7147eb4.png)

**Comment by damienen** [comment]
Ohh, just Network Provider issue. Makes sense, but not a new issue. Closing.
