### ISSUE TITLE
Description: User was not given any indicator of why the Mint button was not enabled.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#593]
Description:
There was a scenario wherein a user filled out all fields but the Preview URL.

As the user was trying to mint the Data NFT they noticed that the Mint button was disabled and no error message or indicator was seen.

Suggestion:
Have the button enabled, and on click first performs validation of all fields before proceeding to the next step, which is the minting popup/transaction.

![image](https://user-images.githubusercontent.com/121969933/235424737-3cf71db6-73a3-4ec5-8bf6-9b85433e7c4c.png)
![image](https://user-images.githubusercontent.com/121969933/235424756-9607d081-0a67-48e2-9b89-0501608a8631.png)

**Comment by fuzzyduke** [comment]
Shortfix seen, Mandatory fields are marked with a red asterisk.

**Comment by damienen** [comment]
Great. Closing.
