### ISSUE TITLE
Data NFT Marketplace: User face issue on safari Browser

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#596]
Description:
User reported that they have an issue viewing data on Safari Browser. 
Others users have reported a seamless testing cycle on Safari.

Needs to be tested by a user with an Apple running Safari.

**Comment by damienen** [comment]
@Enciusan it's your time to shine 
@fuzzyduke any idea which NFT is it?

**Comment by Enciusan** [comment]
Can't reproduce.
