### ISSUE TITLE
2 Connections in xPortal

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#597]
**Description**
The users were connected to the data dex and experienced a disconnect at some point. After they established again a connection, in the xPortal app there were 2 opened connections on the Data DEX at the same time 

This issue was not reproduced by us, happens from time to time. To be tested in the future and come back with update. Multiple users have reported connection issues with xPortal

**Comment by damienen** [comment]
This is simply the way xPortal works at the moment. Nothing we can do about it at the moment, sadly.

They can manually close the connections. Closing.
