### ISSUE TITLE
Data NFT Marketplace: Listing reported to be successful despite error seen in explorer.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#599]
Description:
User has mentioned that there were able to successfully list NFTs despite the error in the explorer.

https://devnet-explorer.multiversx.com/transactions/64be5bb39ba0592bc3e1183655e9ae38250709c1b61a2bbb15a84a1a0b3a267e

![image](https://user-images.githubusercontent.com/121969933/235510524-e928b1ee-0c43-4313-ad23-aefca903f5b5.png)

**Comment by damienen** [comment]
So the toast in the lower right corner appeared as successful even though the transaction failed?

**Comment by fuzzyduke** [comment]
Verified with tech, no action to be taken on this.
