### ISSUE TITLE
Supply after Burn do not refresh properly

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#600]
*Description*

Multiple users reported this type of issue:
They performed multiple actions in the Data DEX and on random times and random actions, the tx did poped up in xPortal to be signed.

**Comment by damienen** [comment]
The title does not seem to align with the description. You sure these are supposed to go together, @BogdanCostinas ?

**Comment by BogdanCostinas** [comment]
Description:

Multiple community members reported some issues when comes to the Total supply- not updating right after they burned a random number of NFTs. Sometimes they needed to refresh the page and/or disconnect and reconnect again to see the correct number of Data NFTs that remained after burning

**Comment by damienen** [comment]
That is normal. Happening from API caching. On mainnet it should be a better.
