### ISSUE TITLE
Not able to navigate through pages while waiting for a tx to be completed

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#601]
**Description**

When you signed a transaction, and it's pending, you get the "forbidden" sign when you try to navigate to other pages within the Data DEX. 
It might be confusing for some participants in the data dex to wait for the tx to be processed until they can perform another action

**Comment by damienen** [comment]
This is expected and intentional behavior. It's a limitation we have to enforce due to performance issues. This is for as long as we do not have a backend at least.
