### ISSUE TITLE
Terms of use checkbox is already "signed"

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#603]
**Description**
If you accept the terms of use  before procuring a Data NFT and close the form and reopen it again, you don't need to accept the terms again, since the box it's already filled

**Steps to reproduce:**
Step 1: Go to Marketplace
Step 2: Click on Procure on a random Data NFT
Step 3: Close the "buying" form and Check the box " I have read all terms and agree to them"
Step 4: Click again on Procure on the same Data NFT
Step 5: The checkbox it's already filled

**Expected behavior**
When you open the "Procure form" everything need to be cleaned, I need to manually check the box that I have read and agree with the terms of use

![image](https://user-images.githubusercontent.com/118804443/235513189-b5a11316-98ad-4886-bae9-619659977699.png)

**Comment by fuzzyduke** [comment]
verified fixed. #612
