### ISSUE TITLE
Data NFT Marketplace: Data NFT image was seen to be for an alternate source

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#604]
Description:
The Data NFT Image was seen to be from an alternate source while the user was trying to procure the Data NFT.

![image](https://user-images.githubusercontent.com/121969933/235513410-594f9f73-7859-4440-ad7f-3643408c16be.png)

**Comment by damienen** [comment]
That simply looks like a video card bug. Do we have any extra details on this? What does "alternate source" means?

**Comment by fuzzyduke** [comment]
Not reproducible. As per feedback, this may have been an issue with the user's display card. No other insights on the possible cause.
