### ISSUE TITLE
"Retry?" - After the Data Marshal perform the availability check

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#606]
**Description**
When you want to Procure a Data NFT, the Marshal checks if the Stream is available. Once the check has been completed, regardless of the result you'll get the message " Retry? " 

**Steps to reproduce:**
Step 1: Go to Marketplace
Step 2: Click on Procure a Data NFT
Step 3: Wait until the check is done and then you'll see the "Retry?"

**Expected behavior:**
If the Stream is Offline, then display the message "Retry?"
If the Stream is Online, edit the text with something different e.g.: "Perform another check" "Check again for availability" or "Recheck"

![image](https://user-images.githubusercontent.com/118804443/235513705-61e89d21-7073-4200-8e1c-86855bfe508a.png)

**Comment by damienen** [comment]
@newbreedofgeek I think the message being the same is fine. What do you think?

**Comment by damienen** [comment]
We can change to "check again" if it's succesful

**Comment by damienen** [comment]
Works. Closing.
