### ISSUE TITLE
User sees message for insufficient Itheum despite have 1k+ 

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#608]
Description:

1. User attempted to procure an NFT and received the below message despite having 1k+ Itheum.

![image](https://user-images.githubusercontent.com/121969933/235517398-8a1d8bc8-94cc-4db1-b784-241f200ebb6f.png)

**Comment by damienen** [comment]
@fuzzyduke do we know the address of that user?

**Comment by fuzzyduke** [comment]
Address of user @damienen 

erd1ykcsegejws9866q6cywh8q79tfdqm2pg29727x74znezurhesewq7pneuu

**Comment by damienen** [comment]
Rechecked behavior. It was an MX API failure.
