### ISSUE TITLE
Data NFT Marketplace: Procure NFT returns error in unknown scenario.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#609]
Description:

User reported the below explorer transaction failure upon trying to procure an NFT.

It is assumed that the price was updated as the user Procured the NFT.

https://devnet-explorer.multiversx.com/transactions/c250211ba7829e8e482bf8e53b351616e8176a8a17fe6ed8788d109daa0e60dd

**Comment by damienen** [comment]
Can confirm this is what happened. This is the price changing transaction:
https://devnet-explorer.multiversx.com/transactions/b243407f73b54ed8ec99ffb2095cf87bdecf0cfec5e06f96f8dc9c02a1521785#decimal

Closing.
