### ISSUE TITLE
UI Polish - Get Whitelisted page

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#611]
- We need to align the page to the new design.
- Needs to be pixel perfect, people will judge the whole data dex based on UI
- Make it look good on Mobile, Tablet and Desktop
- Ask on Slack for Figma link

**Comment by Enciusan** [comment]
We have to add the gif also a little bit of allign, tablet view i have to check too and for mobile view we need some allign too. @damienen

**Comment by newbreedofgeek** [comment]
- Animated gif is left.

**Comment by damienen** [comment]
Discord link is also left
Telegram link is also left

**Comment by damienen** [comment]
@newbreedofgeek solved the animation for now. closing.
