### ISSUE TITLE
ER1: Could not get your token information from the MultiversX blockchain.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#615]
Below is seen on page load as of 8th May 2023.

Kindly note this is an old wallet with a history of transactions.
ER1: Could not get your token information from the MultiversX blockchain.

![image](https://user-images.githubusercontent.com/121969933/236758026-a24d991c-a1a6-4ce0-b675-7706588e2b45.png)

**Comment by damienen** [comment]
MX API error. nothing new around town.

closing
