### ISSUE TITLE
User is able to purchase NFT in detail page when not logged in.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#621]
Description:
User is able to purchase NFT in detail page when not logged in.

Steps to reproduce.
1. Make sure you are logged out
2. Browse to the marketplace
3. Click on the detail view of a purchasable data NFT.

Expected Result:
1. Data NFT should not be purchasable to users who are not logged in.

![image](https://github.com/Itheum/data-dex/assets/121969933/0cd8f9c4-5db0-47bf-a9d7-a4f58ad3e94d)

**Comment by damienen** [comment]
Solved on @Enciusan 's branch. Closing.
