### ISSUE TITLE
Mobile Menu for desktop for non logged in users does not have a drop down menu.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#623]
Please review the menu structure for mobile for both logged in and non logged in users.

Please compare to desktop version while testing.

![image](https://github.com/Itheum/data-dex/assets/121969933/e79200a2-12be-4ed6-a6f3-a280b60f18df)

**Comment by damienen** [comment]
Desktop also does not have all navbar components. The only thing missing is marketplace on mobile in navbar, which is intentional
