### ISSUE TITLE
Recent Data NFTs section has only 6 items worth of Items, instead of 2 full rows.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#624]
Description
Recent Data NFTs do not show 2 full rows worth of NFTs, Please clarify the logic.

![image](https://github.com/Itheum/data-dex/assets/121969933/c61950af-e6f0-4786-b97a-e273a5e40275)

**Comment by damienen** [comment]
Solved by fetching last 25 possible IDs and slicing this result to 10. This makes the chances of only 10 being available from last 25 very slim.
