### ISSUE TITLE
Data Marshal accepts URL however view data of the data NFT doesnt reflect any output file.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#625]
Description
Data Marshal handling of arweave stored files anomalies noticed
2 URLs were placed in the Marshal. Both of them were recognized as valid URLs while minting.

The second URL seems to be a redirect of the first. The URL was retrieved from the transaction of the 
1. Upon view data of the below minted URL, a blank page was encountered
https://arweave.net/fOdfjsnJSN5J9KhON7gaVsaBPHyHnLEONPmbCLL-3ZE
https://devnet-explorer.multiversx.com/nfts/DATANFTFT4-3ba099-0176

2. Upon view data of the below minted URL, Internal server error was seen.
https://pttv7dwjzfen4spuvbhdpoa2k3dicpd4q6olcdru7gnqrmx63wiq.arweave.net/fOdfjsnJSN5J9KhON7gaVsaBPHyHnLEONPmbCLL-3ZE
https://devnet-explorer.multiversx.com/nfts/DATANFTFT4-3ba099-0177

**Comment by fuzzyduke** [comment]
When the user enters a "data stream URL", we need to pass it to some backend web service that can validate all of these rules and then give a PASS /FAIL.

**Comment by damienen** [comment]
Closing for now. Moved to another issue
