### ISSUE TITLE
Description: For items in the Users Wallet, they shouldnt see "Purchase data" in the slider detail page.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#626]
Description:
Purchase data is seen for users for their wallet items.

Kindly remove "Purchase data", "Preview Data" for slider detail view of items in the wallet.

![image](https://github.com/Itheum/data-dex/assets/121969933/2923d4c9-54bf-42f9-a319-12af83a359e4)

**Comment by damienen** [comment]
Related to #618 . Assigning to, @Enciusan ! Congrats! Jackpot

**Comment by damienen** [comment]
Solved. Closing.
