### ISSUE TITLE
Data NFT Wallet: Purchased tab should only show the items that the user is the owner but not the creator.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#629]
Description
The purchased tab should only show the items that the user is the owner but not the creator.

![image](https://github.com/Itheum/data-dex/assets/121969933/3e2068d8-4965-4074-8a0d-aee4e5404f74)

**Comment by icegriffinguru** [comment]
@damienen 
Purchsed button is being used now?
it's disabled in default and for future work, isn't it?

**Comment by damienen** [comment]
That's why we want to implement the functionality for it, to enable it

**Comment by icegriffinguru** [comment]
oh, enabling `Purchased` tab and showing bought NFTs is in current milestone?

**Comment by icegriffinguru** [comment]
@damienen

**Comment by damienen** [comment]
Yes, as it's pretty easy to do.

**Comment by fuzzyduke** [comment]
Verified Fixed on #649
