### ISSUE TITLE
Multi-wallet Login Support 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#63]
Currently we only support login for Metamask. Create a UI abstraction that allows for adding in other wallet providers. To begin with, let's add:
- Metamask
- WalletConnect
- Ledger (Elrond) - https://github.com/Itheum/data-dex/issues/62

**Comment by RoseAdminforallgroup** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/

**Comment by newbreedofgeek** [comment]
Duplicate of #64 and #70
