### ISSUE TITLE
Suggestion: "Get whitelisted to mint Data NFTs" visibility review.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#633]
"Get whitelisted to mint Data NFTs" is currently seen on the header menu only for non logged in users, For logged in users it shows in the dropdown menu.
Should there be a more prominent CTA in maybe the homepage?

![image](https://github.com/Itheum/data-dex/assets/121969933/844c93ed-9035-4130-924e-d0af9513998e)

**Comment by fuzzyduke** [comment]
Clicking on Join now goes to an invalid page

Steps to reproduce
1. go to the dashboard.
2. go to the final section "App Marketplace"->"learn more"-> "Join Now"

This is the same for Strava Fitness

![image](https://github.com/Itheum/data-dex/assets/121969933/7ec6d89b-2f9f-4cfd-b64f-ae54ace80341)

**Comment by fuzzyduke** [comment]
Comment added on the above for how to reproduce.

**Comment by damienen** [comment]
It occupies lots of space, for now let's leave it be
