### ISSUE TITLE
CanaryNet GuardRails Page/Section on Data DEX

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#636]
As per our commitment to transparent CanaryNet GuardRails management, we need a page or section in the Data DEX that shows:

1. Active Guardrails and values (e.g. max token price = 1000 ITHEUM)
2. Historic Changes to Guardrails (e.g. max token price changed from 500 ITHEUM to 1000 ITHEUM and TX on-chain)
3. Upcoming Changes to Guardrails (e.g. max token price changed from 1000 ITHEUM to 1500 ITHEUM on XXX)

**Comment by damienen** [comment]
Let's create a new page with it

**Comment by damienen** [comment]
@Enciusan maybe leave the preview here as a comment

**Comment by damienen** [comment]
For history:
Show changes except of an entire profile, consisting of date and link to tx

For coming:
Show changes and expected change date

**Comment by damienen** [comment]
Don't forget to include "Whitelisted Data Creators"

**Comment by damienen** [comment]
Remove:
% cut from seller: 200
% cut from buyer: 200
Discount fee % seller: 0
Discount fee % buyer: 0

Add:
Min royalties
Max royalties
Time between mints
Max Data NFT supply
Anti-Spam fee

**Comment by damienen** [comment]
Nice looking as per the UI design.
