### ISSUE TITLE
Max Listing / Max Buy Token Limits on UI

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#637]
- Have a config parameter for "max SFTs per user" (different to max supply of SFT in wallet or marketplace)
- When user tries to LIST more than this limit, the UI stops them
- When user tries to BUY more than this limit, the UI stops them

@damienen -- this would be the 1st feature we build and ship after soft-launch

**Comment by damienen** [comment]
MAX_BUY_LIMIT_PER_SFT

**Comment by icegriffinguru** [comment]
Fixed.
Should add `REACT_APP_MAX_BUY_LIMIT_PER_SFT="30"` into env file
Any number is fine

**Comment by damienen** [comment]
> * Have a config parameter for "max SFTs per user" (different to max supply of SFT in wallet or marketplace)
This is covered ^

> * When user tries to LIST more than this limit, the UI stops them
This is not currently covered ^

> * When user tries to BUY more than this limit, the UI stops them
This is covered^

**Comment by icegriffinguru** [comment]
Should I add `MAX_LIST_LIMIT_PER_SFT`, too?
@damienen

**Comment by icegriffinguru** [comment]
@damienen , @fuzzyduke  Fixed

**Comment by damienen** [comment]
Works. Closing.
