### ISSUE TITLE
Links to invalid pages

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#641]
> Clicking on Join now goes to an invalid page
> 
> Steps to reproduce
> 
> go to the dashboard. go to the final section "App Marketplace"->"learn more"-> "Join Now" This is the same for Strava Fitness
> 
> ![image](https://user-images.githubusercontent.com/121969933/238426061-03dd3328-e4ef-4fff-a670-9a6673ea7e65.png)

**Comment by damienen** [comment]
Are you on mainnet? If so, yes, it shouldn't be available.

If you are on devnet, it's just that "Join Now" that shouldn't appear

**Comment by fuzzyduke** [comment]
Have checked on 583 and 638. The section doesnt show.

**Comment by bucurdavid** [comment]
@fuzzyduke where did you tested it ? check now my PR

**Comment by fuzzyduke** [comment]
Passed, no invalid links encountered. Verified on #657
