### ISSUE TITLE
Show when marketplace is paused

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#652]
The same way we show a specific NFT is frozen, we should show the marketplace is paused.

It should ba the same typ e blur and a text centered that says "Data NFT Marketplace is currently paused. Please check back later"

**Comment by icegriffinguru** [comment]
@damienen , @fuzzyduke  fixed.
if Market is pauses, dapp throw errors on clicking
- "List" button on Wallet page
- "Purchase" button on NFT detail page

Marketplace page gets freezed entirely

**Comment by damienen** [comment]
@icegriffinguru can you save that pause into store and disable those buttons with a tooltip in case the marketplace is paused?

**Comment by icegriffinguru** [comment]
Done
@damienen , @fuzzyduke

**Comment by damienen** [comment]
Seems good. Closing.
