### ISSUE TITLE
Identical tab styling for both "Wallet" and "Market"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#655]
Currently, the Data NFT Wallet tab style looks very good (on desktop)

But the Data NFT Marketplace tab style looks different:

What do to:
- Make the Data NFT marketplace tab style exactly the same as Data NFT Wallet. Here are the main items to fix, but you can do what you need to do it make it "identical"

![image](https://github.com/Itheum/data-dex/assets/743169/f08788b7-d116-49c3-b6eb-484b267f57ee)

**Comment by damienen** [comment]
If you switch quickly between Wallet and Market you will see the tab selector "jumping"

**Comment by damienen** [comment]
Good stuff. Closing.
