### ISSUE TITLE
Data Dex: Login issues

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#660]
Description:

First time log in doesnt load token values. Wallet: web wallet.

![image](https://github.com/Itheum/data-dex/assets/121969933/fbeaff77-a38e-4ada-8f3c-6930193622e4)

**Comment by icegriffinguru** [comment]
@damienen , @fuzzyduke

**Comment by fuzzyduke** [comment]
Additional Login Anomalies

1. Fresh login to a wallet still retain the header which indicates user that is not logged in. the dashboard however is seen.
2. Fresh login to a wallet does not log in user. it request the 4 wallet login options a second time.3.

**Comment by icegriffinguru** [comment]
> Additional Login Anomalies
> 
> 1. Fresh login to a wallet still retain the header which indicates user that is not logged in. the dashboard however is seen.
> 2. Fresh login to a wallet does not log in user. it request the 4 wallet login options a second time.3.

@fuzzyduke 
Have you checked on my branch?

**Comment by fuzzyduke** [comment]
@icegriffinguru had experienced this on other branches. Have checked on your branch and not encountered the issue yet, will keep this ticket open for some time to observe behavior as it is not consistently reproduceable.

**Comment by damienen** [comment]
Will close for now if not observed. Please reopen if needed
