### ISSUE TITLE
Datadex: Copy address function doesnt seem to copy

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#661]
Description:
Copy address doesnt seem to copy.

![image](https://github.com/Itheum/data-dex/assets/121969933/8159b90d-6192-4c01-8b73-d0738e6f6b4a)

**Comment by fuzzyduke** [comment]
Cant seem to reproduce this consistently.

**Comment by icegriffinguru** [comment]
I can't also produce the error. I checked the code but everything seemed fine.
I made the button click shows a popup message saying "Address is copied to clipboard".
