### ISSUE TITLE
Secondary Trade Listing Royalty and "You will receive" calculations are incorrect

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#664]
1) As discussed, when testing with 3.22% royalty the calculations are wrong:
<img width="419" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/5070a439-d979-4569-8a53-f821ff1e8058">

2) This issue will probably be the same with whole number royalties as well. e.g 15%.

3) Also test multiple listings.. 1 vs more than one. i.e. if someone list 96 tokens, will the calculation be correct? This should be checked for Data Creator AND non-data Creator (so royalties are shown on secondary trade)
<img width="415" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/072e1c02-774c-493d-8a80-fdfd5e1915bd">

**Comment by damienen** [comment]
Solved. Closing.
