### ISSUE TITLE
Data NFT Marketplace: Marketplace shows error upon refresh.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#676]
Description:

Stg env->log in mainnet->log in via defi wallet->data nft marketplace

Upon hitting f5 to refresh the page, sometimes the page displays error code Er1. See below image.

"Er1:  Error getting your token information from the blockchain when"

Expected result: Data NFT Marketplace refreshes correctly without any error codes

Chrome Version 113.0.5672.127 (Official Build) (64-bit) on Win 10 Desktop

![image](https://github.com/Itheum/data-dex/assets/121969933/01093f41-7f70-4e28-b1f5-eb5dbf4d4385)

**Comment by icegriffinguru** [comment]
@fuzzyduke 
Firstly, "Er1" error message does not exist on current milestone branch.
Secondly, i need to know which query causes such error. At least, a snapshot of developer console is needed.
Lastly, oftern refreshing page will exceed API call limit

**Comment by fuzzyduke** [comment]
@icegriffinguru This was as per our mainnet testing on https://stg.datadex.itheum.io/.  
Point 1. Noted, wasn't aware of the modification.
Point 2, This was reported by a user during testing, the console view is not available. 
For point 3, as this was on mainnet, is it possible to exceed the API call limit?

**Comment by icegriffinguru** [comment]
For point 3, yes, there is API limitation on mainnet.

**Comment by damienen** [comment]
So it's just an API failure then. Closing.
