### ISSUE TITLE
Data NFT Marketplace: Links are invalid for some pages.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#678]
Description: 

Go to the dashboard. In the App Marketplace section click on Gamer Passport and then "Join Now", link is seen to be invalid.
This is the same case for Strava.

Further under gamer passport we see "ESSports" which is incorrect.

**Comment by bucurdavid** [comment]
@damienen  @newbreedofgeek  This are fixed on [milestone-1.1.0](https://github.com/Itheum/data-dex/tree/milestone-1.1.0)

**Comment by damienen** [comment]
Already solved, closing.
