### ISSUE TITLE
Whitelist page: Components not clickable when page is scaled to 150%

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#679]
Description:

When the page is scaled higher on the browser, header buttons are not easily clickable. Seems some TS components are overlapping with the header items.

![image](https://github.com/Itheum/data-dex/assets/121969933/b52c6ef5-3946-4acf-a4e5-18dbca620625)

Correct the text to "Get Whitelisted to be part of the first batch of Data Creators *to* mint Data NFTs. Make history!"

**Comment by damienen** [comment]
Can you clarify the part with the correct the text? What does it have to do with the other stuff?

**Comment by fuzzyduke** [comment]
It is an additional point regarding the grammar used in the write-up, which was a minor point.

**Comment by damienen** [comment]
Will be implemented with tablet view
