### ISSUE TITLE
Data NFT Marketplace: Unable to log into browsers from ledger

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#682]
Description:
Users report to not be able to log into Opera, Firefox and Edge from Ledger.

User: ZK

**Comment by damienen** [comment]
As expected, Firefox disabled Ledger usage by default. One can connect with Ledger after following the tutorial:
https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-x-Ledger-U2F-Issue-on-Firefox?support=true
Tested and it works.

Edge works

Indeed Opera Crypto Browser is problematic, will escalate to MX.
