### ISSUE TITLE
Date format across platform

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#683]
Description:
Date format has to be sorted to dd/mm/yyyy

-PP

**Comment by icegriffinguru** [comment]
@fuzzyduke 
Fixed

**Comment by damienen** [comment]
Good. Closing

**Comment by fuzzyduke** [comment]
Date Convention to be dd/mm/yyyy, this is seen in "Recent Data NFT interactions".

![image](https://github.com/Itheum/data-dex/assets/121969933/787a5b5a-300a-494f-a902-4fd1ab708759)

**Comment by fuzzyduke** [comment]
Please rievew the formats across all activity and transaction history views.

**Comment by icegriffinguru** [comment]
@damienen 
I think it's impossible to change date format with `input` element.
https://stackoverflow.com/a/9519493/17823883

**Comment by damienen** [comment]
Yes, I searched for it, too and it seems it's not straight forward

**Comment by damienen** [comment]
Will close for now. Will get back to it if that's the case
