### ISSUE TITLE
Ledger Popups (e.g. TX sign) are not centred on screen

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#690]
<img width="1151" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/6c6d705e-87a6-4f9a-ad12-89a33094aff2">

**Comment by damienen** [comment]
This is the basic centering coming from MX's library.

**Comment by damienen** [comment]
Solved. Closing

**Comment by newbreedofgeek** [comment]
@damienen i'm reopening this. 

Wes using ledger today and on my laptop, the screen asking to "sign TX" etc are looking a but bad. i.e. they are too long and have weird padding etc. We need to do a round of fixes.

**Comment by damienen** [comment]
Can you give some screenshot and point out what looked bad?

**Comment by newbreedofgeek** [comment]
@damienen  

Most TX popups have too much padding.. mainly top and bottom.

If you look at the TX popups on MX tools like xExchange with ledger, they are more compressed and loot better quality.

Some examples.. but pls check all TX confirmation popups and fix.

![image](https://github.com/Itheum/data-dex/assets/743169/dad25d7d-b809-459e-a022-e70d3d036923)

<img width="636" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/7e57c97d-fe5f-494b-800f-ac45493334b8">

<img width="681" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/d990fbe5-bab6-4c97-b147-c22e5bc2739a">

<img width="967" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/81ca1bb8-0bc7-45b8-ad15-071a86a6b996">
