### ISSUE TITLE
Web Wallet - Login complete successfully but in the dashboard all token balances show "spinner"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#691]
Logging in with Web Wallet, and the redirect comes back to Data DEX, all token balances in dashboard (ITHEUm balance, claims balances) show the spinning symbol. No errors but they look stuck.

You need to reload the page again for it to work

**Comment by damienen** [comment]
This is a specific issue that is happening a lot when using web wallet

**Comment by damienen** [comment]
Related to other login issues

**Comment by icegriffinguru** [comment]
Fixed.
This is not related to web wallet but ChainMeta and SmartContract constructor.
(@damienen , I pointed out code change in the pull request review in the past.)
Indeed, ChainMeta can cause some race condition issues...

**Comment by damienen** [comment]
Works. Nice! Closing
