### ISSUE TITLE
Web Wallet - Login cancel returns to Data DEX in weird state

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#692]
Web Wallet - when you try and login but your CANCEL it redirects back to the Data DEX to a route called "/abort" or "/cancelled" or something.

But the Data DEX is now in the dashboard page and stuck here. 

Behaviour:
If we get to this state, we should redirect back to the "/" (homepage)

**Comment by icegriffinguru** [comment]
It returned to "/dashboard?status=cancelled" for me.
No weird state but working fine.
@newbreedofgeek , @damienen

**Comment by damienen** [comment]
Not happening anymore, so closing
