### ISSUE TITLE
Data DEX broken in Safari browsers

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#695]
After some final testing before main branch merging, it seems the new Data DEX does not work in Safari. We need to fix it before launch.

Seems to be a RegEx issue:
<img width="1086" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/5dd5b6bd-8c2f-4d81-aaed-3d9e29a8f3f1">

@icegriffinguru I think you wrote this RegEx, can you please make it cross-browser compatible:
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

We should fix this asap, need to push to main latest tomorrow

**Comment by damienen** [comment]
Solved. Closing.
