### ISSUE TITLE
Simplify and improve the Non-Logged in defaulting of chain in the Public Marketplace and Recent Data NFTs

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#703]
- The current code works and has been shipped to main, but it should be improved and simplified, for e.g. marketplaceChain is not a prop or state variable so it should not be used in effects. also we have duplicate effects doing the same things etc.

<img width="1035" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/17c88d82-a354-4e4c-8b45-105f591aa3ca">

- Let's move the logic (checking host is datadex.itheum.io and swapping) to the centralzied methods that return APIs and Gateway endpoints

- Recent Data NFT logic also needs to be fixed

**Comment by damienen** [comment]
Easiest way to solve this is to increase number of Data NFTs fetched by the query

**Comment by icegriffinguru** [comment]
@damienen 
First issue is not found; no `marketplaceChain` variable in StoreProvider.tsx file.
Can you give me more description about second and third issues?
