### ISSUE TITLE
Minor : in dashboard route, set the menu item ENUM

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#704]
In our dashboard route, we are not setting the internal menuItem (it's undefined)... this is the setting that disables/enables the menu options.

As you can see, user can click on ""dashboard"" button again even though they are already on it.

<img width="367" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/d156acc1-a11f-45e8-beeb-4cc608c3347a">

**Comment by icegriffinguru** [comment]
If you navigate to dashboard page by clicking a menu-item, the menu item gets disabled.
However, it does not work if you refresh page.
Fixing it now.

**Comment by fuzzyduke** [comment]
Upon refreshing the page on #721 the user now sees "Dash" as disabled. However in the console, we still see menuItem Undefined, please advise.

![image](https://github.com/Itheum/data-dex/assets/121969933/67e47871-3a1e-4674-aeb3-e0b45b971739)

**Comment by icegriffinguru** [comment]
@fuzzyduke 
The expected behavior is that a selected menuitem should remain selected if you refresh the page.
console's menuitem is not relevant.

**Comment by fuzzyduke** [comment]
Acknowledged. 

Fixed, Closing.
