### ISSUE TITLE
Store bugs

### ISSUE THREAD

**Issue by Enciusan** [Itheum/data-dex#707]
After i've merged milestone i saw some weird things in app like here in marketplace when i want to procure something no data come. In wallet nft's is the same and also if i want to call any store they came undefined. Please have a look. Thank you.

<img width="638" alt="image" src="https://github.com/Itheum/data-dex/assets/92076681/86b76d1e-9e7b-44fc-b7d9-f47a648f106e">

**Comment by damienen** [comment]
Solved. Closing
