### ISSUE TITLE
Description: Itheum Balance does not show accurately. Shows as 0 even though balance exists.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#708]
Description: #663 
Itheum Balance shows as 0 even though there are Itheum tokens in the wallet.

![image](https://github.com/Itheum/data-dex/assets/121969933/813c17ef-3a9c-4a74-a4b3-713ab3efc8b1)

![image](https://github.com/Itheum/data-dex/assets/121969933/cd9a1a62-65af-42f5-b4d6-9c1aae290b36)

**Comment by damienen** [comment]
Solved. Closing.
