### ISSUE TITLE
Data NFT Marketplace: Update Fee does not function.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#709]
Description:
"Update Fee" invokes no action.

Steps to reproduce:
1. Browse to marketplace
2. Go to "My Listed Data NFTs"
3. Click on Update Fee

Expected Result:
1. Updated fee should prompt for a dialogue to change the Data NFT price. Although no dialogue is seen.

![image](https://github.com/Itheum/data-dex/assets/121969933/82fe4850-07c2-4572-87a4-2b7b2362dba6)

**Comment by damienen** [comment]
Solved. Closing.
