### ISSUE TITLE
Data NFT Marketplace: Activity section under Wallet fails to load.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#712]
Description:
In the Wallet while browsing to "Activity" section, the view fails to load.

![image](https://github.com/Itheum/data-dex/assets/121969933/cd8ba49c-d06a-4af2-85ab-c8f9ae2baafe)

**Comment by icegriffinguru** [comment]
Fixed, @fuzzyduke

**Comment by damienen** [comment]
@icegriffinguru open a PR to check the fix, please
