### ISSUE TITLE
Backend documentation

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#716]
We should have an easy to understand documentation in order for devs to be able to understand how to use the Native Authentication of the our backend

**Comment by damienen** [comment]
Any update on this, @bucurdavid ?

**Comment by bucurdavid** [comment]
I added some documentation on Native Auth here: https://github.com/Itheum/core-mx-web2-backend-service/tree/develop

**Comment by damienen** [comment]
The Swagger needs more details and we are fine

**Comment by damienen** [comment]
Solved. Closing.
