### ISSUE TITLE
Data NFT Marketplace Wallet; Purchased and Activity tabs and enabled on pr 663 but not available on STG

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#719]
Description:

"Purchased" and "Activity" tabs are enabled on pr 663 but not available on STG

![image](https://github.com/Itheum/data-dex/assets/121969933/80b982bb-8194-4eae-82a1-665dd47b9c75)

**Comment by damienen** [comment]
That's fine. Closing.
