### ISSUE TITLE
Data NFT Marketplace: Difference observed in refreshing on STG vs pr 663

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#720]
Description:
Page was refreshed 3 times on 2 seperate URLS in parallel. It was observed that all 3 times pr 663 loaded quick, however stg was timing out.
This is the final page of the Marketplace Data NFTs listing page.

https://deploy-preview-663--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/164

https://stg.datadex.itheum.io/datanfts/marketplace/market/164

![image](https://github.com/Itheum/data-dex/assets/121969933/c82dc6b9-739d-45c2-bafd-ce4769c5cd79)

Same test was carried out a few minutes later, STG was noticeably slower than pr 663.

The Wallet address was the same.

**Comment by damienen** [comment]
@icegriffinguru can you please check if there are some issues on milestone-1.1.0 that cause less stability?

**Comment by icegriffinguru** [comment]
@damienen 
It seems everything is same in both deploys except querying API.
`deploy-preview` queries "https://devnet-api.multiversx.com/query" while `stg` queries "https://devnet-gateway.multiversx.com/vm-values/query".
The latter fails more often than the former.

**Comment by icegriffinguru** [comment]
@fuzzyduke , can you find github commit of `deploy-preview` for me?

**Comment by icegriffinguru** [comment]
Query success depends on devnet state. Sometimes, denvet API is slow. Othertimes, devnet gateway is slow. Or even stuck with old data.
