### ISSUE TITLE
Datadex: Clicking on copy address in menu on STG doesn't prompt that the address is copied like on 663

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#722]
Datadex: Clicking on copy address in menu on STG doesn't prompt that the address is copied like on 663

STG
![image](https://github.com/Itheum/data-dex/assets/121969933/78571341-0172-4897-a6e7-3043db5b6fba)

663
![image](https://github.com/Itheum/data-dex/assets/121969933/cbd476d0-fd37-4d7f-870b-7ac1b448df4a)

**Comment by damienen** [comment]
That's an extra fix. It's good
