### ISSUE TITLE
It's time to get out of the dark side

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#725]
We should readd the light mode to the Data Dex

**Comment by damienen** [comment]
Notes: Use a darker shade of white so the users' eyes don't bleed

**Comment by damienen** [comment]
Try increasing contrast for elements that are harder to view in white mode

**Comment by fuzzyduke** [comment]
![image](https://github.com/Itheum/data-dex/assets/121969933/cc6ba696-dc36-48a9-8882-76272bee880f)

1. Kindly review the Itheum Logo is grey.
2. NFMe ID Avatar Card: cannot see the Coming soon text clearly.
3. The overall contrast does seem slightly off within the cards with white background and grey font. 
4. "My Claims" Card seem to have an accentuated empty space.

![image](https://github.com/Itheum/data-dex/assets/121969933/11bd3589-3d3a-4d50-b64f-4c6741088921)
1. Grey text within the card are not clearly visible.

**Comment by damienen** [comment]
I don't get the difference between what's disabled and what's available in light mode

**Comment by damienen** [comment]
Solved. Closing.
