### ISSUE TITLE
Data NFT marketplace:Listing data NFT shows long decimal value for royalty amount.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#734]
Description
Lengthy decimal place seen when listing an offer for Data NFT
Royalties % = 3.14
Price = 100
Number of Data NFTs = 1

![image](https://github.com/Itheum/data-dex/assets/121969933/0ddb45ef-a8c3-4b40-bc04-8c86b7b6ff19)

**Comment by icegriffinguru** [comment]
Fixed, @fuzzyduke

**Comment by fuzzyduke** [comment]
Verified fixed on #721 

![image](https://github.com/Itheum/data-dex/assets/121969933/eda87b59-1bd5-419f-a6b8-f033ec64090f)

**Comment by fuzzyduke** [comment]
@damienen kindly confirm the rounding up of digits, should it be rounded to the lower bound i.e., .307 instead of .308 Itheum, as the original value is .3077
