### ISSUE TITLE
Menu Option for "CanaryNet Dashboard" and clear upcoming and future guard-rails entries

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#736]
1. Add a new menu item called "CanaryNet Dashboard" to menu here

<img width="463" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/9b0c978f-507b-42d0-a200-c204eff72009">

It should appear BEFORE Logout.

- ...
- Guardrails Viewer
- Logout

When user clicks on it... use `react router's navigate()` to go to "/guardrails" (don't use a page reload via href or link)

2. clear upcoming and future guard-rails entries. How is this stored? in a local config variable? 

<img width="929" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/ea4199a9-735f-4f41-aed3-661015cfd84b">

3. (small fix) In menu -- change "View claims history" to "View Claims History" (capital letters for each word)

**Comment by Enciusan** [comment]
@fuzzyduke Please test this, thank you.

**Comment by damienen** [comment]
This looks good. Closing.
