### ISSUE TITLE
fix max list and max buy lables

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#737]
I've set the following on mainnnet.

REACT_APP_MAX_BUY_LIMIT_PER_SFT="2"
REACT_APP_MAX_LIST_LIMIT_PER_SFT="2"

When a user tries to go more than these values.. then it needs more appropriate error messages.

Currently its showing the old "not enough balance" error message.
<img width="256" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/8c5712b3-3933-490b-947e-a12a3a33d84b">

Expected behaviour:
1. Fix error labels like so: (make sure they are follow the same character case like so)
- if REACT_APP_MAX_LIST_LIMIT_PER_SFT is hit then error message should be: "Cannot exceed max buy limit"
- if REACT_APP_MAX_BUY_LIMIT_PER_SFT is hit then error message should be: "Cannot exceed max list limit"

2. Add some padding to the below of this error message. (and make sure the boxes are still at fixed height after your add padding -- so they should not jump in size or the boxes be different sizes)
<img width="260" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/672bd6fa-8b31-495c-958a-8b33e5daf6ff">

**Comment by icegriffinguru** [comment]
Fixed, @fuzzyduke
