### ISSUE TITLE
Table in Details Page is showing first listing price instead of last

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#739]

**Comment by bucurdavid** [comment]
<img width="1339" alt="image" src="https://github.com/Itheum/data-dex/assets/46384319/4a61c76e-5e67-41f6-abb6-2424e7318b22">
here @damienen @fuzzyduke ?

**Comment by damienen** [comment]
Hmm, there was an instance in which the first price was displayed from the second page

**Comment by bucurdavid** [comment]
![image](https://github.com/Itheum/data-dex/assets/46384319/9c5c820c-beeb-40ae-a711-5249cb33b4ab)

This takes the last `addOffer` transaction price. But I think a better way would be to wait for the backend and show a list of offers for the Data NFT.

**Comment by damienen** [comment]
First thing:
[10 instead of 10.2](https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197)

Add the price for which addOffer was added between brackets

**Comment by bucurdavid** [comment]
There is a problem with the store in data dex, because sometimes when market requirements are loading first from the store the price is 10.2. @damienen @icegriffinguru

**Comment by icegriffinguru** [comment]
@bucurdavid 
Which store variable do you mean?
What do you fetch it for?

**Comment by bucurdavid** [comment]
https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197

this should show 10.2 instead of 10. I managed to get 10.2 after more refreshes.

```
 function getTokenHistory() {
    const apiUrl = getApi(_chainMeta.networkId);
    axios
      .get(`https://${apiUrl}/nfts/${tokenId}/transactions?status=success&function=addOffer&size=1&receiver=${_chainMeta?.contracts?.market}`)
      .then((res) => {
        const txs = res.data;
        if (txs.length > 0) {
          const tx = txs[0];
          const hexPrice = Buffer.from(tx.data, "base64").toString().split("@")[8];
          let _price = 0;
          if (hexPrice.trim() !== "") {
            _price = parseInt("0x" + hexPrice, 16);
            if (marketRequirements) {
              _price += (_price * marketRequirements.buyer_fee) / 10000;
            }
          }
          setPriceFromApi(_price);
        } else {
          setPriceFromApi(-1);
        }
        setIsLoadingPrice(false);
```

**Comment by damienen** [comment]
Closing for now. Seems good, will monitor.
