### ISSUE TITLE
Details page opening should be more user friendly

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#740]
From marketplace or wallet

**Comment by fuzzyduke** [comment]
Kindly provide context on implementation.

**Comment by Enciusan** [comment]
We had to make more visible that a details page of nft's exists so i've added a nice transition on hover image.

**Comment by fuzzyduke** [comment]
Verified. Passed.

Observations.
1. Details button seen on mouseover on image of Data NFT card. Not seen on mouseover of any other part within the card.
2. Popup encountered on click showing Data NFT details.

![Image](https://github.com/Itheum/data-dex/assets/121969933/f0890292-2d7f-48b4-975f-7af14d6f12d1)
