### ISSUE TITLE
Add an "adanvced" mode in the settings page which allows the user to view or preview data on devnet

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#741]
This should be saved in a session storage

**Comment by icegriffinguru** [comment]
Switch Component

**Comment by fuzzyduke** [comment]
Verified Fixed on #721 
Preview Data and view data available on listing and detail of Data NFT

**Comment by damienen** [comment]
Should be moved to settings page

**Comment by damienen** [comment]
Solved. Closing.
