### ISSUE TITLE
Data NFT Marketplace still showing devnet data when user not logged in

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#742]
We made a fix to this but seems to have regression.

Problem:
- User is not logged in and is on our production domain datadex.itheum.io
- User goes to "Market" : https://datadex.itheum.io/datanfts/marketplace/market
- User sees devnet data nfts

Expected behaviour:
- User sees mainnet data nfts  - so nothing will be shown
- User sees the mainnet message for "market is currently paused"

**Comment by damienen** [comment]
Solved. Closing
