### ISSUE TITLE
Prepare data-dex for Trailblazer

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#756]
- [x] Have a button inside the Data NFT Wallet, detect the trailblazer ID in the Data NFT tile and then a button to the trailblazer app on explorer to open in a new tab. Button can say "Explore". (Check if identifier is X, if yes, have a button that allows the user to go its relevant explorer page. It can be a small badge near the identifier.)

- [x] On the Marketplace, detect the trailblazer ID on a Data NFT tile and a button to say "Explore". Again this trailblazer app on explorer. (Same implementation for as above)

**Comment by icegriffinguru** [comment]
@damienen 
I pushed an update but not sure I've done what you exactly want. Plz check.

**Comment by damienen** [comment]
The 2nd item does not seem to be working. The explore button is not shown on the marketplace

**Comment by icegriffinguru** [comment]
Fixed 2nd point

**Comment by damienen** [comment]
Works. Closing. Nice stuff, @icegriffinguru !
