### ISSUE TITLE
We need to have some protected routes

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#767]
There are some routes that should only be accesible whenever the user is logged in.

You can use AuthenticatedRoutesWrapper from sdk-dapp.

These routes would be wallet view, dashboard, trade data view for now. If you think there's anything extra let me know.

**Comment by icegriffinguru** [comment]
Done

**Comment by damienen** [comment]
@fuzzyduke you should check that these routes are not available unless you are logged in

**Comment by fuzzyduke** [comment]
Verified. Implemented. Passed.

Routes previously accessible on previous versions are not available on #789 
Wallet view, dashboard, trade data.

**Comment by damienen** [comment]
This error is fine for now, user is still redirected to where they should be. We will review this once chainMeta is not present anymore
