### ISSUE TITLE
Details Page is broken

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#769]
Need to test and fix both these uses-cases:

Non Logged In view:
- Go Home, then to Recent Data NFTs and then click on 1st item
- You get this error
<img width="1260" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/3e977356-8ef3-4c28-8464-3a04ee261a9a">

Logged in view:
- Go got Wallet and click on items to open details view drawer:
- You get this error
<img width="1107" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/09180077-4efd-498f-b74d-e554d1ff1993">

- Same with the Marketplace view:
<img width="1074" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/0958a37e-cd2e-4a6a-97c7-7661c741ed0d">

**Comment by newbreedofgeek** [comment]
Other issues:

1. In Wallet View, when the details drawer opens up... the "View" needs to go direct to the **offer link** in a "new browser"

<img width="1266" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/03e18203-d869-408c-8c30-e107c587c8e2">

i.e. it should open this in a new tab:
https://deploy-preview-754--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/DATANFTFT4-3ba099-0197/offer-1951

It has to go direct into the **offer**

**Comment by newbreedofgeek** [comment]
2. In the full screen details page. 

e.g.
https://deploy-preview-754--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/DATANFTFT4-3ba099-0197

There are some issues:
1. Change "Purchase Data" to "View Offer"
2. Some issues with routing - https://www.loom.com/share/73c506f5393f479cbb5edc51b9bf9019

**Comment by newbreedofgeek** [comment]
Also add support for:

```
REACT_APP_ENV_BACKEND_DEVNET_API
REACT_APP_ENV_BACKEND_MAINNET_API
```

**Comment by Enciusan** [comment]
@fuzzyduke If you can have a look here and then close it? Thank you.

**Comment by fuzzyduke** [comment]
Hey there @Enciusan, the detail pages now load correctly for various scenarios for logged in and non logged in users. View and view offers get redirected correctly the the right offer pages.

Points for clarification, as per one of the requirements mentioned above;
1. If we are on a detail page, clicking on "View Offer" should not open in a new tab, currently it does. Please clarify

**Comment by fuzzyduke** [comment]
Verified. Fixed.
