### ISSUE TITLE
Wallet - Activity: Burning and listing actions do not show in the activity tab.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#770]
1. Burning and listing Actions of NFTs do not show in the Activity tab of the wallet for a user.

![image](https://github.com/Itheum/data-dex/assets/121969933/3a4c9de4-12cf-4561-96a1-1d7979da6e10)

**Comment by bucurdavid** [comment]
Just tested it and it's working.
![Image](https://github.com/Itheum/data-dex/assets/46384319/1c262424-a114-4818-9003-3417e490ec56)

**Comment by damienen** [comment]
@fuzzyduke please either add some steps to reproduce or close this as unreproducable

**Comment by fuzzyduke** [comment]
Reviewed. Passed. 

Not reproducible.
