### ISSUE TITLE
HotFix : "Other" Offers should appear on all details pagess

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#787]
The "offer" box you see here: https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197

<img width="777" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/436ec5ce-270e-4411-aaf8-90d8712966ef">

Should appear in all details pages (even the pages with the offerID in the URL). e.g.
https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197/offer-1967

But if the user is in the above offerID url page, change the title to "3 Other Offers".

This behaviour should also happen in drawer mode of details pages

**Comment by damienen** [comment]
Closing.
