### ISSUE TITLE
Change details drawer to details modal

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#793]

**Comment by fuzzyduke** [comment]
The description on mobile seems truncated for a higher amount of text.

Device: android, vivo Y15s

![image](https://github.com/Itheum/data-dex/assets/121969933/014fcdbd-064c-4b06-ae08-0c4f5082f89f)

**Comment by damienen** [comment]
When clicking on recent data nfts on this branch I get 404.

**Comment by damienen** [comment]
Unreproduceable on other phone models and is not a very popular one so closing until further notice.
