### ISSUE TITLE
Change offers source on the marketplace to our internal API

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#794]
Right now we are fetching offers from the MX gateway, directly from the SC.

We should fetch offers from our internal API IF THE API is available.

If the API is not available, we should fetch from the MX gateway.

We already have such behavior in the data-dex (check if API is available and have fallback behavior if not) so you can check with @Enciusan to see how to do it. It's called ConditionalRender. @bucurdavid also have such a component, but for functional callback

Please talk to them to see what's best to use in your case.

**Comment by icegriffinguru** [comment]
This is original OfferType queried from SC.
```
export interface OfferType {
  index: number;
  owner: string;
  offered_token_identifier: string;
  offered_token_nonce: number;
  offered_token_amount: string;
  wanted_token_identifier: string;
  wanted_token_nonce: number;
  wanted_token_amount: string;
  quantity: number;
}
```

This one is David's backend API offer type
```
export interface BackendOfferType {
  id: 0,
  index: number,
  identifier: string,
  nonce: number,
  title: string;
  description: string,
  wanted_token: string,
  price: number,
  listed_supply: number,
  owner: string;
}
```

I can't find a solution to convert from backend offers to SC offers.
We need to keep consistency in data types.
@damienen , what do you think?

**Comment by damienen** [comment]
To me it seems that the type from backend can be mapped to our current type.

index => index
identifier => offered_token_identifier
nonce => offered_token_nonce
wanted_token => wanted_token_identifier,wanted_token_nonce
price => wanted_token_amount
listed_supply => offered_token_amount

But yes, it is confusing. It's best @bucurdavid modifies his stuff on API level to fit the current data type

**Comment by bucurdavid** [comment]
@icegriffinguru  Api is updated

**Comment by bucurdavid** [comment]
@icegriffinguru API updated

**Comment by icegriffinguru** [comment]
Updated

**Comment by damienen** [comment]
These errors are occuring:
This is because you have two slashes in the request. Please check
![Image](https://github.com/Itheum/data-dex/assets/44813558/847b183a-c71e-4c96-8b83-e99774946d6c)

**Comment by bucurdavid** [comment]
@damienen we should remove the `/` from env and code:

```typescript
await ${this.api}health-check
```
to 
```typescript
await ${this.api}/health-check
```

**Comment by newbreedofgeek** [comment]
@icegriffinguru let's remove / from ENV var.

pls check and add slash to other user cases on this ENV so we don't break it.

**Comment by icegriffinguru** [comment]
Removed slashes.

**Comment by damienen** [comment]
Works. Closing
