### ISSUE TITLE
Guard-rails > "Whitelisted Addresses" not working as intended

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#797]
Just deployed v1.2.0 to Mainnet, and logged in with a Mainnet wallet.

There is one address that is whitelisted to mint Data NFTs and that address should appear here.

Can we somehow get this directly from the Minter smart contract and show it here.

<img width="1042" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/41c0d8ca-2ae5-4942-8676-2da3ab3368d1">

CC @damienen

**Comment by damienen** [comment]
You can use getWhitelist to get the addresses:
https://github.com/Itheum/itheumcore-elrond-data-nft-minter/blob/bca1fe7e9c7b64d4c981e7a278bc04e9c2895789/src/storage.rs#L74

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
Mainnet login shows below. Verified. fixed. 

![Image](https://github.com/Itheum/data-dex/assets/121969933/0686c176-71fb-49e2-b77e-061265428fdf)
