### ISSUE TITLE
When no data for claims or NFT transactions models, we need to style it better

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#798]
Where there is no data yet for these 2 models:

<img width="1539" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/b5162a87-9d76-420c-825e-657fb03217cb">

<img width="1646" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/740b1c3a-b995-4e6a-8257-207cfa697bf4">

- Add some minHeight to the body
- Show our "Nothing here yet" components. 
- The UI should look similar to this

<img width="1428" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/52e10a63-3da2-4312-ba09-e2d09f1b3016">

CC @damienen

**Comment by damienen** [comment]
Component that needs to be modified:
https://github.com/Itheum/data-dex/blob/main/src/components/Tables/Components/DataTable.tsx

**Comment by fuzzyduke** [comment]
Detail doesn't load. #789 

![image](https://github.com/Itheum/data-dex/assets/121969933/a309c1d6-053b-440c-9caa-b155c884e31c)
