### ISSUE TITLE
Data NFT Details Page, "offers" section is not mobile friendly.

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#805]
Data NFT Details Page, "offers" section is not mobile friendly.

<img width="343" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/ea9dd22f-7633-40c9-8511-af319a27610a">

Please check and make it support mobile, tablet and desktop.

**Comment by fuzzyduke** [comment]
Verified. Fixed.
