### ISSUE TITLE
Data NFT Marketplace: Accessing an offer that doesn't exist should have a proper UI Message for users.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#827]
Description:

Below is seen when an invalid offer is invoked on mainnet.

For example 

https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197/offer-2010

![image](https://github.com/Itheum/data-dex/assets/121969933/bf10e63b-bf8f-4429-88bb-ff44e4075f23)

**Comment by fuzzyduke** [comment]
Current view on #897 , please clarify.

![image](https://github.com/Itheum/data-dex/assets/121969933/d767a79d-e95b-410b-9ec2-7cb5a2c03031)

**Comment by newbreedofgeek** [comment]
- Change the 2nd line to "We are showing Data NFT Details and other available offers below"
- Make it stay on screen and not go away automatically

@Enciusan

**Comment by fuzzyduke** [comment]
Verified Fixed.

Item stays on the page till closed.

![image](https://github.com/Itheum/data-dex/assets/121969933/2b0443bc-9500-4163-a5af-aa0ed8c32760)
