### ISSUE TITLE
Elrond - Login Web Wallet (Maiar/Ledger)

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#83]
Elrond Login through Web Wallet using Maiar or Ledger does not allow the user to send transactions

**Comment by newbreedofgeek** [comment]
Escalated to Elrond - https://github.com/ElrondNetwork/dapp-core/issues/200

**Comment by damienen** [comment]
We should close this as the fix will come from Elrond with web wallet 2.0, not from us. @newbreedofgeek
