### ISSUE TITLE
Data NFT Marketplace : When buying a Data NFT, the Itheum balance is reset to 0 (and appears after TX is complete)

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#830]
Setup:
- I had some ITHEUM token balance. e.g. 10 ITHEUM
- I went to the marketplace and bought a Data NFT from someone else

What Happened:
- When the TX was running the ITHEUM token balance on header became 0.00 ITHEUM. Like so:
<img width="1193" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/d7b541c4-9177-4d79-b4c6-1ba1e180c362">
- After the TX was complete, the token balanced fixed it self and no longer showed 0.00 ITHEUM.

What Should happen:
- It should not reset to 0.00 during a TX. The current header token balance should just stay the same as before the TX ran. e.g. 10 ITHEUM
- Once the TX complete, we refresh the token balance like we usually do to show reduced token count

**Comment by icegriffinguru** [comment]
@newbreedofgeek , I can't reproduce the issue.
I've checked code in StoreProvider and AppHeader but everything looked fine.
@damienen , Have you ever experienced such issue?

**Comment by damienen** [comment]
@fuzzyduke see if you can reproduce it and give steps if possible

**Comment by Enciusan** [comment]
I can't reproduce neither.

**Comment by damienen** [comment]
Closing then, at least for now
