### ISSUE TITLE
Make the Data Dex apps unavailable in mainnet

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#831]

**Comment by fuzzyduke** [comment]
Join has been removed from Apps Marketplace section.

![image](https://github.com/Itheum/data-dex/assets/121969933/2f9ca5c4-2347-4bcc-b636-49adc69a3d9b)

However, Red Heart Challenge details page does have a "Join Now", Kindly advise 

![image](https://github.com/Itheum/data-dex/assets/121969933/52d5dc70-2fc6-488a-a1d2-6f69446afb0e)

**Comment by fuzzyduke** [comment]
Also, Supported Data CAT Programs are seen on Mainnet on #821 .

https://deploy-preview-821--frosty-hermann-85ca4f.netlify.app/tradedata

![image](https://github.com/Itheum/data-dex/assets/121969933/c9864c07-1c06-495b-9326-6bd006340fb4)

**Comment by newbreedofgeek** [comment]
> Also, Supported Data CAT Programs are seen on Mainnet on #821 .
> 
> https://deploy-preview-821--frosty-hermann-85ca4f.netlify.app/tradedata
> 
> ![image](https://user-images.githubusercontent.com/121969933/256027019-c9864c07-1c06-495b-9326-6bd006340fb4.png)

@bucurdavid no need to fix this as I'm fixing it now as a hotfix on production

CC @fuzzyduke

**Comment by damienen** [comment]
Solved. Closing.
