### ISSUE TITLE
Make sure Fonts are all aligned with our UI/UX standards

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#833]
Align with harbsy and come up with 'primary' and 'secondary' fonts for all our UI web apps.

**Comment by damienen** [comment]
https://chakra-ui.com/docs/styled-system/customize-theme

**Comment by damienen** [comment]
@Enciusan which are those primary and secondary fonts?

**Comment by Enciusan** [comment]
Clash display for headings and satoshi for texts stuff

**Comment by damienen** [comment]
Works. Closing.
