### ISSUE TITLE
Redesign horizontal scroll bar for tabs in marketplace

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#838]
"While on mobile, If you are not aware that you have to switch between public marketplace and your listed data nfts, it's hard to find it." - Community Member

"My suggestion. Make the "buttons" smaller on mobile to fit both in only one view." - a wise man (@BogdanCostinas)

![Image](https://github.com/Itheum/data-dex/assets/44813558/76a34472-5b33-4822-9d90-9625367ec497)
![Image](https://github.com/Itheum/data-dex/assets/44813558/7f0fcf5f-80bd-4117-a732-4de6d70baf2b)

**Comment by fuzzyduke** [comment]
Both tbs are visible on #857
