### ISSUE TITLE
When there are no offers - it should not show "Price" and "Quantity"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#848]
It should instead show our "NoDataHere" component.

<img width="918" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/95447462-bcfc-4c7a-bb79-a0297855009e">

**Comment by fuzzyduke** [comment]
Below seen on branch



![Image](https://github.com/Itheum/data-dex/assets/121969933/8182ee99-bbc2-4eb7-b9c8-295db273a0d9)
