### ISSUE TITLE
Elrond - History of claims

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#85]
Users should be able to see a history of their last transactions in which they got claims,

**Comment by newbreedofgeek** [comment]
Let's differ this to a future release after we take the current version `v0.4.0` to Mainnet.

How we could do it:
- In the Data DEX we have a menu item for "Chain Transactions"
- If user is in Elrond mode and goes here, we can query events/past transactions from user's wallet and show their past claims.
@damienen do we have the appropriate on-chain event/logging from the claims contract for us to be able to do this in the near future?

**Comment by newbreedofgeek** [comment]
https://github.com/Itheum/data-dex/commit/65674fe946f0d1f9a50e79557ba5d779ca7b119b
