### ISSUE TITLE
If API for max fee is down, then "List X NFT for Y Itheum" should be disabled.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#852]
Currently in the API to check Max fee is available, and if a fee is set beyond the max fee, then we see a warning message.
However, if the API is not available then a user can enter a value beyond the max fee and click on List NFT.

Implementation of a flow is required wherein; if the API that retrieves max fee is down, then the List NFT button should be disabled.

![image](https://github.com/Itheum/data-dex/assets/121969933/2c2f96ea-f0af-459b-b21e-97947f445cc0)

**Comment by damienen** [comment]
Done. Closing.
