### ISSUE TITLE
Misc Small UI Fixes Issues 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#861]
Misc issues in a thread...

**Comment by newbreedofgeek** [comment]
These curved edges have some color bleeding over

https://deploy-preview-859--frosty-hermann-85ca4f.netlify.app/

Overflow: hidden should fix it

**Comment by newbreedofgeek** [comment]
In the details page, Need some space between the "copy link" icon and the green price line

<img width="414" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/cbd630d4-1d93-4bec-ba76-9cd73a64f9a1">

**Comment by newbreedofgeek** [comment]
On Devnet,

Something weird happening with "Offers" box on this Data NFT
https://deploy-preview-859--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/DATANFTFT4-3ba099-0173

<img width="1238" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/4210e772-7fca-40c3-9601-faa8c6bd820a">

**Comment by newbreedofgeek** [comment]
Offers BOX should not have "space between" or "space even". It should just appear like the table with rows.. i.e. aligned to top

<img width="431" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/3b2d6e68-19ff-406e-b40f-7d943a6b7a74">

**Comment by newbreedofgeek** [comment]
Settings route is broken

https://deploy-preview-859--frosty-hermann-85ca4f.netlify.app/settings

<img width="1154" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/de47dc58-9d5b-44e6-8ea7-b47197950a63">

**Comment by newbreedofgeek** [comment]
Go to "Market":
/datanfts/marketplace/market

Click on "My Listed Data NFT(s)", the URL becomes : /datanfts/marketplace/my

<img width="1484" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/61e45df9-045f-4315-8f4b-cb23c95cc2d4">

then reload page, URL still stays on `/datanfts/marketplace/my` 
<img width="1171" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/f9be64a6-1011-4d6b-9023-8bc166834682">

Expected Behaviour:
- if the route is `/marketplace/my` just redirect to `/marketplace`

**Comment by damienen** [comment]
Solved. Closing
