### ISSUE TITLE
With the Web API now sowing Marketplace Content, any updates don't update on UI as it happens

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#862]
If I update price on Data NFTs, the update down not show on the UI for a few minutes - https://www.loom.com/share/ae6cc4e8e31d462d961a1649d1259c53

This will confuse users who may try and do the action again and again.

Not sure what the ideal UX is... we need to discuss.

**Comment by newbreedofgeek** [comment]
Soltuion:

@bucurdavid to produce health-check that takes param ?marketplace=1
And this will return the "health-check" for the marketplace... in this case it should be false

@icegriffinguru 

To replicate the current data dex health-check store code that checks if API is up or down... BUT, here it checks if 'Marketplace' is up or down via above health-check?marketplace=1 and then fallback the marketplace ONLY to web3 api

**Comment by bucurdavid** [comment]
@newbreedofgeek 
![image](https://github.com/Itheum/data-dex/assets/46384319/7dd80439-ddc0-4842-a25b-f22331ad559c)

**Comment by damienen** [comment]
Solved
