### ISSUE TITLE
Settings route is broken

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#865]
Settings route is broken

https://deploy-preview-859--frosty-hermann-85ca4f.netlify.app/settings

<img width="1154" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/de47dc58-9d5b-44e6-8ea7-b47197950a63">

_Originally posted by @newbreedofgeek in https://github.com/Itheum/data-dex/issues/861#issuecomment-1657474434_

**Comment by damienen** [comment]
Solved.
