### ISSUE TITLE
 if the route is `/marketplace/my` just redirect to `/marketplace`

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#866]
Go to "Market":
/datanfts/marketplace/market

Click on "My Listed Data NFT(s)", the URL becomes : /datanfts/marketplace/my

<img width="1484" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/61e45df9-045f-4315-8f4b-cb23c95cc2d4">

then reload page, URL still stays on `/datanfts/marketplace/my` 
<img width="1171" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/f9be64a6-1011-4d6b-9023-8bc166834682">

Expected Behaviour:
- if the route is `/marketplace/my` just redirect to `/marketplace`

_Originally posted by @newbreedofgeek in https://github.com/Itheum/data-dex/issues/861#issuecomment-1657751885_

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
Upon refreshing https://deploy-preview-882--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/my the page stays on /market/my it doesn't currently redirect /market on #882
