### ISSUE TITLE
Intermittent login failure seen on Datadex.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#869]
Upon attempting to log in, there are instances where after selecting the wallet, no further action is seen. Instead we see the wallet selection again. Please look at the console message saying "Login cancelled".

Steps to reproduce.
1. Click on connect wallet.
2. Select "Defi Wallet"
3. Select your address in the wallet.

Kindly note you may have to repeat this a few times or refresh your page before a login attempt to reproduce.

![image](https://github.com/Itheum/data-dex/assets/121969933/b80fec6a-8ab0-408f-a825-28c87b1f537d)

**Comment by damienen** [comment]
This should get better once we ditch chainMeta
