### ISSUE TITLE
Delist and update price doesnt reflect after auto reload, only reflect after manual refresh.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#872]
After delisting or updating price, there is a reload of cards seen, however the amounts stay the same. 
It is only after a manual refresh of the page that the listed count or Unlock fee are seen to reflect correctly.

Steps to reproduce
1.  Browse to market
2. Navigate to "My Listed Data NFTs"
3. Delist 1 out of 1+ Data NFTs. 
4. Update Price of the Data NFT
5. Review numbers after auto reload.

Actual behavior
1.  Numbers of Listing count and Updated price are not reflected post the updates.

Expected behaviour
1. Numbers should reflect correctly after autoreload of cards.

![image](https://github.com/Itheum/data-dex/assets/121969933/014418fe-6b4f-4c3e-aaea-5312dd079170)

**Comment by icegriffinguru** [comment]
@damienen 
If API is up, UI will fetch old offers from API instead of SC just after update transactions.
Backend is not responsive with updates.

**Comment by damienen** [comment]
Shouldn't the marketplace offers, including my listed, only be fetched from API if that variable with "is api marketplace up" is true?

**Comment by icegriffinguru** [comment]
Fixed.

**Comment by fuzzyduke** [comment]
Verified. Fixed.
