### ISSUE TITLE
For non logged in user on Mainnet, Preview data is not available in the Market.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#883]
For non-logged-in users on Mainnet, Preview data is not available in the Market. Message is seen "Preview Data is disabled on Devnet"

Steps

1. Browse to [Mainnet
](https://datadex.itheum.io/datanfts/marketplace/market)
2. Click on Preview Data.

-ZK

![image](https://github.com/Itheum/data-dex/assets/121969933/d476859b-d1f5-45fe-bf24-236ac88ec00c)

**Comment by fuzzyduke** [comment]
Kindly open it in a Private Window.

**Comment by damienen** [comment]
Good catch

**Comment by fuzzyduke** [comment]
Hi @damienen could we kindly have a Hotfix on this before Tuesday 8th of August 2023.

**Comment by damienen** [comment]
Solved. Closing.
