### ISSUE TITLE
Error seen when using web wallet to View Data on Data NFT in wallet.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#886]
While attempting to "View Data" on DataDex STG the below error is seen.

Steps
1. Log in with Web wallet on the Data Dex
2. Go to the wallet section
3. Click on View data
4. Sign transaction in web wallet

Actual behaviour:
1. After signing the transaction upon redirecting back to the datadex no action is seen.

Expected Behaviour
1. After singing the transaction upon redirecting back to the datadex, the File should be downloaded.

![image](https://github.com/Itheum/data-dex/assets/121969933/be91c4f1-97ff-43b6-bd91-cbec7aa6cbbb)

**Comment by damienen** [comment]
Solved. Closing.
