### ISSUE TITLE
Web Wallet: Upon Updating the price of a listed data NFT and signing the transaction, the redirection back to the page is to the wrong tab.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#890]
Description

Updating price of a listed item via webwallet causes broken UI when redirecting back to the My Listed Data NFT tab.

Step 1
1. Log in with web wallet
2. Browse to Market
3. Update Price
4. Sign the transaction in web wallet

Actual behavior
1. Redirection is seen back to the "Public Makerplace" tab instead of the "My listed Data NFT" tab.
2. The 3 Listed data NFTs are seen under the Public Marketplace which is wrong. It should show all marketplace items.

Expected behaviour
1. After signing the transaction, redirection should be returned to the "My Listed Data NFTs" tab.

![image](https://github.com/Itheum/data-dex/assets/121969933/a64c3637-4497-4485-a3b9-56a20b8dab7f)

**Comment by damienen** [comment]
@icegriffinguru see if you can reproduce after your latest solved on the marketplace/ and marketplace/my

**Comment by icegriffinguru** [comment]
It's working, @damienen.

**Comment by damienen** [comment]
Great. Closing.
