### ISSUE TITLE
Improve View Data "sign message" prompt

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#904]

**Comment by vmradulescu** [comment]
![image](https://github.com/Itheum/data-dex/assets/141028717/f1e80615-1f66-4bf6-b771-214b280b2a7b)

Currently, the prompt seen when the transaction is requested is above. For xportal, there has to be a clear message, similar to what we currently have in the Itheum Explorer.

**Comment by damienen** [comment]
1. Change "transaction" to "message"
2. Add the "Please sign the message using xPortal or Ledger" if the person is logged in with xPortal or Ledger
