### ISSUE TITLE
Devnet MVX explorer invoked from mainnet in Market item.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#905]
While navigating to explorer details from datadex - prod, the below gets redirected to devnet mvx explorer.

![image](https://github.com/Itheum/data-dex/assets/121969933/835fbcd6-f32e-4a44-81e5-d9ba7fc52e18)

**Comment by damienen** [comment]
While solving this issue I took the time to route all chainID usages

**Comment by fuzzyduke** [comment]
Verified. Fixed.

Accurate redirection seen while accessing #915 on mainnet for all the fields mentioned.

![image](https://github.com/Itheum/data-dex/assets/121969933/bf0dc0c2-eeba-481c-a91c-2b4ed6dbb4c9)
