### ISSUE TITLE
When on an offers page, there has to be some indicator to the user on whether they hold the Data NFT before purchasing.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#917]
When visiting the main collection page, there is no way for a user to know whether they already own the item. They may then end up rebuying without knowledge they already possess the Data NFT.

![image](https://github.com/Itheum/data-dex/assets/121969933/468398cd-307e-4b7c-8943-8b8442c4171a)

**Comment by fuzzyduke** [comment]
This wallet has an Itheum TB, however, there is no indicator.

![image](https://github.com/Itheum/data-dex/assets/121969933/00173398-ba2e-45a6-a3a0-cc0fe4748a4b)

**Comment by damienen** [comment]
The badge should say "You already own this"

**Comment by fuzzyduke** [comment]
Verified Fixed.
