### ISSUE TITLE
View data with web wallet causes error.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#919]
Signing with web wallet while viewing data invokes the below on #915

This is while viewing data from the wallet section.

![image](https://github.com/Itheum/data-dex/assets/121969933/fda2f4a9-27e2-4f0d-8278-eb785429023d)

![image](https://github.com/Itheum/data-dex/assets/121969933/755549be-4dae-4cac-a96f-0799f452a723)

**Comment by icegriffinguru** [comment]
I've tested web-wallet on branch milestone 1.4.0 but it worked fine with multiple viewData signings.
@fuzzyduke

**Comment by damienen** [comment]
@fuzzyduke see if you can reproduce on https://github.com/Itheum/data-dex/pull/859

else close it

**Comment by fuzzyduke** [comment]
Not Reproducible. Closing.
