### ISSUE TITLE
After logout and logged back in, $Itheum token balance is not refreshing

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#93]
Describe the bug:
I logged out of the Itheum platform and logged back in, refresh my page and my $Itheum token isn’t displaying again instead it is showing a zero balance

Expected behavior:
I should still see my $ITHEUM whenever i log back into the Dapp

Desktop 

OS: [e.g. Windows]

Browser [Microsoft Edge]

Version [103.0.1264.37]

**Comment by newbreedofgeek** [comment]
Look at https://github.com/ElrondNetwork/dapp-core#reading-user-state

**Comment by damienen** [comment]
Solved in https://github.com/Itheum/data-dex/commit/cea6cbd81614787b4521bb09770ecf02dfb87461

**Comment by newbreedofgeek** [comment]
Confirmed to be fixed with https://github.com/Itheum/data-dex/commit/a76b7fad8b06d331f67e8f528cbec560de5ab97d
