### ISSUE TITLE
Preview Data NOT working on Mainnet Non-Logged in View

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#934]
In non-logged in view, a page like this:
https://datadex.itheum.io/datanfts/marketplace/DATANFTFT-e936d4-03/offer-164

Has preview Data disabled.. which is wrong.

<img width="759" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/b5a83ae0-0740-4e6c-b35c-6c1783bfd684">

**Comment by fuzzyduke** [comment]
Verified fixed.
