### ISSUE TITLE
Weird "Nothing here yet..." and "offer" overlap on details page

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#936]
![image](https://github.com/Itheum/data-dex/assets/743169/75b48231-76c5-4f5a-bf72-4ca117fba57e)

**Comment by Enciusan** [comment]
This is fixed on my branch once we merge this will be fixed.

**Comment by newbreedofgeek** [comment]
Pls test on https://github.com/Itheum/data-dex/pull/897

**Comment by fuzzyduke** [comment]
Verified fixed on #897 

Only 1 offer on marketplace

![image](https://github.com/Itheum/data-dex/assets/121969933/029a7d9e-65ce-40c3-b513-18bf8587807b)

On collection page the single offer is seen

![image](https://github.com/Itheum/data-dex/assets/121969933/e25947db-a162-42c6-ba44-965c515bcc33)
