### ISSUE TITLE
Data NFT Marketplace + Wallet: Enable the Data DEX to support "Multiple Data NFT collections"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#939]
# This ticket will need a UI design from @harbzy 1st before dev work starts. @fuzzyduke can do the Product Specs #

Currently, we ONLY hardcode a single Data NFT collection in contractAddresses and use this in the various sections of the Data DEX. But we are moving to a multi collection design. Allowing multiple Data NFT and Data SFT collections to be traded in a single user interface. Currently, we support the "SFT" design where you can list "multiple of the same", but we can also support "NFT" design, where you can ONLY list 1.

## Currently Behaviour: ##
**Data NFT Wallet:**
- We only show user's data nfts from the single collection and let them burn/mint etc

**Data NFT Marketplace :**
- We only allow user to trade data nfts from the single collection and let them buy, de-list, update price etc

## Expected Behaviour: ##
- contractAddresses should support an array of Data NFT collections.
dataNFTFTTicker: ["DATANFTFT-e936d4", "INSP-a65b3b"] // these can be NFT and SFT tokens

**Data NFT Wallet:**
- We show user's data NFTs from all supported collections
- Burn: These collections can be either NFT or SFT, so "burn" might need different UX for both (let's discuss)
- Tile View / Details View: These collections can be either NFT or SFT, if it's NFT, then we dont need the "pick multiple and list" options. We just show "list 1 option"
- List to Marketplace: As above, depending on NFT vs SFT the "list UX" need to change

**Data NFT Marketplace :**
- Buy / Tile View / Details View: : These collections can be either NFT or SFT, if it's NFT, then we dont need the "pick multiple and buy" options. We just show "buy 1 option"
- Delist : Based on SFT or NFT, we allow user to pick multiple supply or only 1 
- Update Price: UI needs to change based on SFT or NFT

Note: This ticket does NOT cover "minting" of NFT vs SFT standard, this can happen in a seperate ticket.

**Comment by newbreedofgeek** [comment]
can move to 1.6 as well...

**Comment by damienen** [comment]
Duplicate. Closing
