### ISSUE TITLE
When Elrond API is down - we need to show error dialog to user

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#94]
e.g. When devnet or mainnet API is down returning 404 or 500 etc - we need to show error message to user. We need to show an easy to understand error message.

**Comment by newbreedofgeek** [comment]
You can use this error dialog https://github.com/Itheum/data-dex/blob/feature/%2364-elrond-login/src/App.js#L751

**Comment by damienen** [comment]
Solved in https://github.com/Itheum/data-dex/commit/f862fc89758137940cd7274391190bfd5818e1ef
