### ISSUE TITLE
Enable NativeAuth on Sdk Dapp

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#941]
- Add the NativeAuth setting for DappCore login buttons
- When the user clicks on "Explore" buttons on Data NFTs, attach the NativeAuth token to the Explorer links. This is to the Explorer app can support this feature - https://github.com/Itheum/explorer-dapp/issues/128
- When attaching the "token" to the URL, follow the exact same spec as the xPortal Hub spec so it's uniform in design.

**Comment by damienen** [comment]
DappCore -> sdk-dapp

**Comment by damienen** [comment]
Passing the link to "Explore" button will be done in another ticker in 1.6.0

So, if you enable sdk-dapp native auth in login buttons it is enough to review this as issue as done and close it, @icegriffinguru

**Comment by damienen** [comment]
Works. Closing.
