### ISSUE TITLE
Offers BOX should be "aligned to top" and Not spaced out like "space between". Align to UI/UX design doc from harbsy

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#942]
<img width="431" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/3b2d6e68-19ff-406e-b40f-7d943a6b7a74">

**Comment by Enciusan** [comment]
This is fixed on my branch once we merge this will be fixed.

**Comment by newbreedofgeek** [comment]
Pls test on https://github.com/Itheum/data-dex/pull/897

**Comment by fuzzyduke** [comment]
Verified fixed
Items are top aligned.

![image](https://github.com/Itheum/data-dex/assets/121969933/41b17017-c25f-484a-bbe4-b31f92ea2b0d)
