### ISSUE TITLE
Issue with Creator Page on Mainnet

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#948]
I tested by connecting a Mainnet wallet (as devnet may have issue)

- When you go to the Creator page, there are blank tiles and javascript errors are throwing.

See video : https://www.loom.com/share/066e4084e1664fae84544c10481cc52f

Expected Behaviour:
- If no data in the Creator Pages, we should show our "no data" component

**Comment by newbreedofgeek** [comment]
@icegriffinguru can u login via a Mainnet wallet and test.

- Is it broken due to API not being deployed? IF So, can you pls "gracefully handle this" (at the moment it breaks when no web2 API)

**Comment by fuzzyduke** [comment]
Approved Fixed. Please note that the it has been reported by dev that due to some mismatches, items like count or displayig creator Data NFTs created doesnt show correctly on mainnet. Taking these mismatches into account and limitations to testing Dev PR on mainnet we can close this issue.
