### ISSUE TITLE
Elrond - Maiar App screen delay Approve step reloads the Data DEX session

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#95]
I take the first 2 steps from issue 2
3. At step 2 I scanned the QR code with Maiar app on wallet 1 and DO NOT APPROVE IT. The Maiar app is still on approve window
4.  I cancel the QR code window and I choose to connect with PC Maiar DeFi Wallet (with a DIFFERENT wallet - wallet 2). The Maiar app is still on approve window
5. I get connected on the web page with wallet 2.
6. I now press Approve on Maiar app (which is on wallet 1)
7. Suprize!! The web page now switches me immediately on wallet 1!! On wallet 2 I had 0 Itheum, on wallet 1 I had 340. I know this because the ballance changed when I pressed approve in Maiar app.

What needs to happen: 
- If user is on a Elrond connected session already and the Maiar app approve happens we detect the address has changed and log the user our as a precaution.

**Comment by newbreedofgeek** [comment]
Can fix this with #93 issue

**Comment by newbreedofgeek** [comment]
Can fix this with #93 issue

**Comment by damienen** [comment]
Solved in https://github.com/Itheum/data-dex/commit/801083bda3c6f838be6f6473c1d4144f2c336adb

**Comment by newbreedofgeek** [comment]
Tested and Not solved
