### ISSUE TITLE
Feature: Add to Favorite + Trending offers

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#952]
- User can add/remove an offer to their favorite (web2 API can save it... )
- These favorites appears in the "wallet" tab for favorite
- Based on the favorites of ALL users... we can generate a trending list of items (web2 api for trending items). trending = how many time something was added to favorite + trading activity (figure out how to "weight it")
- Show trending list on homepage, dashboard 
- Maybe also, if a user is looking at the details page for a Data NFT that's trending... we also show some icon that the item is "trending" (like a fire icon)

**Comment by newbreedofgeek** [comment]
- Needs web2 AP upgrade @bucurdavid 
- Some UIUX help from @harbzy

**Comment by newbreedofgeek** [comment]
@bucurdavid @Enciusan @damienen @fuzzyduke i've moving this to 1.6.

1.5 will be a smaller release with features needed for XDay

**Comment by bucurdavid** [comment]
After internal talks the implementation of this endpoint will relate to trending `Data NFTs` and not `offers`.

Proposed trending algorithm is:
$$\text{Data NFT}_{\text{trending rating}} = w_1 \cdot \text{total number of favorites} + w_2 \cdot e^{-\lambda \cdot \text{last interaction (in days)}} \cdot \text{total number of interactions}$$


- `w1` - is the number that controls the weight of total number of favorites of a Data NFT
- `w2` - is the number that control the weight of total number of interactions of a Data NFT
- `λ` - is the number that controls the weight of the last time a Data Nft had the last interaction in the marketplace
-  `e` - Euler's const is used for a smoother transition between trending Data NFTs

> [!IMPORTANT]  
> The algorithm takes into consideration the last interaction of a Data NFT to prevent high trending rankings in cases of inactivity. This ensures a smooth decay from trending even without the presence of other Data NFTs activity.

**Comment by damienen** [comment]
Solved. Closing.
