### ISSUE TITLE
Native Auth Integration with Data Marshal on Data DEX

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#959]
- Soon a new version of the SDk will by published which will have a new viewDataViaNativeAuth method.
- Use this method to allow a user to "view data" without the sign message workflow
- Once we do this, we can remove all the complex web wallet and other custom code we put into support sign message so we can simplify the codebase
- The ticket will need to match the implementation of native auth (i.e. duration of session, how we set origins etc) as the ticket : https://github.com/Itheum/explorer-dapp/issues/137

**Comment by damienen** [comment]
Tested all wallets. Expected behavior met. Closing. Good job, @icegriffinguru
