### ISSUE TITLE
Frontend integration of Favorite/Tranding Data NFTs (Data Dex)

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#969]

**Comment by fuzzyduke** [comment]
Adding favorite invokes no action on detail page.

![Image](https://github.com/Itheum/data-dex/assets/121969933/ac62b908-f871-4628-9743-1b16fbd036ad)

**Comment by fuzzyduke** [comment]
If there is only 1 favorite left in the wallet and it is toggled to be disabled then the last selection should be removed from the favorites tab in the wallet.

![Image](https://github.com/Itheum/data-dex/assets/121969933/3785d805-1c80-4a13-9f4b-3d4f1a9302c9)

**Comment by fuzzyduke** [comment]
In recent data NFTs section if the second data NFT is market as fav then.

selecting and deselcting the first NFT effectively deselects the second nft instead.

![Image](https://github.com/Itheum/data-dex/assets/121969933/3ef4ffc7-0141-45a7-bc5f-34acd7492263)


![Image](https://github.com/Itheum/data-dex/assets/121969933/a8d29f5f-14fc-4b5e-ab89-0c90b86f02fa)

**Comment by bucurdavid** [comment]
> Adding favorite invokes no action on detail page.
> 
> ![Image](https://private-user-images.githubusercontent.com/121969933/297836953-ac62b908-f871-4628-9743-1b16fbd036ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTExODcsIm5iZiI6MTcwNTY1MDg4NywicGF0aCI6Ii8xMjE5Njk5MzMvMjk3ODM2OTUzLWFjNjJiOTA4LWY4NzEtNDYyOC05NzQzLTFiMTZmYmQwMzZhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNzU0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDFjN2Y2ODA5ZjQzOWFmZDNkY2U3ZWMxYzM2NWJjZTFiYWQyODQyNzA2NjY3OTFiZmI4ODgwZjBjZTA4NzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sYXr2CiS9XoZICNyq41o0TVr-7rnrosPw3cqW72_I8E)

The testing url was not whitelisted.

**Comment by fuzzyduke** [comment]
Fixed.
