### ISSUE TITLE
Update price works for Defi Wallet but does not reflect for web wallet.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#976]
Update price works for Defi Wallet but does not reflect for web wallet.

1. Update price doesn't reflect when using web wallet.

Price for the last card was updated to 66 and the page refreshed but it still stayed at 3.06 Itheum
![image](https://github.com/Itheum/data-dex/assets/121969933/f33d1492-703c-4c28-b1ba-7843366c2542)

**Comment by fuzzyduke** [comment]
2. Same happens for delisting when using web wallet. The transaction concludes successfully but the listing is still seen.

**Comment by fuzzyduke** [comment]
Please also review listing and purchasing with web wallet. And if listing lists at the right time, with purchase of the last item the offer should be removed.

**Comment by bucurdavid** [comment]
Solved.Closing.
