### ISSUE TITLE
User Has reported that while trying to create a Data NFT with ledger, the sign window is too large.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#979]
User Has reported that while trying to create a Data NFT with ledger, the sign window is too large.
The user had to remove elements in inspect mode to sign the transaction.

![image](https://github.com/Itheum/data-dex/assets/121969933/af28ea4d-543c-41d1-9700-4b84f8141ceb)

**Comment by damienen** [comment]
Solved. Closing.
