### ISSUE TITLE
Connection issues seen with xportal on #859

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#984]
|Sourced from #982 

Tried to run a burn transaction with xportal. Upon signing in xportal, the below was seen. The sign dint seem to be acknowledged by the datadex.

@damienen @newbreedofgeek

Steps

connect to https://github.com/Itheum/data-dex/pull/859 using xportal.
Run a burn transaction on an item in the wallet.
Sign transaction in the wallet.
It is seen that no continuity is seen on the datadex after signing in the wallet.

Expected behaviour.

The transaction should have been processed and the count should have been reduced on the supply.
Note: This is not consistently reproduceable.

![image](https://github.com/Itheum/data-dex/assets/121969933/0cdcab22-945f-4298-95c3-c4b9d2bfaa8f)

This was encountered while purchasing via xportal as well, after signing the transaction in the wallet, continuity was not seen on the datadex. This is again not consistently reproduceable as purchases are also seen to go through normally with xportal at times.

![image](https://github.com/Itheum/data-dex/assets/121969933/b0e724f3-2240-4054-8cb2-3749eddb0496)

While attempting a second login to xportal the below is seen. Unsure of the impact of the message in the console.

Was able to scan the QR code and login using Xportal. However for a short period of time noticed the message "Invalid QR code" before it then successfully scanned the QR code and proceeded to successful login.

![image](https://github.com/Itheum/data-dex/assets/121969933/879dbdf8-a19d-4575-b1f9-543f6ba03781)

**Comment by newbreedofgeek** [comment]
Needs investigation. @icegriffinguru can do it

**Comment by damienen** [comment]
Not recurrent. Haven't seen in a long time. Will monitor, but closing
