### ISSUE TITLE
HOTFIX: We need fallback to marketRequirements returning undefined is certain boundary cases

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#991]

**Comment by damienen** [comment]
Let's follow our way of doing it with web2 stuff:
Try web2 (that fetches from web3 via cron) -> not working -> try web3 -> default to hardcoded or return error

This should make it way more stable.

PS: Another suggestion, let's use blast api for crons. Tried recently and it was working better than MX api + blast is normal use case is exactly for backends

**Comment by damienen** [comment]
Done. Closing.
